"""
#autogenerated#header#do#not#modify############################################
#
# File:        python_builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   16/03/2026
# Last Update: 17/03/2026, 18:02
# Version:     0.1.7
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """
Pure-Python backend generation.

The Python backend emits standalone Python modules that avoid NumPy and operate
on plain Python scalars and lists. It is primarily useful as a readable
reference backend, for debugging instruction lowering, and for environments
where a compiler or numeric array dependency is intentionally avoided.
"""

from ....aux import configured_zero_tol
from ...builder import Builder
from ...codecontainer import (
    AccumulateStatementLine,
    AssignmentStatementLine,
    CaptureContainer,
    CodeLine,
    CommentLine,
    DefinitionContainer,
    DefinitionLines,
    HookContainer,
    ImportContainer,
    ImportSectionContainer,
    IntCombineExpandContainer,
    MultiFrameExpandContainer,
    RoutineCallContainer,
    RoutineContainer,
)
from ...computeresource import ComputeResource
from ...context import Context
from ...instruction import (
    AffineOperationInstruction,
    BiLinearOperationInstruction,
)
from ...library import Library, LibRoutine
from ...libroutinevar import (
    ExternalImport,
    LibRoutineBufferVariable,
    LibRoutineConstant,
    LibRoutineInOutVariable,
    LibRoutineInputVariable,
    LibRoutineLocalVariable,
    LibRoutineOutputVariable,
    LibRoutineVariable,
    Numeric,
)


class PyNumeric(Numeric):
    """Python numeric wrapper."""


ZERO_TOL = configured_zero_tol()


class PyLibRoutineVariable(LibRoutineVariable):
    """Common python-side variable behaviour."""

    def expr_at(self, offset_string):
        return f"{self.name}[{offset_string}]"

    def get_zero_value(self):
        if self.dtype.startswith("i"):
            return "0"
        return "0.0"

    def generate_tozero_lines(self):
        zero_value = self.get_zero_value()
        if self.is_scalar:
            yield f"{self.expr()} = {zero_value}"
            return
        for offset in range(self.size):
            yield f"{self.at(offset).expr()} = {zero_value}"

    def get_definition_lines(self):
        if self.is_scalar:
            yield f"{self._name} = {self.get_zero_value()}"
            return
        yield f"{self._name} = [{self.get_zero_value()} for _ in range({self._size})]"


class PyLocalVariable(PyLibRoutineVariable, LibRoutineLocalVariable):
    """Local python variable."""


class PyDummyVariable(PyLibRoutineVariable):
    """Base class for python routine arguments."""

    _intent = None

    def as_argument_declaration(self):
        return self._name

    def get_definition_lines(self):
        return
        yield

    def expr(self):
        if self.is_scalar and type(self)._intent in {"WO", "RW"}:
            return f"{self.name}[0]"
        return super().expr()


class PyInputVariable(PyDummyVariable, LibRoutineInputVariable):
    """Read-only Python routine argument."""

    _intent = "RO"


class PyOutputVariable(PyDummyVariable, LibRoutineOutputVariable):
    """Write-only Python routine argument."""

    _intent = "WO"


class PyInOutVariable(PyDummyVariable, LibRoutineInOutVariable):
    """Read-write Python routine argument."""

    _intent = "RW"


class PyBufferVariable(PyInOutVariable, LibRoutineBufferVariable):
    """Buffer-backed Python routine argument."""

    _intent = "RW"


class PyConstant(PyLibRoutineVariable, LibRoutineConstant):
    """Python constant definition."""

    def get_definition_lines(self):
        if self.is_scalar:
            yield f"{self._name} = {self.value!r}"
            return
        yield f"{self._name} = {list(self.values)!r}"


class PyAssignmentStatementLine(AssignmentStatementLine):
    """Python assignment statement rendering."""

    BLUEPRINT = "{target} = {expression}"


class PyRoutineCallContainer(RoutineCallContainer):
    """Python function-call emission container."""

    def get_call_string(self):
        return f"{self.get_call_name()}({', '.join(self.get_args_list())})"


class PyCommentLine(CommentLine):
    """Python comment line rendering."""

    COMMENT_PREFIX = "# "


class PyMultiFrameExpandContainer(MultiFrameExpandContainer):
    """Lower multiframe ranges to Python ``for`` loops."""

    INDENT_BODY = True
    DEFAULT_LOCAL_VARIABLE_CLASS = PyLocalVariable

    def generate_head_containers(self):
        if self._multiframe_variable is not None:
            expr = self._multiframe_variable.expr()
            yield from self.codelines_from_text(
                f"for {expr} in range({self._min_value}, {self._max_value}):"
            )

    def generate_foot_containers(self):
        return
        yield


class PyIntCombineExpandContainer(IntCombineExpandContainer):
    """Combine split loop indices back into a single Python index."""

    INDENT_BODY = True
    DEFAULT_LOCAL_VARIABLE_CLASS = PyLocalVariable

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(
            f"{self._multiframe_variable.local} = {self._second.local} * {self._first.max_value} + {self._first.local}"
            + (
                f" + {self._multiframe_variable.min_value}"
                if self._multiframe_variable.min_value
                else ""
            )
        )
        yield from self.codelines_from_text(
            f"if {self._multiframe_variable.local} < {self._multiframe_variable.max_value}:"
        )

    def generate_foot_containers(self, **_):
        return
        yield


class PyRoutineContainer(RoutineContainer):
    """Python function container."""

    INDENT_BODY = True
    INPUT_VARIABLE_CLASS = PyInputVariable

    def get_signature(self):
        call_args = list(
            variable.as_argument_declaration()
            for variable in self.get_argument_variables()
        )
        return f"def {self.name}({', '.join(call_args)}):"

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(self.get_signature())

    def generate_prmb_containers(self, **kwargs):
        local_variables = list(self.get_local_variables())
        if local_variables:
            yield from self.comment_from_text("LOCAL") or []
            for variable in local_variables:
                yield DefinitionLines(variable, context=self.context, **kwargs)
            yield from self.codelines_from_text("")

    def generate_foot_containers(self, **_):
        return
        yield


class PyAccumulateStatementLine(AccumulateStatementLine):
    """Python in-place accumulation statement rendering."""

    UPDATE_BLUEPRINT = "{target} += {expression}"


class PyAffineContainer(PyAccumulateStatementLine):
    """Python affine accumulation line."""

    EXPRESSION_BLUEPRINT = "{a_value} * {x_expression} + {b_value}"

    def __init__(self, y, a, x, b, *, context, **params):
        super().__init__(
            target=y,
            value_dict={
                "target": y,
                "x_expression": x,
                "a_value": a,
                "b_value": b,
            },
            context=context,
            **params,
        )
        self.requires(y)
        self.requires(x)
        self.requires(a)
        self.requires(b)


class PyBilinearContainer(PyAccumulateStatementLine):
    """Python bilinear accumulation line."""

    EXPRESSION_BLUEPRINT = "{a_value} * {u_expression} * {v_expression}"

    def __init__(self, y, a, u, v, *, context, **params):
        super().__init__(
            target=y,
            value_dict={
                "target": y,
                "u_expression": u,
                "v_expression": v,
                "a_value": a,
            },
            context=context,
            **params,
        )
        self.requires(y)
        self.requires(u)
        self.requires(v)
        self.requires(a)


class PyImportContainer(ImportContainer):
    """Python ``from module import ...`` emission container."""

    INDENT_BODY = False

    def construct_code_lines(self, **_):
        names = ", ".join(routine.name for routine in self.routines)
        yield f"from {self.library.libname} import {names}"


class PyImportSectionContainer(ImportSectionContainer):
    """Python import section using bare routine names."""

    def compose_call_name(self, importable, library):
        del library
        return importable.name


class PyBuilder(Builder, identifier="PYTHON"):
    """Builder emitting pure-Python backend code."""

    _assignment_class = PyAssignmentStatementLine

    def create_libroutine_variable(
        self,
        *,
        name,
        dtype,
        status,
        size,
        assignment=None,
        namespace=None,
        **kwargs,
    ):
        if status & LibRoutineVariable.STATUS_BUFFER:
            return PyBufferVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        status = status & 3
        if status == LibRoutineVariable.STATUS_INPUT:
            return PyInputVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        if status == LibRoutineVariable.STATUS_OUTPUT:
            return PyOutputVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        if status == LibRoutineVariable.STATUS_INOUT:
            return PyInOutVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        return super().create_libroutine_variable(
            name=name,
            dtype=dtype,
            status=status,
            size=size,
            namespace=namespace,
            **kwargs,
        )

    def as_numeric(self, variable):
        return PyNumeric(variable)

    def lookup_status(self, status):
        if status.upper().strip() == "OUT":
            status = "INOUT"
        return super().lookup_status(status)

    def check_relevance(self, *variables, hook=None):
        remember = []
        for var in variables:
            if var is None:
                return False
            if isinstance(var, LibRoutineVariable):
                remember.append(var)
                continue
            if abs(var) < ZERO_TOL:
                return False
        if hook is not None:
            for var in remember:
                hook.requires(var)
        return True

    def handle_affine_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        alpha = instruction_dict.get("alpha", 1)
        beta = instruction_dict.get("beta", 0)

        x_var_real = context.namespace.find_assignment(
            type(src0), "real", exception_not_existing=False
        )
        x_var_imag = context.namespace.find_assignment(
            type(src0), "imag", exception_not_existing=False
        )
        y_var_real = context.namespace.find_assignment(
            type(tgt0), "real", exception_not_existing=False
        )
        y_var_imag = context.namespace.find_assignment(
            type(tgt0), "imag", exception_not_existing=False
        )

        x_var_offs = src0.offsets
        y_var_offs = tgt0.offsets
        a_real = self.wrap_lrv(alpha.real)
        a_imag = self.wrap_lrv(alpha.imag)
        b_real = self.wrap_lrv(beta.real)
        b_imag = self.wrap_lrv(beta.imag)

        combinations = [
            (y_var_real, a_real, x_var_real, b_real, 1),
            (y_var_real, a_imag, x_var_imag, b_real, -1),
            (y_var_imag, a_real, x_var_imag, b_imag, 1),
            (y_var_imag, a_imag, x_var_real, b_imag, 1),
        ]
        hook = HookContainer(context=context)
        first_real = True
        first_imag = True
        for y_var, a_val, x_var, b_val, sign in combinations:
            if y_var is y_var_real and not first_real:
                b_val = self.wrap_lrv(0.0)
            if y_var is y_var_imag and not first_imag:
                b_val = self.wrap_lrv(0.0)
            ret = self.check_relevance(y_var, a_val, x_var, b_val, hook=hook)
            if ret:
                yield PyAffineContainer(
                    y_var.at(*y_var_offs),
                    a_val * sign,
                    x_var.at(*x_var_offs),
                    b_val,
                    context=context,
                )
                if y_var is y_var_real:
                    first_real = False
                else:
                    first_imag = False

        yield CodeLine("", context=context)

    def handle_bilinear_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        src1 = instruction_dict.get("src1")
        alpha = instruction_dict.get("alpha")

        u_var_real = context.namespace.find_assignment(
            type(src0), "real", exception_not_existing=False
        )
        u_var_imag = context.namespace.find_assignment(
            type(src0), "imag", exception_not_existing=False
        )
        v_var_real = context.namespace.find_assignment(
            type(src1), "real", exception_not_existing=False
        )
        v_var_imag = context.namespace.find_assignment(
            type(src1), "imag", exception_not_existing=False
        )
        y_var_real = context.namespace.find_assignment(
            type(tgt0), "real", exception_not_existing=False
        )
        y_var_imag = context.namespace.find_assignment(
            type(tgt0), "imag", exception_not_existing=False
        )

        u_var_offs = src0.offsets
        v_var_offs = src1.offsets
        y_var_offs = tgt0.offsets
        a_real = self.wrap_lrv(alpha.real)
        a_imag = self.wrap_lrv(alpha.imag)

        hook = HookContainer(context=context)

        combinations = [
            (y_var_real, a_real, u_var_real, v_var_real, +1),
            (y_var_real, a_real, u_var_imag, v_var_imag, -1),
            (y_var_real, a_imag, u_var_imag, v_var_real, -1),
            (y_var_real, a_imag, u_var_real, v_var_imag, -1),
            (y_var_imag, a_real, u_var_imag, v_var_real, +1),
            (y_var_imag, a_real, u_var_real, v_var_imag, +1),
            (y_var_imag, a_imag, u_var_real, v_var_real, +1),
            (y_var_imag, a_imag, u_var_imag, v_var_imag, -1),
        ]

        for y_var, a_val, u_var, v_var, sign in combinations:
            ret = self.check_relevance(y_var, a_val, u_var, v_var, hook=hook)
            if ret:
                yield PyBilinearContainer(
                    y_var.at(*y_var_offs),
                    sign * a_val,
                    u_var.at(*u_var_offs),
                    v_var.at(*v_var_offs),
                    context=context,
                )

        yield CodeLine("", context=context)

    def create_external_array(self, *args, context, **kwargs):
        return Builder.create_external_array(
            self,
            *args,
            context=context,
            local_class=PyLocalVariable,
            constant_class=PyConstant,
        )


class PyComputeResource(ComputeResource):
    """Compute-resource description for the Python backend."""

    def create_mfe_container(
        self,
        *,
        context,
        local_variable_capture,
        name=None,
        loop_container=None,
        loop_capture=None,
    ) -> None | MultiFrameExpandContainer:
        del name, loop_container, loop_capture
        return PyMultiFrameExpandContainer(
            context=context,
            local_variable_capture=local_variable_capture,
        )

    def create_combine_container(
        self,
        first,
        second,
        *,
        context,
        local_variable_capture,
        name=None,
        loop_container=None,
        loop_capture=None,
    ) -> None | MultiFrameExpandContainer:
        del name, loop_container, loop_capture
        return PyIntCombineExpandContainer(
            first,
            second,
            context=context,
            local_variable_capture=local_variable_capture,
        )


class PyLibRoutine(LibRoutine):
    """Python lib routine."""


class PyLibrary(Library):
    """Python backend library representation."""

    BACKEND_IDENTIFIER = "python"
    FILEENDING = "py"
    INDENTSTR = "    "
    LIBROUTINE_CLASS = PyLibRoutine
    IMPORTLINE_CLASS = PyImportContainer
    DEFAULT_BUILDER = PyBuilder
    DEFAULT_CONTAINER_CLASS = PyRoutineContainer

    def __init__(
        self,
        plain_name,
        build_hash=None,
        resource=None,
        configuration=None,
        general_configuration=None,
    ):
        if resource is None:
            resource = PyComputeResource("PyResource")
        self._initialize_library_state(
            plain_name=plain_name,
            build_hash=build_hash,
            resource=resource,
            import_section_class=PyImportSectionContainer,
            backend_configuration=configuration,
            general_configuration=general_configuration,
        )

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text("# autogenerated python library")
        yield from self.codelines_from_text("")

    def generate_foot_containers(self, **_):
        return
        yield

    def generate_prmb_containers(self, **_):
        imports = list(self.import_capture.list_imports())
        if imports:
            for library, routines in imports:
                yield PyImportContainer(
                    library, routines, context=self.context
                )
            yield from self.codelines_from_text("")

        constants = list(self.definition_capture.captured)
        if constants:
            for variable in constants:
                for line in variable.get_definition_lines():
                    yield from self.codelines_from_text(line)
            yield from self.codelines_from_text("")

    def generate_clsg_containers(self, **_):
        return
        yield

    def get_to_zero_support_routine(self, dtype):
        """Return the external helper routine used to reset one buffer."""
        routine_name = f"phoenix_to_zero_{dtype}"
        existing = self[routine_name]
        if existing is not None:
            return existing
        zero_value = PyLocalVariable(name="tmp", dtype=dtype, no_entry=True).get_zero_value()
        code = [
            f"def {routine_name}(buffer, size):",
            f"    buffer[:size] = {zero_value}",
        ]
        return self._register_manual_routine(
            routine_name,
            code=code,
            arguments=[
                {
                    "name": "buffer",
                    "dtype": dtype,
                    "size": 1,
                    "status": "INOUT",
                    "assignment": ("buffer", "data"),
                },
                {
                    "name": "size",
                    "dtype": "i32",
                    "status": "IN",
                },
            ],
        )

    def get_codelines(self, indent=0):
        """get the codelines from the inner container object"""
        yield from self.get_codelines_head(indent=indent)
        yield from self.get_codelines_prmb(indent=indent + 0)
        yield indent, ""
        yield from self.iter_routine_codelines(indent=indent + 0)
        yield from self.get_codelines_clsg(indent=indent + 0)
        yield from self.get_codelines_foot(indent=indent)


PyBuilder.set_instruction_class_handler(
    AffineOperationInstruction, PyBuilder.handle_affine_instruction
)
PyBuilder.set_instruction_class_handler(
    BiLinearOperationInstruction, PyBuilder.handle_bilinear_instruction
)

PyRoutineContainer.set_comment_class(PyCommentLine)

PyBuilder.set_comment_class(PyCommentLine)
PyBuilder.set_routinecall_class(PyRoutineCallContainer)
