"""
#autogenerated#header#do#not#modify############################################
#
# File:        backend_opencl.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   19/03/2026
# Last Update: 19/03/2026, 20:47
# Version:     0.1.0
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """
OpenCL-backed ADAAs and coefficient backend definitions.

The OpenCL backend stores coefficient arrays as :mod:`pyopencl.array.Array`
instances. That keeps ``_data`` in the backend-native format while still
allowing efficient conversion to and from NumPy on demand. The same backend
object also owns the OpenCL context and command queue that generated wrappers
should reuse when compiling and launching kernels.
"""

from typing import Any

import numpy as np

from ....adaa import ComplexArrayADAA, ImagArrayADAA, RealArrayADAA
from ....coeffbackend import CoeffBackend

PROVIDE_OPENCL = False

try:
    import pyopencl as cl
    import pyopencl.array as cl_array
except ImportError:
    cl = None
    cl_array = None
else:
    PROVIDE_OPENCL = True


if PROVIDE_OPENCL:

    class OpenClCoeffBackend(CoeffBackend):
        """Coefficient backend storing data in OpenCL device arrays."""

        NP_DTYPE_LOOKUP = {
            "f32": np.float32,
            "f64": np.float64,
            "i32": np.int32,
            "i64": np.int64,
        }

        def __init__(self, context=None, queue=None, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._cl_cntxt = context
            self._cl_queue = queue

        def ensure_context(self):
            """Create the default OpenCL context and queue on first use."""
            if self._cl_cntxt is None:
                self._cl_cntxt = cl.create_some_context(interactive=False)
            if self._cl_queue is None:
                self._cl_queue = cl.CommandQueue(self._cl_cntxt)
            return self._cl_cntxt, self._cl_queue

        @property
        def context(self):
            """Return the backend-owned OpenCL context."""
            self.ensure_context()
            return self._cl_cntxt

        @property
        def queue(self):
            """Return the backend-owned OpenCL command queue."""
            self.ensure_context()
            return self._cl_queue

        def lookup_np_dtype(self, dtype: str):
            """Resolve the backend dtype token to a NumPy dtype."""
            if dtype not in type(self).NP_DTYPE_LOOKUP:
                raise ValueError(f"dtype {dtype} not understood")
            return type(self).NP_DTYPE_LOOKUP[dtype]

        def coeff_new_array(self, size: int, dtype: str):
            """
            Allocate a new backend-native coefficient array.

            :param size: Number of scalar entries to allocate.
            :param dtype: Backend dtype token such as ``"f64"``.
            :returns: A :class:`pyopencl.array.Array` on the backend queue.
            """
            self.ensure_context()
            np_dtype = self.lookup_np_dtype(dtype)
            return cl_array.zeros(self._cl_queue, size, dtype=np_dtype)

        def coeff_from_numpy(
            self,
            coeff_like: Any,
            nparray: np.ndarray,
            size: int,
            dtype: str,
        ) -> None:
            """
            Upload host data into an OpenCL coefficient array.

            :param coeff_like: Target device array.
            :param nparray: Source NumPy array.
            :param size: Expected flat size.
            :param dtype: Backend dtype token.
            """
            self.ensure_context()
            np_dtype = self.lookup_np_dtype(dtype)
            array = np.ascontiguousarray(nparray, dtype=np_dtype)
            if array.ndim != 1:
                raise ValueError("OpenCL backend expects 1D arrays.")
            if len(array) != size:
                raise ValueError(
                    f"Wrong input size {len(array)} for OpenCL dtype {dtype}, "
                    f"expected {size}."
                )
            coeff_like.set(array, queue=self._cl_queue)

        def coeff_to_numpy(
            self, coeff_like: Any, size: int, dtype: str
        ) -> np.ndarray:
            """
            Download an OpenCL coefficient array to NumPy.

            :param coeff_like: Source device array.
            :param size: Expected flat size.
            :param dtype: Backend dtype token.
            :returns: A detached NumPy copy of the device data.
            """
            self.ensure_context()
            np_dtype = self.lookup_np_dtype(dtype)
            array = coeff_like.get(queue=self._cl_queue)
            if size is not None and len(array) != size:
                raise ValueError(
                    f"Wrong OpenCL array size {len(array)} for dtype {dtype}, "
                    f"expected {size}."
                )
            return np.array(array, dtype=np_dtype, copy=True)

        def coeff_to_zero(self, coeff_like: Any, size: int, dtype: str):
            """
            Fill a backend-native array with zeros.

            :param coeff_like: Device array to reset.
            :param size: Expected flat size.
            :param dtype: Backend dtype token.
            """
            del size
            self.ensure_context()
            np_dtype = self.lookup_np_dtype(dtype)
            host = np.zeros(coeff_like.size, dtype=np_dtype)
            cl.enqueue_copy(self._cl_queue, coeff_like.data, host)

        def coeff_copy_data(self, targ: Any, source: Any, size: int, dtype: str):
            """
            Copy one backend-native array into another.

            :param targ: Target device array.
            :param source: Source device array.
            :param size: Expected flat size.
            :param dtype: Backend dtype token.
            """
            del size, dtype
            self.ensure_context()
            host = np.ascontiguousarray(source.get(queue=self._cl_queue))
            cl.enqueue_copy(self._cl_queue, targ.data, host)

        def coeff_linop(
            self,
            arr_r: Any,
            /,
            scal_a: float | None,
            arr_x: Any,
            scal_b: float | None,
            arr_y: Any,
            *,
            size: int,
            dtype: str,
            inplace: bool = False,
        ):
            """
            Perform the backend's basic linear operation on device arrays.

            :param arr_r: Result array on the device.
            :param scal_a: Optional scale for ``arr_x``.
            :param arr_x: First input array or ``None``.
            :param scal_b: Optional scale for ``arr_y`` or scalar offset if
                ``arr_y`` is ``None``.
            :param arr_y: Second input array or ``None``.
            :param size: Expected flat size.
            :param dtype: Backend dtype token.
            :param inplace: Whether to accumulate into ``arr_r``.
            """
            del size
            self.ensure_context()
            np_dtype = self.lookup_np_dtype(dtype)
            if arr_r is None:
                return
            if inplace:
                host = np.ascontiguousarray(
                    arr_r.get(queue=self._cl_queue), dtype=np_dtype
                )
            else:
                host = np.zeros(arr_r.size, dtype=np_dtype)

            if arr_x is not None:
                host_x = np.ascontiguousarray(
                    arr_x.get(queue=self._cl_queue), dtype=np_dtype
                )
                if scal_a is None:
                    host = host + host_x
                else:
                    host = host + np_dtype(scal_a) * host_x

            if arr_y is not None:
                host_y = np.ascontiguousarray(
                    arr_y.get(queue=self._cl_queue), dtype=np_dtype
                )
                if scal_b is None:
                    host = host + host_y
                else:
                    host = host + np_dtype(scal_b) * host_y

            cl.enqueue_copy(self._cl_queue, arr_r.data, np.ascontiguousarray(host))


    class OpenClCA(
        ComplexArrayADAA,
        backend=OpenClCoeffBackend(),
        identifier="OPENCL",
        is_anchor=True,
    ):
        """Complex ADAA backed by OpenCL device arrays."""


    class OpenClRA(
        RealArrayADAA,
        backend=OpenClCoeffBackend(),
        identifier="OPENCL",
        is_anchor=True,
    ):
        """Real ADAA backed by OpenCL device arrays."""


    class OpenClIA(
        ImagArrayADAA,
        backend=OpenClCoeffBackend(),
        identifier="OPENCL",
        is_anchor=True,
    ):
        """Purely imaginary ADAA backed by OpenCL device arrays."""


    __all__ = [
        "PROVIDE_OPENCL",
        "OpenClCoeffBackend",
        "OpenClCA",
        "OpenClRA",
        "OpenClIA",
    ]
else:
    __all__ = ["PROVIDE_OPENCL"]
