"""
#autogenerated#header#do#not#modify############################################
#
# File:        opencl_pywrapper_library.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   19/03/2026
# Last Update: 19/03/2026, 20:47
# Version:     0.1.0
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """
Python wrapper layer for generated OpenCL libraries.

The OpenCL wrapper compiles generated ``.cl`` sources through :mod:`pyopencl`
and launches kernels directly from Python. It reuses the context and queue
owned by the assigned OpenCL ADAA backend whenever possible so that ADAA data
and generated kernels operate on the same device memory.
"""

from os import PathLike
from pathlib import Path

import numpy as np

from ...libroutinevar import (
    LibRoutineInputVariable,
    LibRoutineOutputVariable,
    LibRoutineInOutVariable,
)
from .opencl_builder import (
    OpenCLKernelGroupRequest,
    OpenCLKernelLocalRequest,
)
from ..pywrapper_library import (
    PyWrapperLibraryBase,
    WrapperBase,
    _RequestValue,
)

try:
    import pyopencl as cl
    import pyopencl.array as cl_array
except ImportError:
    cl = None
    cl_array = None


class OpenCLWrapper(WrapperBase):
    """Adapt wrapper arguments to OpenCL kernel launches."""

    NP_DTYPE_LOOKUP = {
        "f64": np.float64,
        "f32": np.float32,
        "i64": np.int64,
        "i32": np.int32,
    }

    def __init__(self, *args, queue=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._queue = queue

    @property
    def queue(self):
        """Return the command queue used for kernel launches."""
        return self._queue

    def call(self, *args, **kwargs):
        """Prepare arguments, launch the kernel, and extract return ADAAs."""
        self.prepare_buffers()
        self.prepare_returns()
        self.prepare_inputs(args, kwargs)
        global_size, local_size = self.get_launch_configuration()
        for all_args in self.prepare_arguments_iter():
            call_args, _keepalive = self.adapt_call_arguments(all_args)
            event = self._exec(self._queue, global_size, local_size, *call_args)
            event.wait()
        return self.extract_from_returns()

    def get_launch_configuration(self):
        """Compute ``global_size`` and ``local_size`` from kernel requests."""
        container = self.libroutine.container
        if container is None or not self.libroutine.is_kernel:
            raise ValueError("OpenCL wrappers can only launch kernel routines.")

        local = {0: 1, 1: 1, 2: 1}
        groups = {0: 1, 1: 1, 2: 1}
        for variable in container.get_kernel_variables():
            axis = int(getattr(variable, "launch_axis", 0))
            extent = max(1, int(variable.launch_extent))
            if isinstance(variable, OpenCLKernelLocalRequest):
                local[axis] = max(local[axis], extent)
            elif isinstance(variable, OpenCLKernelGroupRequest):
                groups[axis] = max(groups[axis], extent)

        global_size = tuple(local[axis] * groups[axis] for axis in (0, 1, 2))
        local_size = tuple(local[axis] for axis in (0, 1, 2))
        return self._trim_dims(global_size), self._trim_dims(local_size)

    def _trim_dims(self, dims):
        """Trim trailing singleton dimensions for PyOpenCL launch tuples."""
        dims = [max(1, int(val)) for val in dims]
        while len(dims) > 1 and dims[-1] == 1:
            dims.pop()
        return tuple(dims)

    def adapt_call_arguments(self, all_args):
        """Convert wrapper arguments to OpenCL kernel arguments."""
        converted = []
        keepalive = []
        for value, spec in zip(all_args, self.argument_specs):
            arg_type, variable, _name, _key, _adaa = spec
            call_arg, refs = self.convert_argument(
                value=value,
                variable=variable,
                arg_type=arg_type,
            )
            converted.append(call_arg)
            keepalive.extend(refs)
        return tuple(converted), keepalive

    def convert_argument(self, *, value, variable, arg_type):
        """Convert one wrapper argument for OpenCL execution."""
        del arg_type
        if isinstance(value, _RequestValue):
            value = value.value

        np_dtype = type(self).NP_DTYPE_LOOKUP[variable.dtype]
        if variable.is_scalar:
            return self.convert_scalar_argument(
                value=value,
                variable=variable,
                np_dtype=np_dtype,
            )
        return self.convert_array_argument(
            value=value,
            variable=variable,
            np_dtype=np_dtype,
        )

    def convert_scalar_argument(self, *, value, variable, np_dtype):
        """Convert a scalar OpenCL argument."""
        if isinstance(variable, LibRoutineInputVariable):
            if isinstance(value, np.ndarray):
                array = np.asarray(value, dtype=np_dtype).reshape(-1)
                if array.size != 1:
                    raise ValueError(
                        f"Scalar OpenCL argument {variable.name} expects exactly "
                        f"one value."
                    )
                return np_dtype(array[0]), [array]
            if hasattr(value, "item"):
                return np_dtype(value.item()), []
            return np_dtype(value), []

        call_arg, refs = self.convert_array_argument(
            value=value,
            variable=variable,
            np_dtype=np_dtype,
        )
        return call_arg, refs

    def convert_array_argument(self, *, value, variable, np_dtype):
        """Convert an array OpenCL argument."""
        if cl_array is not None and isinstance(value, cl_array.Array):
            self.validate_device_array(
                value=value,
                variable=variable,
                np_dtype=np_dtype,
            )
            return value.data, [value]

        if isinstance(variable, LibRoutineInputVariable):
            array = np.asarray(value, dtype=np_dtype)
            if array.ndim != 1:
                raise ValueError(
                    f"OpenCL wrapper expects 1D storage for argument "
                    f"{variable.name}."
                )
            if variable.size is not None and len(array) != variable.size:
                raise ValueError(
                    f"OpenCL wrapper expects size {variable.size} for "
                    f"{variable.name}, got {len(array)}."
                )
            if not array.flags["C_CONTIGUOUS"]:
                array = np.ascontiguousarray(array, dtype=np_dtype)
            device_array = cl_array.to_device(self._queue, array)
            return device_array.data, [array, device_array]

        raise ValueError(
            f"Output-capable OpenCL argument {variable.name} must be provided "
            f"as an OpenCL ADAA or pyopencl.array.Array."
        )

    def validate_device_array(self, *, value, variable, np_dtype):
        """Validate dtype, size, and context of a device-backed argument."""
        if np.dtype(value.dtype) != np.dtype(np_dtype):
            raise ValueError(
                f"OpenCL argument {variable.name} expects dtype "
                f"{np.dtype(np_dtype)}, got {np.dtype(value.dtype)}."
            )
        if variable.size is not None and int(value.size) != int(variable.size):
            raise ValueError(
                f"OpenCL wrapper expects size {variable.size} for "
                f"{variable.name}, got {value.size}."
            )

        context = self.get_array_context(value)
        if context is not None and context != self._queue.context:
            raise ValueError(
                f"OpenCL argument {variable.name} belongs to a different "
                f"context than the wrapper queue."
            )

    def get_array_context(self, value):
        """Extract the OpenCL context associated with a device array."""
        data = getattr(value, "data", None)
        if data is not None and hasattr(data, "context"):
            return data.context
        queue = getattr(value, "queue", None)
        if queue is not None:
            return queue.context
        return None


class OpenCLPyWrapperLibrary(PyWrapperLibraryBase):
    """Python wrapper library for generated OpenCL kernels."""

    WRAPPER_CLASS = OpenCLWrapper

    def __init__(
        self,
        wrapped_library,
        wrapper_lib=None,
        *,
        context=None,
        queue=None,
        build_options=None,
        build_hash=None,
    ):
        if cl is None or cl_array is None:
            raise ImportError("pyopencl is required for OpenCL wrapper libraries")

        backend = self._infer_opencl_backend(wrapped_library)
        if context is None and backend is not None:
            context = backend.context
        if queue is None and backend is not None:
            queue = backend.queue
        if context is None:
            context = cl.create_some_context(interactive=False)
        if queue is None:
            queue = cl.CommandQueue(context)

        self._context = context
        self._queue = queue
        self._build_options = list(build_options or [])
        wrapper_lib = self._prepare_wrapper_lib(
            wrapped_library,
            wrapper_lib or wrapped_library.filename,
        )
        super().__init__(
            wrapped_library,
            wrapper_lib=wrapper_lib,
            build_hash=build_hash,
        )

    @property
    def context(self):
        """Return the OpenCL context used for compilation and execution."""
        return self._context

    @property
    def queue(self):
        """Return the command queue used for kernel launches."""
        return self._queue

    def _infer_opencl_backend(self, wrapped_library):
        """Try to reuse the backend attached to assigned OpenCL ADAAs."""
        backends = []
        for _name, libroutine in wrapped_library.content:
            for _source, assignment in libroutine.daa_assignments or []:
                adaa_class, _status = assignment
                backend = getattr(adaa_class, "_BACKEND", None)
                if backend is None:
                    continue
                if hasattr(backend, "context") and hasattr(backend, "queue"):
                    backends.append(backend)

        unique = []
        seen = set()
        for backend in backends:
            ident = id(backend)
            if ident in seen:
                continue
            seen.add(ident)
            unique.append(backend)

        if len(unique) > 1:
            raise ValueError(
                "Multiple OpenCL backends/contexts detected in the wrapped "
                "library assignments. Pass context=... and queue=... explicitly."
            )
        if unique:
            return unique[0]
        return None

    def _prepare_wrapper_lib(self, wrapped_library, wrapper_lib):
        """Compile the OpenCL source into a :class:`pyopencl.Program`."""
        if isinstance(wrapper_lib, cl.Program):
            return wrapper_lib

        if isinstance(wrapper_lib, (str, PathLike)):
            source_path = Path(wrapper_lib)
            if not source_path.is_absolute():
                source_path = Path(
                    wrapped_library.relative_to_basepath(wrapper_lib)
                )
            if source_path.exists():
                source = source_path.read_text()
                build_options = [
                    *self._build_options,
                    "-I",
                    str(source_path.parent.resolve()),
                ]
            else:
                source = str(wrapper_lib)
                build_options = list(self._build_options)
            return cl.Program(self._context, source).build(options=build_options)

        if hasattr(wrapper_lib, "build"):
            return wrapper_lib.build(options=self._build_options)

        return wrapper_lib

    def resolve_wrapper_callable(self, libroutine_name, libroutine):
        """Resolve and configure the compiled kernel entry point."""
        if not libroutine.is_kernel:
            raise ValueError(
                "Only OpenCL kernel routines can be wrapped directly. "
                "Helper routines must be called from within another kernel."
            )
        kernel = getattr(self.wrapper_lib, libroutine_name)
        self.configure_kernel_signature(kernel, libroutine)
        return kernel

    def configure_kernel_signature(self, kernel, libroutine):
        """Configure scalar argument dtypes for PyOpenCL kernel dispatch."""
        kernel.set_scalar_arg_dtypes(
            [self.create_scalar_arg_dtype(arg) for arg in libroutine.get_arguments()]
        )

    def create_scalar_arg_dtype(self, arg):
        """Return the NumPy dtype for scalar-by-value kernel arguments."""
        if not arg.is_scalar:
            return None
        if not isinstance(arg, LibRoutineInputVariable):
            return None
        return OpenCLWrapper.NP_DTYPE_LOOKUP[arg.dtype]

    def create_wrapper_instance(
        self,
        name,
        exe,
        arguments,
        libroutine,
        *,
        reuse_buffer=False,
    ):
        """Create the wrapper instance bound to the library queue."""
        return type(self).WRAPPER_CLASS(
            name=name,
            exe=exe,
            arguments=arguments,
            libroutine=libroutine,
            reuse_buffer=reuse_buffer,
            queue=self._queue,
        )
