"""
#autogenerated#header#do#not#modify############################################
#
# File:        backend_numpy.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   19/03/2026
# Last Update: 19/03/2026, 20:44
# Version:     0.1.0
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """
NumPy-backed ADAA and coefficient backend definitions.

This module contains the standard host-array backend based on NumPy arrays.
The NumPy coefficient backend is also reused by the Fortran backend because
``f2py`` interoperates naturally with NumPy-owned arrays.
"""

from typing import Any

import numpy as np

from ....adaa import ComplexArrayADAA, ImagArrayADAA, RealArrayADAA
from ....coeffbackend import CoeffBackend


class NumPyCoeffBackend(CoeffBackend):
    """Coefficient backend storing arrays as NumPy host arrays."""

    def coeff_new_array(self, size: int, dtype: str):
        match dtype:
            case "f32":
                return np.zeros(size, dtype=np.float32)
            case "f64":
                return np.zeros(size, dtype=np.float64)
            case "i32":
                return np.zeros(size, dtype=np.int32)
            case "i64":
                return np.zeros(size, dtype=np.int64)
            case _:
                raise ValueError(f"dtype {dtype} not understood")

    def coeff_from_numpy(
        self,
        coeff_like: Any,
        nparray: np.ndarray,
        size: int,
        dtype: str,
    ) -> None:
        del size
        if dtype in ("f32", "f64"):
            if nparray.dtype in [np.float32, np.float64]:
                coeff_like[:] = nparray
            else:
                raise ValueError(
                    f"Wrong input datatype {nparray.dtype} for dtype {dtype}."
                )
        elif dtype in ("i32", "i64"):
            if nparray.dtype in [np.int32, np.int64]:
                coeff_like[:] = nparray
            else:
                raise ValueError(
                    f"Wrong input datatype {nparray.dtype} for dtype {dtype}."
                )
        else:
            raise ValueError(f"dtype {dtype} not understood")

    def coeff_to_numpy(
        self, coeff_like: Any, size: int, dtype: str
    ) -> np.ndarray:
        del size
        match dtype:
            case "f32":
                return np.array(coeff_like, dtype=np.float32)
            case "f64":
                return np.array(coeff_like, dtype=np.float64)
            case "i32":
                return np.array(coeff_like, dtype=np.int32)
            case "i64":
                return np.array(coeff_like, dtype=np.int64)
            case _:
                raise ValueError(f"dtype {dtype} not understood")

    def coeff_to_zero(self, coeff_like: Any, size: int, dtype: str):
        del size, dtype
        coeff_like.fill(0)

    def coeff_linop(
        self,
        arr_r: Any,
        /,
        scal_a: float | None,
        arr_x: Any,
        scal_b: float | None,
        arr_y: Any,
        *,
        size: int,
        dtype: str,
        inplace: bool = False,
    ):
        del size, dtype
        if arr_r is None:
            return
        if not inplace and arr_x is None:
            arr_r[:] = 0
        elif arr_x is not None:
            match (inplace, scal_a):
                case (True, None):
                    arr_r[:] += arr_x
                case (True, scal_a):
                    arr_r[:] += scal_a * arr_x
                case (False, None):
                    arr_r[:] = arr_x
                case (False, scal_a):
                    arr_r[:] = scal_a * arr_x

        match (scal_b, arr_y):
            case (None, None):
                return
            case (_, None):
                return
            case (None, arr_y):
                arr_r[:] += arr_y
            case (scal_b, arr_y):
                arr_r[:] += scal_b * arr_y


class NumPyCA(
    ComplexArrayADAA,
    backend=NumPyCoeffBackend(),
    identifier="NUMPY",
    is_anchor=True,
):
    """Complex ADAA using NumPy arrays as storage."""


class NumPyRA(
    RealArrayADAA,
    backend=NumPyCoeffBackend(),
    identifier="NUMPY",
    is_anchor=True,
):
    """Real ADAA using NumPy arrays as storage."""


class NumPyIA(
    ImagArrayADAA,
    backend=NumPyCoeffBackend(),
    identifier="NUMPY",
    is_anchor=True,
):
    """Purely imaginary ADAA using NumPy arrays as storage."""


__all__ = [
    "NumPyCoeffBackend",
    "NumPyCA",
    "NumPyRA",
    "NumPyIA",
]
