"""
#autogenerated#header#do#not#modify############################################
#
# File:        c_builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   13/03/2026
# Last Update: 19/03/2026, 12:39
# Version:     0.1.13
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """
C backend code generation and C-oriented makefile targets.

This module lowers Phoenix instruction trees to C source and header files,
using explicit routine variables, semicolon-terminated statements, C loop
containers, and C ABI wrapper conventions. It also provides C-specific
makefile target blueprints for object and shared-library compilation.
"""

from ....aux import configured_zero_tol, multiline_iterable
from ...backend_config import Configuration
from ...builder import Builder
from .c_atomic import register_c_atomic_handlers
from ...codecontainer import (
    AccumulateStatementLine,
    AssignmentStatementLine,
    CodeLine,
    CommentLine,
    DefinitionLines,
    DefinitionContainer,
    HookContainer,
    ImportContainer,
    ImportSectionContainer,
    IntCombineExpandContainer,
    MultiFrameExpandContainer,
    RoutineCallContainer,
    RoutineContainer,
    CaptureContainer,
)
from ...computeresource import ComputeResource
from ...context import Context
from ...instruction import (
    AffineOperationInstruction,
    BiLinearOperationInstruction,
)
from ...library import Library, LibRoutine
from ...makefile import (
    MFTHeader,
    MFTObject,
    MFTSharedLibrary,
)
from ..support_target import BackendSupportBuildTarget
from ...libroutinevar import (
    ExternalImport,
    LibRoutineBufferVariable,
    LibRoutineConstant,
    LibRoutineInOutVariable,
    LibRoutineInputVariable,
    LibRoutineLocalVariable,
    LibRoutineOutputVariable,
    LibRoutineVariable,
    Numeric,
)
from ....toolbox.logger import GLOBAL_LOGGER

_GENERAL_CONFIG = Configuration.general()
GLOBAL_LOGGER.set_loglevel(
    _GENERAL_CONFIG.get_nested("logging", "level", default="DEBUG")
)
GLOBAL_LOGGER.log_to_stdout(
    _GENERAL_CONFIG.get_nested("logging", "stdout", default=False)
)
ZERO_TOL = configured_zero_tol()


class CMFTObject(MFTObject):
    """C object-file target with a C compiler blueprint."""

    def __init__(
        self,
        name,
        *,
        source,
        dependencies=None,
        compiler=None,
        flags=None,
        silent=None,
        configuration=None,
    ):
        super().__init__(
            name,
            source=source,
            dependencies=dependencies,
            silent=silent,
        )
        self._configuration = (
            Configuration.for_backend("c")
            if configuration is None
            else configuration.clone()
        )
        if compiler is None:
            compiler = self._configuration.get_nested(
                "executables", "compiler", default="cc"
            )
        self._compiler = compiler
        self._flags = [
            *self._configuration.get_nested("flags", "object", default=[]),
            *(flags or []),
            *self._configuration.get_nested(
                "flags", "extra_object", default=[]
            ),
        ]

    def generate(self, *flags):
        summary = self.get_dependency_summary()
        direct_dependencies = list(self.dependencies)
        if not direct_dependencies:
            raise ValueError(
                f"{type(self).__name__} expects one direct source dependency."
            )
        source_files = list(
            direct_dependencies[0].get_compile_input_contributions()
        )
        if len(source_files) != 1:
            raise ValueError(
                f"{type(self).__name__} expects exactly one compile input."
            )
        cmd_flags = [
            *self._flags,
            *flags,
            *summary["compile_flags"],
            self._join_flags(
                self._configuration.get_nested(
                    "prefixes", "include", default="-I"
                ),
                summary["include_dirs"],
            ),
        ]
        cmd_flags = " ".join(flag for flag in cmd_flags if flag)
        yield (
            f"{self._compiler} -c {source_files[0]} -o {self.target_name()}"
            + (f" {cmd_flags}" if cmd_flags else "")
        )


class CMFTSharedLibrary(MFTSharedLibrary):
    """C shared-library target with a C linker blueprint."""

    def __init__(
        self,
        name,
        dependencies=None,
        *,
        linker=None,
        flags=None,
        silent=None,
        configuration=None,
    ):
        super().__init__(name, dependencies=dependencies, silent=silent)
        self._configuration = (
            Configuration.for_backend("c")
            if configuration is None
            else configuration.clone()
        )
        if linker is None:
            linker = self._configuration.get_nested(
                "executables", "linker", default="cc"
            )
        self._linker = linker
        self._flags = [
            *self._configuration.get_nested("flags", "shared", default=[]),
            *(flags or []),
            *self._configuration.get_nested(
                "flags", "extra_shared", default=[]
            ),
        ]

    def generate(self, *flags):
        summary = self.get_dependency_summary()
        link_inputs = " ".join(summary["link_inputs"])
        cmd_flags = [
            *self._flags,
            *flags,
            *summary["link_flags"],
            self._join_flags(
                self._configuration.get_nested(
                    "prefixes", "library", default="-L"
                ),
                summary["library_dirs"],
            ),
        ]
        cmd_flags = " ".join(flag for flag in cmd_flags if flag)
        yield (
            f"{self._linker} -o {self.target_name()} {link_inputs}"
            + (f" {cmd_flags}" if cmd_flags else "")
        )


class CNumeric(Numeric):
    """C version of a numeric."""


class CLibRoutineVariable(LibRoutineVariable):
    """Shared C variable behaviour."""

    DTYPE_LOOKUP = {
        "f64": "double",
        "f32": "float",
        "i64": "int64_t",
        "i32": "int32_t",
    }

    def lookup_dtype(self, dtype):
        if dtype in type(self).DTYPE_LOOKUP:
            return type(self).DTYPE_LOOKUP[dtype]
        raise ValueError(f"Unknown dtype: {dtype}")

    def expr_at(self, offset_string):
        return f"{self.name}[{offset_string}]"

    def get_zero_value(self):
        if self.dtype == "f32":
            return "0.0f"
        if self.dtype.startswith("f") or self.dtype.startswith("c"):
            return "0.0"
        return "0"

    def generate_tozero_lines(self):
        zero_value = self.get_zero_value()
        if self.is_scalar:
            yield f"{self.expr()} = {zero_value};"
            return
        yield f"phoenix_zero_{self.dtype}({self.name}, {self.size});"

    def get_definition_lines(self) -> str:
        dtype = self.lookup_dtype(self._dtype)
        if self.is_scalar:
            yield f"{dtype} {self._name};"
            return
        yield f"{dtype} {self._name}[{self._size}];"


class CLocalVariable(CLibRoutineVariable, LibRoutineLocalVariable):
    """Local C variable."""


class CDummyVariable(CLibRoutineVariable):
    """Base class for C routine arguments."""

    _intent = None

    def _intent_is_const(self):
        return type(self)._intent == "RO"

    def _intent_is_pointer(self):
        return type(self)._intent in {"WO", "RW"}

    def get_definition_lines(self) -> str:
        yield self.as_argument_declaration()

    def as_argument_declaration(self):
        dtype = self.lookup_dtype(self._dtype)
        const = "const " if self._intent_is_const() else ""
        if self.is_scalar:
            if self._intent_is_pointer():
                return f"{dtype} *{self._name}"
            return f"{const}{dtype} {self._name}"
        return f"{const}{dtype} *{self._name}"

    def expr(self):
        if self.is_scalar and self._intent_is_pointer():
            return f"(*{self.name})"
        return super().expr()


class CInputVariable(CDummyVariable, LibRoutineInputVariable):
    """Read-only C argument."""

    _intent = "RO"


class COutputVariable(CDummyVariable, LibRoutineOutputVariable):
    """Write-only C argument."""

    _intent = "WO"


class CInOutVariable(CDummyVariable, LibRoutineInOutVariable):
    """Read-write C argument."""

    _intent = "RW"


class CBufferVariable(CInOutVariable, LibRoutineBufferVariable):
    """Buffer-backed C argument."""

    _intent = "RW"


class CConstant(CLibRoutineVariable, LibRoutineConstant):
    """C constant representation."""

    def get_definition_lines(self) -> str:
        dtype = self.lookup_dtype(self._dtype)
        if self.is_scalar:
            yield f"static const {dtype} {self._name} = {self.value};"
            return

        prefix = f"static const {dtype} {self._name}[{self.size}] = {{"
        values = [
            int(v) if self.dtype[0] == "i" else float(v) for v in self.values
        ]
        for line in multiline_iterable(
            values,
            separator=", ",
            max_line_length=100,
            indent="",
            extra_indent="    ",
            linebreak="",
            prefix=prefix,
            suffix="};",
            prefix_suffix_lines=False,
        ):
            yield line


class CAssignmentStatementLine(AssignmentStatementLine):
    """C assignment statement."""

    BLUEPRINT = "{target} = {expression};"


class CRoutineCallContainer(RoutineCallContainer):
    """C function call."""

    def get_call_string(self):
        return f"{self.get_call_name()}({', '.join(self.get_args_list())});"


class CCommentLine(CommentLine):
    """C line comment."""

    COMMENT_PREFIX = "// "


class CMultiFrameExpandContainer(MultiFrameExpandContainer):
    """C `for`-loop for multiframe expansion."""

    INDENT_BODY = True
    DEFAULT_LOCAL_VARIABLE_CLASS = CLocalVariable

    def generate_head_containers(self):
        if self._multiframe_variable is not None:
            expr = self._multiframe_variable.expr()
            yield from self.codelines_from_text(
                f"for ({expr} = {self._min_value}; {expr} < {self._max_value}; ++{expr}) {{"
            )

    def generate_foot_containers(self):
        if self._multiframe_variable is not None:
            yield from self.codelines_from_text("}")


class CIntCombineExpandContainer(IntCombineExpandContainer):
    """Helper container combining split integer loop indices in C."""

    INDENT_BODY = True
    DEFAULT_LOCAL_VARIABLE_CLASS = CLocalVariable

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(
            f"{self._multiframe_variable.local} = {self._second.local} * {self._first.max_value} + {self._first.local}"
            + (
                f" + {self._multiframe_variable.min_value}"
                if self._multiframe_variable.min_value
                else ""
            )
            + ";"
        )
        yield from self.codelines_from_text(
            f"if ({self._multiframe_variable.local} < {self._multiframe_variable.max_value}) {{"
        )

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text("}")


class CRoutineContainer(RoutineContainer):
    """C function container."""

    INDENT_BODY = True
    INPUT_VARIABLE_CLASS = CInputVariable

    def get_signature(self, *, terminate=False):
        call_args = list(
            variable.as_argument_declaration()
            for variable in self.get_argument_variables()
        )
        if not call_args:
            args_string = "void"
        else:
            args_string = ", ".join(call_args)
        suffix = ";" if terminate else ""
        return f"void {self.name}({args_string}){suffix}"

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(
            self.get_signature(terminate=False)
        )
        yield from self.codelines_from_text("{")

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text("}")

    def generate_prmb_containers(self, **kwargs):
        local_variables = list(self.get_local_variables())
        if not local_variables:
            return
        yield from self.comment_from_text("LOCAL") or []
        for variable in local_variables:
            yield DefinitionLines(variable, context=self.context, **kwargs)
        yield from self.codelines_from_text("")


class CAccumulateStatementLine(AccumulateStatementLine):
    """C accumulation statement."""

    UPDATE_BLUEPRINT = "{target} += {expression};"


class CAffineContainer(CAccumulateStatementLine):
    """Affine update operation `y += a * x + b`."""

    EXPRESSION_BLUEPRINT = "{a_value} * {x_expression} + {b_value}"

    def __init__(self, y, a, x, b, *, context, **params):
        super().__init__(
            target=y,
            value_dict={
                "target": y,
                "x_expression": x,
                "a_value": a,
                "b_value": b,
            },
            context=context,
            **params,
        )
        self.requires(y)
        self.requires(x)
        self.requires(a)
        self.requires(b)


class CBilinearContainer(CAccumulateStatementLine):
    """Bilinear update operation `z += a * x * y`."""

    EXPRESSION_BLUEPRINT = "{a_value} * {u_expression} * {v_expression}"

    def __init__(self, y, a, u, v, *, context, **params):
        super().__init__(
            target=y,
            value_dict={
                "target": y,
                "u_expression": u,
                "v_expression": v,
                "a_value": a,
            },
            context=context,
            **params,
        )
        self.requires(y)
        self.requires(u)
        self.requires(v)
        self.requires(a)


class CImportContainer(ImportContainer):
    """C include import."""

    INDENT_BODY = False

    def construct_code_lines(self, **_):
        yield f'#include "{self.library.libname}.h"'


class CImportSectionContainer(ImportSectionContainer):
    """C import handling using headers and plain routine names."""

    def compose_call_name(self, importable, library):
        return importable.name


class CBuilder(Builder, identifier="C"):
    """C Builder."""

    _assignment_class = CAssignmentStatementLine

    def create_libroutine_variable(
        self,
        *,
        name,
        dtype,
        status,
        size,
        assignment=None,
        namespace=None,
        **kwargs,
    ):
        if status & LibRoutineVariable.STATUS_BUFFER:
            return CBufferVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        status = status & 3
        if status == LibRoutineVariable.STATUS_INPUT:
            return CInputVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        if status == LibRoutineVariable.STATUS_OUTPUT:
            return COutputVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        if status == LibRoutineVariable.STATUS_INOUT:
            return CInOutVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        return super().create_libroutine_variable(
            name=name,
            dtype=dtype,
            status=status,
            size=size,
            namespace=namespace,
            **kwargs,
        )

    def as_numeric(self, variable):
        return CNumeric(variable)

    def lookup_status(self, status):
        if status.upper().strip() == "OUT":
            status = "INOUT"
        return super().lookup_status(status)

    def check_relevance(self, *variables, hook=None):
        remember = []
        for var in variables:
            if var is None:
                return False
            if isinstance(var, LibRoutineVariable):
                remember.append(var)
                continue
            if abs(var) < ZERO_TOL:
                return False
        if hook is not None:
            for var in remember:
                hook.requires(var)
        return True

    def handle_affine_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        alpha = instruction_dict.get("alpha", 1)
        beta = instruction_dict.get("beta", 0)

        x_var_real = context.namespace.find_assignment(
            type(src0), "real", exception_not_existing=False
        )
        x_var_imag = context.namespace.find_assignment(
            type(src0), "imag", exception_not_existing=False
        )
        y_var_real = context.namespace.find_assignment(
            type(tgt0), "real", exception_not_existing=False
        )
        y_var_imag = context.namespace.find_assignment(
            type(tgt0), "imag", exception_not_existing=False
        )

        x_var_offs = src0.offsets
        y_var_offs = tgt0.offsets
        a_real = self.wrap_lrv(alpha.real)
        a_imag = self.wrap_lrv(alpha.imag)
        b_real = self.wrap_lrv(beta.real)
        b_imag = self.wrap_lrv(beta.imag)

        combinations = [
            (y_var_real, a_real, x_var_real, b_real, 1),
            (y_var_real, a_imag, x_var_imag, b_real, -1),
            (y_var_imag, a_real, x_var_imag, b_imag, 1),
            (y_var_imag, a_imag, x_var_real, b_imag, 1),
        ]
        hook = HookContainer(context=context)
        first_real = True
        first_imag = True
        for y_var, a_val, x_var, b_val, sign in combinations:
            if y_var is y_var_real and not first_real:
                b_val = self.wrap_lrv(0.0)
            if y_var is y_var_imag and not first_imag:
                b_val = self.wrap_lrv(0.0)
            ret = self.check_relevance(y_var, a_val, x_var, b_val, hook=hook)
            if ret:
                yield CAffineContainer(
                    y_var.at(*y_var_offs),
                    a_val * sign,
                    x_var.at(*x_var_offs),
                    b_val,
                    context=context,
                )
                if y_var is y_var_real:
                    first_real = False
                else:
                    first_imag = False

        yield CodeLine("", context=context)

    def handle_bilinear_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        src1 = instruction_dict.get("src1")
        alpha = instruction_dict.get("alpha")

        u_var_real = context.namespace.find_assignment(
            type(src0), "real", exception_not_existing=False
        )
        u_var_imag = context.namespace.find_assignment(
            type(src0), "imag", exception_not_existing=False
        )
        v_var_real = context.namespace.find_assignment(
            type(src1), "real", exception_not_existing=False
        )
        v_var_imag = context.namespace.find_assignment(
            type(src1), "imag", exception_not_existing=False
        )
        y_var_real = context.namespace.find_assignment(
            type(tgt0), "real", exception_not_existing=False
        )
        y_var_imag = context.namespace.find_assignment(
            type(tgt0), "imag", exception_not_existing=False
        )

        u_var_offs = src0.offsets
        v_var_offs = src1.offsets
        y_var_offs = tgt0.offsets
        a_real = self.wrap_lrv(alpha.real)
        a_imag = self.wrap_lrv(alpha.imag)

        include_all = False

        hook = HookContainer(context=context)

        ret = self.check_relevance(
            y_var_real, a_real, u_var_real, v_var_real, hook=hook
        )
        if ret or include_all:
            yield CBilinearContainer(
                y_var_real.at(*y_var_offs),
                a_real,
                u_var_real.at(*u_var_offs),
                v_var_real.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_real, a_real, u_var_imag, v_var_imag, hook=hook
        )
        if ret or include_all:
            yield CBilinearContainer(
                y_var_real.at(*y_var_offs),
                -a_real,
                u_var_imag.at(*u_var_offs),
                v_var_imag.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_real, a_imag, u_var_imag, v_var_real, hook=hook
        )
        if ret or include_all:
            yield CBilinearContainer(
                y_var_real.at(*y_var_offs),
                -a_imag,
                u_var_imag.at(*u_var_offs),
                v_var_real.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_real, a_imag, u_var_real, v_var_imag, hook=hook
        )
        if ret or include_all:
            yield CBilinearContainer(
                y_var_real.at(*y_var_offs),
                -a_imag,
                u_var_real.at(*u_var_offs),
                v_var_imag.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_imag, a_real, u_var_imag, v_var_real, hook=hook
        )
        if ret or include_all:
            yield CBilinearContainer(
                y_var_imag.at(*y_var_offs),
                a_real,
                u_var_imag.at(*u_var_offs),
                v_var_real.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_imag, a_real, u_var_real, v_var_imag, hook=hook
        )
        if ret or include_all:
            yield CBilinearContainer(
                y_var_imag.at(*y_var_offs),
                a_real,
                u_var_real.at(*u_var_offs),
                v_var_imag.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_imag, a_imag, u_var_real, v_var_real, hook=hook
        )
        if ret or include_all:
            yield CBilinearContainer(
                y_var_imag.at(*y_var_offs),
                a_imag,
                u_var_real.at(*u_var_offs),
                v_var_real.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_imag, a_imag, u_var_imag, v_var_imag, hook=hook
        )
        if ret or include_all:
            yield CBilinearContainer(
                y_var_imag.at(*y_var_offs),
                -a_imag,
                u_var_imag.at(*u_var_offs),
                v_var_imag.at(*v_var_offs),
                context=context,
            )
        yield CodeLine("", context=context)

    def create_external_array(self, *args, context, **kwargs):
        return Builder.create_external_array(
            self,
            *args,
            context=context,
            local_class=CLocalVariable,
            constant_class=CConstant,
        )


class CComputeResource(ComputeResource):
    """Compute resource for C code generation."""

    DEFAULT_LOCAL_VARIABLE_CLASS = CLocalVariable

    def create_mfe_container(
        self,
        *,
        context,
        local_variable_capture,
        name=None,
        loop_container=None,
        loop_capture=None,
    ) -> None | MultiFrameExpandContainer:
        del name, loop_container, loop_capture
        return CMultiFrameExpandContainer(
            context=context,
            local_variable_capture=local_variable_capture,
        )

    def create_combine_container(
        self,
        first,
        second,
        *,
        context,
        local_variable_capture,
        name=None,
        loop_container=None,
        loop_capture=None,
    ) -> None | MultiFrameExpandContainer:
        del name, loop_container, loop_capture
        return CIntCombineExpandContainer(
            first,
            second,
            context=context,
            local_variable_capture=local_variable_capture,
        )


class CLibRoutine(LibRoutine):
    """C LibRoutine variant."""


class CLibrary(Library):
    """C source and header emission."""

    BACKEND_IDENTIFIER = "c"
    FILEENDING = "c"
    INDENTSTR = "    "
    LIBROUTINE_CLASS = CLibRoutine
    IMPORTLINE_CLASS = CImportContainer
    DEFAULT_BUILDER = CBuilder
    DEFAULT_CONTAINER_CLASS = CRoutineContainer

    def __init__(
        self,
        plain_name,
        build_hash=None,
        resource=None,
        configuration=None,
        general_configuration=None,
    ):
        if resource is None:
            resource = CComputeResource("CResource")
        self._initialize_library_state(
            plain_name=plain_name,
            build_hash=build_hash,
            resource=resource,
            import_section_class=CImportSectionContainer,
            backend_configuration=configuration,
            general_configuration=general_configuration,
        )
        self._meta["header_name"] = self.headername

    @property
    def headername(self):
        return self._get_headername()

    def _get_headername(self):
        return f"{self.libname}.h"

    @property
    def objectname(self):
        return self._get_objectname()

    def _get_objectname(self):
        return f"{self.libname}.o"

    @property
    def sharedlibname(self):
        return self._get_sharedlibname()

    def _get_sharedlibname(self):
        return f"lib{self.libname}.so"

    @property
    def header_guard(self):
        return self._get_header_guard()

    def _get_header_guard(self):
        return f"PHOENIX_{self.libname.upper()}_H"

    def write_all_files(self):
        self.write_code()
        self.write_header()
        self.write_docs()
        self.write_manifest()
        return True

    def write_header(self):
        self.ensure_output_dir()
        self.write_basepath_file(self.headername, lines=self.get_header_lines())

    def get_output_files(self):
        yield from super().get_output_files()
        yield self.headername

    def get_compilation_output_files(self):
        yield self.objectname
        yield self.sharedlibname

    def get_header_lines(self):
        yield f"#ifndef {self.header_guard}"
        yield f"#define {self.header_guard}"
        yield ""
        yield "#include <stdint.h>"
        yield ""
        yield "#ifdef __cplusplus"
        yield 'extern "C" {'
        yield "#endif"
        yield ""
        for _name, libroutine in self.content:
            yield self.get_libroutine_signature(
                libroutine, terminate=True
            )
        yield ""
        yield "#ifdef __cplusplus"
        yield "}"
        yield "#endif"
        yield ""
        yield f"#endif  /* {self.header_guard} */"

    def get_libroutine_signature(self, libroutine, *, terminate=False):
        """Render a C signature for a generated or raw-code routine."""
        if libroutine.container is not None:
            return libroutine.container.get_signature(terminate=terminate)
        call_args = [
            variable.as_argument_declaration()
            for variable in libroutine.get_arguments()
        ]
        args_string = "void" if not call_args else ", ".join(call_args)
        suffix = ";" if terminate else ""
        return f"void {libroutine.name}({args_string}){suffix}"

    def get_to_zero_support_routine(self, dtype):
        """Return the external helper routine used to reset one buffer."""
        routine_name = f"phoenix_to_zero_{dtype}"
        existing = self[routine_name]
        if existing is not None:
            return existing
        zero_value = CLocalVariable(name="tmp", dtype=dtype, no_entry=True).get_zero_value()
        ctype = CLocalVariable.DTYPE_LOOKUP[dtype]
        code = [
            f"void {routine_name}({ctype} *buffer, int32_t size)",
            "{",
            "    for (int32_t idx = 0; idx < size; ++idx) {",
            f"        buffer[idx] = {zero_value};",
            "    }",
            "}",
        ]
        return self._register_manual_routine(
            routine_name,
            code=code,
            arguments=[
                {
                    "name": "buffer",
                    "dtype": dtype,
                    "size": 1,
                    "status": "INOUT",
                    "assignment": ("buffer", "data"),
                },
                {
                    "name": "size",
                    "dtype": "i32",
                    "status": "IN",
                },
            ],
        )

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(f'#include "{self.libname}.h"')
        support_header = self.backend_configuration.get_nested(
            "support", "header_name", default=None
        )
        if support_header:
            yield from self.codelines_from_text(f'#include "{support_header}"')

    def generate_foot_containers(self, **_):
        return
        yield

    def generate_prmb_containers(self, **_):
        imports = list(self.import_capture.list_imports())
        if imports:
            yield from self.codelines_from_text("")
            for library, routines in imports:
                yield CImportContainer(library, routines, context=self.context)

        constants = list(self.definition_capture.captured)
        if constants:
            yield from self.codelines_from_text("")
            for variable in constants:
                for line in variable.get_definition_lines():
                    yield from self.codelines_from_text(line)

        if not self.backend_configuration.get_nested(
            "support", "header_name", default=None
        ):
            yield from self.codelines_from_text("")
            for dtype, ctype, zero_value in (
                ("f64", "double", "0.0"),
                ("f32", "float", "0.0f"),
                ("i64", "int64_t", "0"),
                ("i32", "int32_t", "0"),
            ):
                yield from self.codelines_from_text(
                    f"static inline void phoenix_zero_{dtype}({ctype} *buffer, int32_t size) {{"
                )
                yield from self.codelines_from_text(
                    "    for (int32_t idx = 0; idx < size; ++idx) {"
                )
                yield from self.codelines_from_text(
                    f"        buffer[idx] = {zero_value};"
                )
                yield from self.codelines_from_text("    }")
                yield from self.codelines_from_text("}")
                yield from self.codelines_from_text("")

    def generate_clsg_containers(self, **_):
        return
        yield

    def get_header_target(self):
        return MFTHeader(self.relative_to_basepath(self.headername))

    def get_support_target(self):
        support_makefile = self.backend_configuration.get_nested(
            "support", "makefile", default=None
        )
        support_root = self.backend_configuration.get_nested(
            "support", "root", default=None
        )
        build_target = self.backend_configuration.get_nested(
            "support", "build_target", default=None
        )
        support_library = self.backend_configuration.get_nested(
            "support", "library_file", default=None
        )
        if not support_makefile or not support_root or not build_target:
            return None
        required = [support_library] if support_library else []
        return BackendSupportBuildTarget(
            f"support_{self.libname}_{type(self).BACKEND_IDENTIFIER}",
            support_root=support_root,
            makefile=support_makefile,
            build_target=build_target,
            required_files=required,
        )

    def get_object_target(self):
        dependencies = [*self.get_makefile_compile_dependency_targets()]
        return CMFTObject(
            self.relative_to_basepath(self.objectname),
            source=self.get_codefile_target(),
            dependencies=[self.get_header_target(), *dependencies],
            configuration=self.backend_configuration,
        )

    def get_library_target(self):
        dependencies = [
            self.get_object_target(),
            *self.get_makefile_dependency_targets(),
        ]
        support_target = self.get_support_target()
        if support_target is not None:
            dependencies.append(support_target)
        return CMFTSharedLibrary(
            self.relative_to_basepath(self.sharedlibname),
            dependencies=dependencies,
            configuration=self.backend_configuration,
        )

    def get_makefile_targets(self):
        yield self.get_codefile_target()
        yield self.get_header_target()
        yield self.get_object_target()
        yield self.get_library_target()


CBuilder.set_instruction_class_handler(
    AffineOperationInstruction, CBuilder.handle_affine_instruction
)
CBuilder.set_instruction_class_handler(
    BiLinearOperationInstruction, CBuilder.handle_bilinear_instruction
)

CRoutineContainer.set_comment_class(CCommentLine)

CBuilder.set_comment_class(CCommentLine)
CBuilder.set_routinecall_class(CRoutineCallContainer)
register_c_atomic_handlers(CBuilder)
