"""
#autogenerated#header#do#not#modify############################################
#
# File:        c_pywrapper_library.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   13/03/2026
# Last Update: 16/03/2026, 11:46
# Version:     0.1.1
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """ctypes-based Python wrappers for generated C libraries."""

import ctypes
from os import PathLike
from pathlib import Path

import numpy as np

from ...libroutinevar import (
    LibRoutineInputVariable,
    LibRoutineOutputVariable,
    LibRoutineInOutVariable,
)
from ..pywrapper_library import (
    PyWrapperLibraryBase,
    WrapperBase,
    _RequestValue,
)


class CWrapper(WrapperBase):
    """Adapt wrapper arguments to a plain C ABI."""

    NP_DTYPE_LOOKUP = {
        "f64": np.float64,
        "f32": np.float32,
        "i64": np.int64,
        "i32": np.int32,
    }

    C_DTYPE_LOOKUP = {
        "f64": ctypes.c_double,
        "f32": ctypes.c_float,
        "i64": ctypes.c_int64,
        "i32": ctypes.c_int32,
    }

    def adapt_call_arguments(self, all_args):
        converted = []
        keepalive = []
        for value, spec in zip(all_args, self.argument_specs):
            arg_type, variable, _name, _key, _adaa = spec
            call_arg, refs = self.convert_argument(
                value=value,
                variable=variable,
                arg_type=arg_type,
            )
            converted.append(call_arg)
            keepalive.extend(refs)
        return tuple(converted), keepalive

    def convert_argument(self, *, value, variable, arg_type):
        del arg_type
        if isinstance(value, _RequestValue):
            value = value.value

        np_dtype = type(self).NP_DTYPE_LOOKUP[variable.dtype]
        c_dtype = type(self).C_DTYPE_LOOKUP[variable.dtype]

        if variable.is_scalar:
            return self.convert_scalar_argument(
                value=value,
                variable=variable,
                np_dtype=np_dtype,
                c_dtype=c_dtype,
            )
        return self.convert_array_argument(
            value=value,
            variable=variable,
            np_dtype=np_dtype,
        )

    def convert_scalar_argument(self, *, value, variable, np_dtype, c_dtype):
        if isinstance(value, c_dtype):
            return value, [value]

        if isinstance(variable, LibRoutineInputVariable):
            if isinstance(value, np.ndarray):
                return (
                    c_dtype(np.asarray(value, dtype=np_dtype).reshape(-1)[0]),
                    [],
                )
            if hasattr(value, "item"):
                value = value.item()
            return c_dtype(value), []

        if hasattr(value, "contents"):
            return value, [value]

        if isinstance(value, np.ndarray):
            array = np.asarray(value, dtype=np_dtype)
            if array.size != 1:
                raise ValueError(
                    f"Scalar C argument {variable.name} expects exactly one value."
                )
            if not array.flags["C_CONTIGUOUS"]:
                raise ValueError(
                    f"Scalar storage for {variable.name} must be C-contiguous."
                )
            ptr = array.ctypes.data_as(ctypes.POINTER(c_dtype))
            return ptr, [array, ptr]

        holder = c_dtype(value.item() if hasattr(value, "item") else value)
        ptr = ctypes.pointer(holder)
        return ptr, [holder, ptr]

    def convert_array_argument(self, *, value, variable, np_dtype):
        if isinstance(value, ctypes.Array):
            return value, [value]

        array = np.asarray(value, dtype=np_dtype)
        if array.ndim != 1:
            raise ValueError(
                f"C wrapper expects 1D storage for argument {variable.name}."
            )
        if not array.flags["C_CONTIGUOUS"]:
            if isinstance(variable, LibRoutineInputVariable):
                array = np.ascontiguousarray(array, dtype=np_dtype)
            else:
                raise ValueError(
                    f"Output-capable argument {variable.name} must be C-contiguous."
                )
        c_dtype = type(self).C_DTYPE_LOOKUP[variable.dtype]
        ptr = array.ctypes.data_as(ctypes.POINTER(c_dtype))
        return ptr, [array, ptr]


class CPyWrapperLibrary(PyWrapperLibraryBase):
    """Python wrapper library for plain C libraries via `ctypes`."""

    WRAPPER_CLASS = CWrapper

    NP_DTYPE_LOOKUP = CWrapper.NP_DTYPE_LOOKUP
    C_DTYPE_LOOKUP = CWrapper.C_DTYPE_LOOKUP

    def __init__(self, wrapped_library, wrapper_lib=None, build_hash=None):
        wrapper_lib = self._prepare_wrapper_lib(wrapped_library, wrapper_lib)
        super().__init__(
            wrapped_library,
            wrapper_lib=wrapper_lib,
            build_hash=build_hash,
        )

    @classmethod
    def from_compiled_hash(
        cls,
        library_class,
        plain_name,
        build_hash,
        *,
        wrapper_lib=None,
        **library_kwargs,
    ):
        if wrapper_lib is None:
            preview_library = library_class(
                plain_name,
                build_hash=build_hash,
                **library_kwargs,
            )
            wrapper_lib = preview_library.sharedlibname
        return super().from_compiled_hash(
            library_class,
            plain_name,
            build_hash,
            wrapper_lib=wrapper_lib,
            **library_kwargs,
        )

    def _prepare_wrapper_lib(self, wrapped_library, wrapper_lib):
        if wrapper_lib is None:
            return None
        if isinstance(wrapper_lib, (str, PathLike)):
            wrapper_path = Path(wrapper_lib)
            if not wrapper_path.is_absolute():
                wrapper_lib = wrapped_library.relative_to_basepath(wrapper_lib)
            return ctypes.CDLL(str(wrapper_lib))
        return wrapper_lib

    def resolve_wrapper_callable(self, libroutine_name, libroutine):
        if self.wrapper_lib is None:
            raise ValueError("wrapper_lib must be set for C wrapper libraries")
        routine = getattr(self.wrapper_lib, libroutine_name)
        self.configure_routine_signature(routine, libroutine)
        return routine

    def configure_routine_signature(self, routine, libroutine):
        routine.restype = None
        routine.argtypes = [
            self.create_ctypes_argtype(arg)
            for arg in libroutine.get_arguments()
        ]

    def create_ctypes_argtype(self, arg):
        c_dtype = type(self).C_DTYPE_LOOKUP[arg.dtype]

        if arg.is_scalar:
            if isinstance(arg, LibRoutineInputVariable):
                return c_dtype
            if isinstance(
                arg, (LibRoutineOutputVariable, LibRoutineInOutVariable)
            ):
                return ctypes.POINTER(c_dtype)

        return ctypes.POINTER(c_dtype)
