"""
#autogenerated#header#do#not#modify############################################
#
# File:        dtype.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 27/03/2026, 11:31
# Version:     0.0.2079
#
#################################################end#of#autoheader#do#not#modify


"""

# pylint: disable=too-many-arguments


from __future__ import annotations

__doc__ = """

The ADAA class holds data references to HPC backends and unpacks accordingly
for function calls.

Basic arithemtic operations are implemented via a mapping into a basic
linop(A, b, C) -> A + b * C operation

DContainer combines multiple Layers to a combined datatype and can be extended
to manage inter-layer data conversion, host-device sync and consistency checks.

So far, no arithmetic operation is implemented on this level, intentionally,
as, depending on the interpretation of levels, such an implementation might be
factually wrong.

"""


from typing import Type, Any
import numpy as np

from .aux import configured_zero_tol
from .coeffbackend import CoeffBackend
from .keymap import KeyMap


ZERO_TOL = configured_zero_tol()


class GenericADAA:
    """
    ADAA is an acronym for Aligned Data Access Array.
    This data type is intended for the systematic distribution of data into
    multiple aligned arrays. An example for this distribution are arrays
    holding the real and imaginary parts of numbers that were originally
    stored in a complex array. The distribution does not require more memory
    but might allow optimizations based on the active distinction between
    e.g. real and imaginary parts.

    The base class implements just this case and comes along with basic
    arithmetic operations.
    """

    _IDENTIFIER = ""
    _NAME = ""
    _BACKEND: CoeffBackend
    _KEYMAP: KeyMap | None = None
    _FIXED_SIZE = None
    _DATATYPES: dict[str, str] = {}
    _IS_ANCHOR = False
    _ONLY_CACHE: dict[tuple[str, ...], type[GenericADAA]] = {}

    def __init__(self, size: int | None = None, init_zeros=True):
        self._data: dict[str, Any] = {}
        for identifier in self._DATATYPES:
            self._data[identifier] = None
        self._cached: dict[str, np.ndarray | None] = {
            identifier: None for identifier in self._DATATYPES
        }
        self._cached_is_dirty: dict[str, bool] = {
            identifier: True for identifier in self._DATATYPES
        }
        self._size = 0
        self._owns_data = True
        if self._FIXED_SIZE is None and self._KEYMAP is None:
            if not size:
                raise ValueError("Size must be given or fixed.")
        if self._FIXED_SIZE:
            if size is None:
                size = self._FIXED_SIZE
            else:
                if size != self._FIXED_SIZE:
                    raise ValueError(f"Size is fixed ({self._FIXED_SIZE})")
        if self._KEYMAP:
            if size is None:
                size = self._KEYMAP.size
            else:
                if size != self._KEYMAP.size:
                    raise ValueError(f"Size is fixed by keymap {self._KEYMAP}")
        assert size is not None
        self._size = size
        self.initialize()
        if init_zeros:
            self.to_zero()  # should probably be forced anyways.

    @classmethod
    def _set_anchor(cls, value: bool = True) -> None:
        cls._IS_ANCHOR = value

    @property
    def identifier(self) -> str:
        """access write-protected property 'identifier'"""
        return self._IDENTIFIER

    @property
    def size(self) -> int:
        """Access write-protected property 'size'"""
        return self._size

    @property
    def data(self) -> dict[str, Any]:
        """Access to ideally write-protexted property _data"""
        # TODO, sync?
        return self._data

    @classmethod
    def get_fixed_size(cls) -> int:
        """extract the fixed size information, raise Exception if not set"""
        if cls._FIXED_SIZE is None:
            raise ValueError("Fixed size not set!")
        return cls._FIXED_SIZE

    @classmethod
    def datatypes(cls):
        """access the data type pattern"""
        yield from (
            (identifier, thisdtype)
            for identifier, thisdtype in cls._DATATYPES.items()
        )

    def unpack(self):
        """unpack the references and the size"""
        for identifier in self._DATATYPES:
            yield self._data[identifier]
        yield self.size

    def mark_dirty(self, *keys: str):
        """Invalidate cached host-side views for the selected components."""
        selected = keys or tuple(self._DATATYPES)
        for identifier in selected:
            if identifier not in self._cached:
                raise KeyError(f"Unknown cache key {identifier!r}.")
            self._cached[identifier] = None
            self._cached_is_dirty[identifier] = True
        return self

    def reset_cache(self, *keys: str):
        """Drop cached host-side arrays and force a future reload."""
        return self.mark_dirty(*keys)

    def _cache_component(self, identifier: str, array: np.ndarray | None):
        """Store one host-side component array in the local cache."""
        if identifier not in self._cached:
            raise KeyError(f"Unknown cache key {identifier!r}.")
        self._cached[identifier] = None if array is None else np.asarray(array)
        self._cached_is_dirty[identifier] = False

    def _component_to_numpy(self, identifier: str, *, cache: bool = True):
        """Return one component as a NumPy array, optionally using the cache."""
        if identifier not in self._DATATYPES:
            raise KeyError(f"Unknown datatype key {identifier!r}.")
        if cache and not self._cached_is_dirty[identifier]:
            cached = self._cached[identifier]
            if cached is not None:
                return cached
        array = self._BACKEND.coeff_to_numpy(
            self._data[identifier],
            size=self.size,
            dtype=self._DATATYPES[identifier],
        )
        if cache:
            self._cache_component(identifier, array)
            return self._cached[identifier]
        return array

    def to_zero(self):
        """Set the coefficient data to zero."""
        for identifier, thisdtype in self._DATATYPES.items():
            self._BACKEND.coeff_to_zero(
                self._data[identifier],
                size=self.size,
                dtype=thisdtype,
            )
            self._cache_component(identifier, np.zeros(self.size))
        return self

    def copy(self) -> GenericADAA:
        """Creates a real copy of self."""
        copy = self.__class__(self.size)
        for identifier, thisdtype in self._DATATYPES.items():
            if self.data[identifier] is None:
                continue
            self._BACKEND.coeff_copy_data(
                copy.data[identifier],
                self.data[identifier],
                size=self.size,
                dtype=thisdtype,
            )
            if (
                not self._cached_is_dirty[identifier]
                and self._cached[identifier] is not None
            ):
                copy._cache_component(identifier, np.array(self._cached[identifier]))
            else:
                copy.mark_dirty(identifier)
        return copy

    def free_memory(self):
        """free the occupied memory"""
        for identifier, thisdtype in self._DATATYPES.items():
            if not self._owns_data:
                self._data[identifier] = None
                self.mark_dirty(identifier)
                continue
            self._data[identifier] = self._BACKEND.coeff_free(
                self._data[identifier], size=self.size, dtype=thisdtype
            )
            self.mark_dirty(identifier)

    # def _initialize(self, size=None):
    #     """initializeialize the data for a certain size"""
    #     if size is None:
    #         size = self.size
    #     else:
    #         if size == self.size:
    #             return
    #     self.initialize(size)

    def initialize(self):
        """Forced data initialization."""
        self.free_memory()
        self._owns_data = True
        for identifier, thisdtype in self._DATATYPES.items():
            self._data[identifier] = self._BACKEND.coeff_new_array(
                self.size, dtype=thisdtype
            )
            self.mark_dirty(identifier)

    @classmethod
    def find_anchor_class(cls):
        """find the next class in the hierarchy that is an anchor class"""
        if cls._IS_ANCHOR:
            return cls
        try:
            for mro_class in cls.__mro__[1:]:
                if issubclass(mro_class, GenericADAA):
                    return mro_class.find_anchor_class()
            raise AttributeError("No more adaa classes in MRO")
        except AttributeError as exc:
            raise ValueError("No anchor class found.") from exc

    def __init_subclass__(
        cls,
        backend=None,
        identifier=None,
        keymap=None,
        size=None,
        is_anchor=False,
        selected_keys=None,
    ):
        """
        When a new subclass is derived, introduce the class
        variable _IDENTIFIER.

        Anchor classes mark the backend-local public entry points in an ADAA
        family. They are the classes that code should normally import, while
        intermediate restricted variants created through :meth:`only` or
        :meth:`select` remain implementation details layered underneath that
        public anchor.
        """
        cls._IS_ANCHOR = is_anchor
        cls._ONLY_CACHE = {}
        if selected_keys is not None:
            base_datatypes = dict(cls._DATATYPES)
            missing_keys = [
                key for key in selected_keys if key not in base_datatypes
            ]
            if missing_keys:
                raise ValueError(
                    f"Unknown data keys requested: {', '.join(missing_keys)}"
                )
            cls._DATATYPES = {
                key: base_datatypes[key] for key in selected_keys
            }
        if backend is None:
            if cls._IDENTIFIER != "":
                if cls._BACKEND is None:
                    raise ValueError("No backend specified.")
        else:
            cls._BACKEND = backend
        if identifier is not None:
            if cls._IDENTIFIER != "":
                cls._IDENTIFIER = cls._IDENTIFIER + "." + identifier
            else:
                cls._IDENTIFIER = identifier
            cls._NAME = identifier
        if size is not None and keymap is not None:
            raise ValueError("Size and keymap cannot be set simultaneously.")
        if keymap is not None:
            cls._KEYMAP = keymap  # get default
            cls._FIXED_SIZE = keymap.size
        if size is not None:
            if size >= 0:
                cls._FIXED_SIZE = size
            else:
                raise ValueError("Size must be a non-negative integer.")

    @classmethod
    def only(cls, *keys: str) -> Type[GenericADAA]:
        """Derive a view class restricted to the selected data keys."""
        if not keys:
            raise ValueError("At least one data key must be selected.")
        selected_keys = tuple(dict.fromkeys(keys))
        if selected_keys == tuple(cls._DATATYPES):
            return cls
        if selected_keys in cls._ONLY_CACHE:
            return cls._ONLY_CACHE[selected_keys]
        if len(selected_keys) == 1 and selected_keys[0] == "real":
            identifier = "REALARRAY"
        elif len(selected_keys) == 1 and selected_keys[0] == "imag":
            identifier = "IMAGARRAY"
        else:
            identifier = "ONLY[" + ",".join(selected_keys) + "]"
        subset = type(
            cls._IDENTIFIER + f"<{identifier}>",
            (cls,),
            {},
            selected_keys=selected_keys,
            identifier=identifier,
        )
        cls._ONLY_CACHE[selected_keys] = subset
        return subset

    def select(
        self,
        *keys: str,
        copy: bool = True,
        **kwargs: str,
    ) -> GenericADAA:
        """
        Create a restricted ADAA instance selecting or remapping data keys.

        Positional keys request an identity selection. Keyword arguments map
        target keys to source keys on ``self``. With ``copy=False`` the new
        instance shares the backend-owned data references with ``self``.
        """
        if kwargs:
            selected_keys = tuple(dict.fromkeys(keys or tuple(kwargs)))
            mapping = {key: kwargs.get(key, key) for key in selected_keys}
        else:
            selected_keys = tuple(
                dict.fromkeys(keys or tuple(self._DATATYPES))
            )
            mapping = {key: key for key in selected_keys}
        target_cls = self.__class__.only(*selected_keys)
        if (
            not copy
            and target_cls is self.__class__
            and all(mapping[key] == key for key in selected_keys)
        ):
            return self
        target = target_cls(self.size, init_zeros=False)
        if not copy:
            target.free_memory()
            target._owns_data = False
        for target_key, source_key in mapping.items():
            if source_key not in self.data:
                raise ValueError(
                    f"Source key '{source_key}' is not available on {self.__class__.__name__}."
                )
            source_data = self.data[source_key]
            if source_data is None:
                raise ValueError(
                    f"Source key '{source_key}' does not reference backend data."
                )
            if copy:
                self._BACKEND.coeff_copy_data(
                    target.data[target_key],
                    source_data,
                    size=self.size,
                    dtype=target_cls._DATATYPES[target_key],
                )
            else:
                target.data[target_key] = source_data
        return target

    @classmethod
    def allclose(cls, op_a, op_b, rtol: float = 1e-05, atol: float = 1e-8):
        """
        Check whether two ADAA objects are numerically close.

        The comparison is delegated component-wise to the active coefficient
        backend using the provided relative and absolute tolerances.
        """
        if op_a.size != op_b.size:
            raise ValueError("Compared operators must have the same size.")
        for identifier, thisdtype in cls._DATATYPES.items():
            this_all_close = cls._BACKEND.coeff_allclose(
                op_a.data[identifier],
                op_b.data[identifier],
                rtol,
                atol,
                size=op_a.size,
                dtype=thisdtype,
            )
            if not this_all_close:
                return False
        return True

    @classmethod
    def basic_linop(cls, op_r, /, op_a=None, sc_b=None, op_c=None, size=None):
        """evaluates operator_r += operator_a + scalar_b * operator_c"""
        raise NotImplementedError("Must be implemented in subclass")

    @classmethod
    def set_keymap(cls, keymap: KeyMap) -> Type[GenericADAA]:
        """derive a type with given keymap"""
        if cls._FIXED_SIZE:
            raise ValueError("Cannot set keymap when fixed size is given.")
        if cls._KEYMAP is not None:
            raise ValueError(f"KeyMap {cls._KEYMAP} already set.")
        size = keymap.size
        return type(
            cls._IDENTIFIER + f"<{keymap}>",
            (cls,),
            {},
            keymap=keymap,
            identifier=f"KM[{keymap}]",
        )
        keymap.lock()

    @classmethod
    def fix_size(cls, size: int) -> Type[GenericADAA]:
        """derive a fixed size type"""
        if cls._KEYMAP:
            raise ValueError("Cannot fix size directly when keymap is given.")
        if cls._FIXED_SIZE:
            raise ValueError(f"Fixed size {cls._FIXED_SIZE} already set.")

        return type(
            cls._IDENTIFIER + f"[{size}]",
            (cls,),
            {},
            size=size,
            identifier=f"FIXEDSIZE[{size}]",
        )

    @classmethod
    def mul(cls, first, other, target=None, **kwargs):
        """multiplication slot routine"""
        if isinstance(first, GenericADAA) and isinstance(other, GenericADAA):
            raise ValueError("Multiplication of operators is not supported")
        if isinstance(other, GenericADAA):
            return cls.mul(other, first, target=target, **kwargs)

        if target is None:
            target = cls(first.size)

        if isinstance(first, GenericADAA):
            cls.basic_linop(target, op_a=None, sc_b=other, op_c=first)
        return target

    @classmethod
    def div(cls, first, other, target=None, **_kwargs):
        """division slot routine"""
        if isinstance(other, GenericADAA):
            raise ValueError("Division by other operator is not supported")
        if target is None:
            target = cls(first.size)
        cls.basic_linop(target, op_a=None, sc_b=1.0 / other, op_c=first)
        return target

    @classmethod
    def add(cls, first, other, target=None, **_kwargs):
        """addition slot routine"""
        if isinstance(other, GenericADAA):
            assert first.size == other.size
            assert first.identifier == other.identifier
        else:
            raise ValueError("Addition only supports ADAAs")
        if target is None:
            target = cls(first.size)
        cls.basic_linop(target, op_a=first, sc_b=1, op_c=other)
        return target

    @classmethod
    def sub(cls, first, other, target=None, **_kwargs):
        """subtraction slot routine"""
        if isinstance(other, GenericADAA):
            assert first.size == other.size
            assert first.identifier == other.identifier
        else:
            raise ValueError("Subtraction only supports ADAAs")
        if target is None:
            target = cls(first.size)
        cls.basic_linop(target, op_a=first, sc_b=-1, op_c=other)
        return target

    @classmethod
    def neg(cls, first, target=None, **kwargs):
        """negation slot routine"""
        return cls.mul(first, -1, target=target, **kwargs)

    def index(self, *keylike):
        """request the index associated to a certain key"""
        if self._KEYMAP:
            return self._KEYMAP.key2off(*keylike)
        raise ValueError("no keymap assigned")

    def __getitem__(self, keylike):
        return self.to_numpy[self.index(*keylike)]

    ###########################################################################
    #
    # MAGIC
    # =====

    def __add__(self, other):
        return self.__class__.add(self, other)

    def __radd__(self, other):
        return self.__class__.add(other, self)

    def __sub__(self, other):
        return self.__class__.sub(self, other)

    def __rsub__(self, other):
        return self.__class__.sub(other, self)

    def __mul__(self, other):
        return self.__class__.mul(self, other)

    def __rmul__(self, other):
        return self.__class__.mul(other, self)

    def __truediv__(self, other):
        return self.__class__.div(self, other)

    def __rtruediv__(self, other):
        return self.__class__.div(other, self)

    def __div__(self, other):
        return self.__class__.div(self, other)

    def __rdiv__(self, other):
        return self.__class__.div(other, self)

    def __neg__(self):
        return self.__class__.neg(self)

    def __len__(self):
        return self.size

    def __bool__(self):
        return self.size > 0

    def __eq__(self, other):
        return self.__class__.allclose(
            self, other
        )  # , rtol=1e-08, atol=1e-12)

    def __del__(self):
        self.free_memory()

    @classmethod
    def from_numpy(cls, arr: np.ndarray) -> ComplexArrayADAA:
        """Import data from numpy array."""
        raise NotImplementedError("Must be implemented in subclass")

    def to_numpy(self) -> np.ndarray:
        """Export data as numpy array."""
        raise NotImplementedError("Must be implemented in subclass")


###############################################################################


class ComplexArrayADAA(
    GenericADAA, identifier="COMPLEXARRAY", backend=CoeffBackend
):
    """implement a complex array"""

    _DATATYPES: dict[str, str] = {"real": "f64", "imag": "f64"}

    @property
    def real(self):
        """Access protected attribute real."""
        return self._data.get("real")

    @real.setter
    def real(self, arr):
        """Set the data for real part."""
        # self._set_data("real", arr)
        raise ValueError("Real part of the data cannot be set directly.")

    @property
    def imag(self):
        """Access protected attribute imag."""
        return self._data.get("imag")

    @imag.setter
    def imag(self, arr):
        """Set the data for imag part."""
        # self._set_data("imag", arr)
        raise ValueError("Imag part of the data cannot be set directly.")

    @classmethod
    def basic_linop(cls, op_r, /, op_a=None, sc_b=None, op_c=None, size=None):
        """evaluates operator_r += operator_a + scalar_b * operator_c"""
        if op_c is None:
            raise ValueError("op_c must be given.")
        if op_r is None:
            raise ValueError("op_r must be given.")
        if size is not None:
            if size != op_r.size:
                raise ValueError("Invalid size parameter.")
        size = op_r.size
        if sc_b is None:
            sbr, sbi = (1.0, 0.0)
        else:
            sbr, sbi = (complex(sc_b).real, complex(sc_b).imag)
        for identifier, dtype in cls._DATATYPES.items():
            target_part = op_r.data.get(identifier)
            if target_part is None:
                continue
            if identifier == "real":
                arr_x = op_c.data.get("real")
                scal_a = sbr
                arr_y = op_c.data.get("imag")
                scal_b = -1 * sbi
            elif identifier == "imag":
                arr_x = op_c.data.get("real")
                scal_a = sbi
                arr_y = op_c.data.get("imag")
                scal_b = sbr
            else:
                raise ValueError(
                    f"Unsupported datatype identifier '{identifier}'."
                )
            base_part = None if op_a is None else op_a.data.get(identifier)
            cls._BACKEND.coeff_linop(
                target_part,
                scal_a,
                arr_x,
                scal_b,
                arr_y,
                size=size,
                dtype=dtype,
            )
            if base_part is not None:
                cls._BACKEND.coeff_add(
                    target_part,
                    target_part,
                    base_part,
                    size=size,
                    dtype=dtype,
                )
            op_r.mark_dirty(identifier)

    @classmethod
    def from_numpy(cls, arr: np.ndarray) -> ComplexArrayADAA:
        """Import data from numpy array."""
        size = len(arr)
        obj = cls(size)
        array = np.asarray(arr)
        if "real" in cls._DATATYPES:
            real_array = np.asarray(array.real, dtype=np.float64)
            cls._BACKEND.coeff_from_numpy(
                obj.real, real_array, size=size, dtype=cls._DATATYPES["real"]
            )
            obj._cache_component("real", real_array)
        if "imag" in cls._DATATYPES:
            imag_array = np.asarray(array.imag, dtype=np.float64)
            cls._BACKEND.coeff_from_numpy(
                obj.imag, imag_array, size=size, dtype=cls._DATATYPES["imag"]
            )
            obj._cache_component("imag", imag_array)
        return obj

    def to_numpy(self, *, cache: bool = True) -> np.ndarray:
        """Export data as numpy array."""
        real_part = None
        imag_part = None
        if "real" in self._DATATYPES:
            real_part = self._component_to_numpy("real", cache=cache)
        if "imag" in self._DATATYPES:
            imag_part = self._component_to_numpy("imag", cache=cache)
        if real_part is not None and imag_part is not None:
            return real_part + 1j * imag_part
        if real_part is not None:
            return real_part
        if imag_part is not None:
            return 1j * imag_part
        return np.zeros(self.size, dtype=np.float64)


###############################################################################


RealArrayADAA = ComplexArrayADAA.only("real")
RealArrayADAA.__name__ = "RealArrayADAA"
RealArrayADAA.__qualname__ = "RealArrayADAA"
RealArrayADAA.__doc__ = "Complex-array ADAA restricted to the real component."

ImagArrayADAA = ComplexArrayADAA.only("imag")
ImagArrayADAA.__name__ = "ImagArrayADAA"
ImagArrayADAA.__qualname__ = "ImagArrayADAA"
ImagArrayADAA.__doc__ = (
    "Complex-array ADAA restricted to the imaginary component."
)
