"""
#autogenerated#header#do#not#modify############################################
#
# File:        backend_config.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   20/03/2026
# Last Update: 20/03/2026, 18:20
# Version:     0.1.0
#
#################################################end#of#autoheader#do#not#modify
"""

from __future__ import annotations

__doc__ = """
JSON-backed configuration support for Phoenix backends.

The :class:`Configuration` class is a lightweight mutable data container around
the backend-specific JSON files stored next to this module. Each call to
``Configuration.general()`` or ``Configuration.for_backend(...)`` loads a fresh
instance so scripts can modify the returned configuration temporarily without
changing the on-disk defaults unless :meth:`Configuration.save` is called
explicitly.

The configuration files are intended to hold persistent defaults such as:

- compiler and linker executables,
- default and extra compile/link flags,
- runtime tool executables such as ``f2py``, ``mex``, or ``julia``,
- build-folder and log-file naming conventions,
- coarse resource metadata such as target device type or parallel model.
"""

import json
from copy import deepcopy
from pathlib import Path
from typing import Any


def _deep_merge(base: dict, update: dict) -> dict:
    """Return a recursive merge of ``update`` into ``base``."""
    merged = deepcopy(base)
    for key, value in update.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = deepcopy(value)
    return merged


class Configuration:
    """Mutable JSON-backed backend configuration container."""

    BACKENDS_ROOT = Path(__file__).parent / "backends"
    CONFIG_ROOT = BACKENDS_ROOT / "config"

    def __init__(self, name: str, data=None, *, file_path=None):
        self._name = name
        self._data = deepcopy(data or {})
        self._file_path = None if file_path is None else Path(file_path)

    @property
    def name(self) -> str:
        """Return the symbolic configuration name."""
        return self._name

    @property
    def file_path(self) -> Path | None:
        """Return the source path associated with this configuration."""
        return self._file_path

    @classmethod
    def default_file(cls, name: str) -> Path:
        """Return the default JSON file path for ``name``."""
        if name == "general":
            return cls.CONFIG_ROOT / "general.json"
        return cls.backend_root(name) / f"{name}_default.json"

    @classmethod
    def backend_root(cls, name: str) -> Path:
        """Return the package root for one backend."""
        return cls.BACKENDS_ROOT / name

    @classmethod
    def from_file(cls, file_path, *, name=None) -> "Configuration":
        """Load a configuration from a JSON file."""
        path = Path(file_path)
        with open(path, "r") as file:
            data = json.load(file)
        if name is None:
            name = path.stem
        return cls(name=name, data=data, file_path=path)

    @classmethod
    def empty(cls, name: str = "generic") -> "Configuration":
        """Return an empty in-memory configuration."""
        return cls(name=name, data={})

    @classmethod
    def general(cls) -> "Configuration":
        """Load the general default configuration."""
        return cls.from_file(cls.default_file("general"), name="general")

    @classmethod
    def for_backend(cls, backend: str) -> "Configuration":
        """Load the configuration for one backend name."""
        path = cls.default_file(backend)
        if not path.exists():
            return cls.empty(name=backend)
        return cls.from_file(path, name=backend)

    def clone(self) -> "Configuration":
        """Return a detached copy of the configuration."""
        return type(self)(
            self.name,
            data=self._data,
            file_path=self.file_path,
        )

    def to_dict(self) -> dict:
        """Return a deep-copied plain dictionary representation."""
        return deepcopy(self._data)

    @staticmethod
    def split_path(path: str | list[str] | tuple[str, ...]) -> tuple[str, ...]:
        """Normalize a dotted path or key-sequence into tuple form."""
        if isinstance(path, str):
            parts = tuple(part for part in path.split(".") if part)
        else:
            parts = tuple(str(part) for part in path if str(part))
        if not parts:
            raise ValueError("configuration path must not be empty")
        return parts

    def get(self, key, default=None):
        """Return one top-level value."""
        return deepcopy(self._data.get(key, default))

    def set(self, key, value) -> "Configuration":
        """Set one top-level value and return ``self``."""
        self._data[key] = deepcopy(value)
        return self

    def update(self, mapping=None, **kwargs) -> "Configuration":
        """Recursively merge a mapping into the configuration."""
        if mapping is None:
            mapping = {}
        mapping = dict(mapping)
        if kwargs:
            mapping.update(kwargs)
        self._data = _deep_merge(self._data, mapping)
        return self

    def get_nested(self, *keys, default=None):
        """Return a nested value addressed by ``keys``."""
        current = self._data
        for key in keys:
            if not isinstance(current, dict) or key not in current:
                return deepcopy(default)
            current = current[key]
        return deepcopy(current)

    def set_nested(self, *keys, value) -> "Configuration":
        """Set a nested value addressed by ``keys`` and return ``self``."""
        if not keys:
            raise ValueError("at least one key is required")
        current = self._data
        for key in keys[:-1]:
            next_item = current.get(key)
            if not isinstance(next_item, dict):
                next_item = {}
                current[key] = next_item
            current = next_item
        current[keys[-1]] = deepcopy(value)
        return self

    def get_path(self, path: str | list[str] | tuple[str, ...], default: Any = None):
        """Return the value stored at a dotted path."""
        return self.get_nested(*type(self).split_path(path), default=default)

    def set_path(
        self,
        path: str | list[str] | tuple[str, ...],
        value: Any,
    ) -> "Configuration":
        """Set a value addressed by a dotted path."""
        return self.set_nested(*type(self).split_path(path), value=value)

    def has_path(self, path: str | list[str] | tuple[str, ...]) -> bool:
        """Return whether a dotted path exists in the configuration."""
        sentinel = object()
        return self.get_path(path, default=sentinel) is not sentinel

    def iter_paths(self, prefix: tuple[str, ...] = ()):
        """Yield ``(path_tuple, value)`` pairs for all leaf values."""
        yield from self._iter_paths(self._data, prefix=prefix)

    def _iter_paths(self, current: Any, prefix: tuple[str, ...]):
        if isinstance(current, dict):
            for key in sorted(current):
                yield from self._iter_paths(current[key], prefix + (key,))
            return
        yield prefix, deepcopy(current)

    def save(self, file_path=None) -> Path:
        """Write the configuration to disk and return the written path."""
        target = self.file_path if file_path is None else Path(file_path)
        if target is None:
            target = type(self).default_file(self.name)
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "w") as file:
            json.dump(self._data, file, indent=2, sort_keys=True)
            file.write("\n")
        self._file_path = target
        return target
