"""
#autogenerated#header#do#not#modify############################################
#
# File:        buildchain.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   27/03/2026
# Last Update: 27/03/2026, 17:40
# Version:     0.1.0
#
#################################################end#of#autoheader#do#not#modify
"""

from __future__ import annotations

__doc__ = """
Generic build-chain infrastructure around Phoenix builders.

The build chain is intentionally separate from the concrete builder classes:

- optimizers can rewrite instruction trees before lowering,
- validators can reject illegal or backend-incompatible instruction layouts,
- builders remain focused on instruction-to-container lowering.

This module therefore contains the generic orchestration pieces that were
previously bundled into :mod:`phoenix.fgen.builder`.
"""

from dataclasses import dataclass
from typing import Any, Dict, Iterator, List

from .checksum import stable_normalize
from .instruction import (
    Instruction,
    InstructionGroup,
    LeafInstruction,
    MapApplyInstruction,
    ParametricInstructionGroup,
)
from ..toolbox.logger import GLOBAL_LOGGER as log
from ..toolbox.logger import info


class BuilderSegment:
    """Common base class for components participating in the build pipeline."""

    _CLSNAME_PREFIX = "_SEGMENT_"
    _IDENTIFIER = "_GENERIC_"
    _VERSN = 0
    _BUILD = 0

    def __init__(self, **params: Any):
        self._params: Dict[str, Any] = params
        self._welcome_log()

    def _welcome_log(self) -> None:
        info(*self._welcome_log_lines())

    def _welcome_log_lines(self) -> Iterator[str]:
        version, build = type(self)._VERSN, type(self)._BUILD
        yield (
            f"Hello from {type(self)._CLSNAME_PREFIX} "
            + f"'{type(self)._IDENTIFIER}'"
            + f" (v{version}.{build})"
        )
        yield from self._detail_log_lines()

    def _detail_log_lines(self) -> Iterator[str]:
        if self._params:
            yield f"parameters ({len(self._params)}):"
            for param, value in self._params.items():
                yield f"  - {param}={value}"
        else:
            yield "[no parameters given]"

    @property
    def identifier(self):
        return type(self)._IDENTIFIER

    def checksum_payload(self):
        return {
            "class": f"{type(self).__module__}.{type(self).__qualname__}",
            "identifier": type(self)._IDENTIFIER,
            "version": type(self)._VERSN,
            "build": type(self)._BUILD,
            "params": stable_normalize(self._params),
        }

    @classmethod
    def __init_subclass__(
        cls,
        identifier=None,
        version=None,
        build=None,
    ):
        super().__init_subclass__()
        if identifier is None:
            identifier = cls.__name__.upper()
        cls._IDENTIFIER = identifier
        if version is not None:
            cls._VERSN = version
        if build is not None:
            cls._BUILD = build


class Optimizer(BuilderSegment):
    """Optimize the instruction tree with respect to one concern."""

    _CLSNAME_PREFIX = "OPTIMIZER"

    def __str__(self):
        param_string = "|".join(
            [f"{key}={val}" for key, val in self._params.items()]
        )
        return f"<{self._CLSNAME_PREFIX}.{self.identifier}: {param_string}>"

    def __repr__(self):
        return f"<{self._CLSNAME_PREFIX}.{self.identifier}>"

    @log.wrap_call
    def apply(self, instruction: Instruction, **extra_args: Any) -> Instruction:
        raise NotImplementedError(
            "apply method must be implemented in subclass"
        )


class ValidationError(Exception):
    """Exception raised when a validator rejects an instruction tree."""


class Validator(BuilderSegment):
    """Validate instruction trees before lowering."""

    _CLSNAME_PREFIX = "VALIDATOR"

    def validate(
        self, instruction: Instruction, report: dict[str, Any], **extra_args: Any
    ) -> tuple[bool, Any]:
        return True, None

    def handle_fail(
        self, details: Any, report: dict[str, Any], **extra_args: Any
    ) -> ValidationError:
        raise ValidationError(details)


def iter_instruction_nodes(
    instruction: Instruction,
    *,
    parent: Instruction | None = None,
    level: int = 0,
):
    """Yield ``(parent, node, level)`` tuples for a whole instruction tree."""
    yield parent, instruction, level
    for child in getattr(instruction, "instructions", ()):
        if child is instruction or not isinstance(child, Instruction):
            continue
        yield from iter_instruction_nodes(
            child,
            parent=instruction,
            level=level + 1,
        )


@dataclass(frozen=True)
class MapApplySiblingViolation:
    """One illegal group containing multiple sibling map-apply nodes."""

    level: int
    group_type: str
    mapapply_count: int


class SingleMapApplyChainValidator(Validator, identifier="mapapply_single_chain"):
    """Reject groups that contain multiple sibling map-apply instructions."""

    def validate(
        self, instruction: Instruction, report: dict[str, Any], **extra_args: Any
    ) -> tuple[bool, Any]:
        del extra_args
        violations = []
        for _parent, node, level in iter_instruction_nodes(instruction):
            if not isinstance(node, InstructionGroup):
                continue
            mapapply_count = sum(
                1 for child in node.instructions if isinstance(child, MapApplyInstruction)
            )
            if mapapply_count > 1:
                violations.append(
                    MapApplySiblingViolation(
                        level=level,
                        group_type=type(node).__qualname__,
                        mapapply_count=mapapply_count,
                    )
                )
        report["mapapply_single_chain"] = [
            {
                "level": violation.level,
                "group_type": violation.group_type,
                "mapapply_count": violation.mapapply_count,
            }
            for violation in violations
        ]
        if violations:
            return False, violations
        return True, None

    def handle_fail(
        self, details: Any, report: dict[str, Any], **extra_args: Any
    ) -> ValidationError:
        del report, extra_args
        return ValidationError(
            "multiple sibling MapApplyInstruction nodes are not supported; "
            f"violations: {details}"
        )


class AutoParametricGroupOptimizer(
    Optimizer, identifier="auto_parametric_groups"
):
    """Turn long homogeneous leaf groups into ParametricInstructionGroups."""

    def apply(self, instruction: Instruction, **extra_args: Any) -> Instruction:
        threshold = int(self._params.get("threshold", 8))
        del extra_args
        return self._optimize_node(instruction, threshold=threshold)

    def _optimize_node(
        self, instruction: Instruction, *, threshold: int
    ) -> Instruction:
        if isinstance(instruction, ParametricInstructionGroup):
            return instruction
        if isinstance(instruction, InstructionGroup):
            optimized_children = [
                self._optimize_node(child, threshold=threshold)
                for child in instruction.instructions
            ]
            if self._is_parametric_candidate(optimized_children, threshold):
                return ParametricInstructionGroup(optimized_children)
            return type(instruction)(optimized_children, itype=instruction.itype)
        if isinstance(instruction, MapApplyInstruction):
            return type(instruction)(
                self._optimize_node(instruction.content, threshold=threshold),
                environments=list(instruction.environments),
                itype=instruction.itype,
            )
        return instruction

    @staticmethod
    def _is_parametric_candidate(
        children: list[Instruction], threshold: int
    ) -> bool:
        if len(children) < threshold:
            return False
        if not children:
            return False
        first_type = type(children[0])
        if not issubclass(first_type, LeafInstruction):
            return False
        return all(type(child) is first_type for child in children)


class BuildChain:
    """
    Optimization/validation/build pipeline around one concrete builder.
    """

    _class_optimizers: List[Optimizer] = []
    _class_validators: List[Validator] = []

    def __init__(self, builder, optimizers=None, validators=None):
        self._optimizers = []
        self._validators = []
        self._builder = builder
        for optimizer in optimizers or []:
            self.include_optimizer(optimizer)
        for validator in validators or []:
            self.include_validator(validator)

    @property
    def builder(self):
        return self._builder

    @property
    def optimizers(self):
        yield from self._optimizers

    @property
    def validators(self):
        yield from self._validators

    @staticmethod
    def _normalize_instructions(instructions):
        if isinstance(instructions, Instruction):
            return (instructions,)
        return tuple(instructions)

    @log.wrap_call
    def include_optimizer(self, optimizer: Optimizer) -> None:
        if not isinstance(optimizer, Optimizer):
            raise TypeError("Optimizer must be an instance of Optimizer")
        self._optimizers.append(optimizer)

    @log.wrap_call
    def include_validator(self, validator: Validator) -> None:
        if not isinstance(validator, Validator):
            raise TypeError("validator must be an instance of Validator")
        self._validators.append(validator)

    @log.wrap_call
    def perform_optimization(
        self, instruction: Instruction, **extra_args: Any
    ) -> Instruction:
        info(
            f"starting optimization for {instruction.class_identifier()}",
            source=type(self).__name__,
        )
        for num, optimizer in enumerate(self._optimizers):
            info(
                f"apply optimizer #{num + 1}: {type(optimizer).__qualname__}",
                source=type(self).__name__,
            )
            instruction = optimizer.apply(instruction, **extra_args)
        for num, optimizer in enumerate(type(self)._class_optimizers):
            info(
                f"apply class optimizer #{num + 1}: {type(optimizer).__qualname__}",
                source=type(self).__name__,
            )
            instruction = optimizer.apply(instruction, **extra_args)
        info(
            f"finished optimization for {instruction.class_identifier()}",
            source=type(self).__name__,
        )
        return instruction

    @log.wrap_call
    def perform_validation(
        self, instruction: Instruction, **extra_args: Any
    ) -> tuple[bool, dict[str, Any]]:
        report = {}
        info(
            f"starting validation for {instruction.class_identifier()}",
            source=type(self).__name__,
        )

        for num, validator in enumerate(self._validators):
            info(
                f"apply validator #{num + 1}: {type(validator).__qualname__}",
                source=type(self).__name__,
            )
            passed, details = validator.validate(
                instruction, report, **extra_args
            )
            if not passed:
                raise validator.handle_fail(details, report, **extra_args)

        for num, validator in enumerate(type(self)._class_validators):
            info(
                f"apply class validator #{num + 1}: {type(validator).__qualname__}",
                source=type(self).__name__,
            )
            passed, details = validator.validate(
                instruction, report, **extra_args
            )
            if not passed:
                raise validator.handle_fail(details, report, **extra_args)

        info(
            f"finished validation for {instruction.class_identifier()}",
            source=type(self).__name__,
        )
        return True, report

    @log.wrap_call
    def perform_build(
        self, name, instructions, context, **extra_args: Any
    ):
        info(
            f"starting build stage for routine {name}",
            source=type(self).__name__,
        )
        return self._builder.create_routine_container(
            name, instructions, context, **extra_args
        )

    @log.wrap_call
    def optimize(self, instructions, **extra_args: Any):
        instructions = self._normalize_instructions(instructions)
        return tuple(
            self.perform_optimization(instruction, **extra_args)
            for instruction in instructions
        )

    @log.wrap_call
    def validate(self, instructions, **extra_args: Any):
        instructions = self._normalize_instructions(instructions)
        reports = []
        for instruction in instructions:
            _passed, report = self.perform_validation(instruction, **extra_args)
            reports.append(report)
        if len(reports) == 1:
            return reports[0]
        return {"instructions": reports}

    @log.wrap_call
    def build(self, name, instructions, context, **extra_args: Any):
        instructions = self._normalize_instructions(instructions)
        return self.perform_build(
            name, instructions, context=context, **extra_args
        )

    @log.wrap_call
    def build_to_library(
        self,
        library,
        name,
        instructions,
        **extra_args: Any,
    ):
        instructions = self._normalize_instructions(instructions)
        info(
            f"attach routine {name} to library {library.libname}",
            source=type(self).__name__,
        )
        return library.libroutine_from_instructions(
            name,
            *instructions,
            builder=self.builder,
            **extra_args,
        )

    @log.wrap_call
    def run(self, name, instructions, context, **extra_args: Any):
        optimized = self.optimize(instructions, **extra_args)
        self.validate(optimized, **extra_args)
        return self.build(
            name,
            optimized,
            context=context,
            **extra_args,
        )

    @log.wrap_call
    def prepare_instructions(
        self, instructions: Instruction, buildargs: dict[str, Any]
    ):
        info("build code from instruction tree")
        optimized_tree = instructions.deepcopy()
        info("start with root instruction node")
        del buildargs
        return optimized_tree


__all__ = [
    "AutoParametricGroupOptimizer",
    "BuildChain",
    "BuilderSegment",
    "Optimizer",
    "SingleMapApplyChainValidator",
    "ValidationError",
    "Validator",
    "iter_instruction_nodes",
]
