"""
#autogenerated#header#do#not#modify############################################
#
# File:        expression.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   03/03/2026
# Last Update: 23/03/2026, 13:23
# Version:     0.1.12
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """Minimal symbolic expression tree used for generated index arithmetic."""

from dataclasses import dataclass
from typing import Any


class Expression:
    """Base node for symbolic expressions."""

    _string_renderer = None

    def __init__(self, **kwargs):
        self._parameters = kwargs

    def __str__(self):
        return self.render_to_string()

    def __repr__(self):
        return self.render_to_string()

    def render_to_string(self):
        """render an expression using the default string renderer"""
        return self.render(renderer=type(self)._string_renderer)

    def render(self, *, renderer=None):
        """render an expression with a certain renderer"""
        if renderer is None:
            raise TypeError("renderer must be given!")
        return renderer.render(self)


@dataclass
class Constant(Expression):
    """Literal constant expression."""

    value: Any


@dataclass
class Variable(Expression):
    """Expression referencing an external variable-like object."""

    variable: Any


@dataclass
class Arithmetic(Expression):
    """Binary arithmetic expression with an operator tag."""

    first: Expression
    second: Expression
    operand: str


@dataclass
class Negative(Expression):
    """Unary negation expression."""

    inner: Expression


class Add(Arithmetic):
    """Addition expression."""

    def __init__(self, first, second):
        super().__init__(first=first, second=second, operand="add")


class Sub(Arithmetic):
    """Subtraction expression."""

    def __init__(self, first, second):
        super().__init__(first=first, second=second, operand="sub")


class Mul(Arithmetic):
    """Multiplication expression."""

    def __init__(self, first, second):
        super().__init__(first=first, second=second, operand="mul")


class Div(Arithmetic):
    """Division expression."""

    def __init__(self, first, second):
        super().__init__(first=first, second=second, operand="div")


class Pow(Arithmetic):
    """Exponentiation expression."""

    def __init__(self, first, second):
        super().__init__(first=first, second=second, operand="pow")


##############################


class ExpressionRenderer:
    """Base renderer turning expression trees into backend-specific text."""

    def __init__(self):
        pass

    def render(self, expression):
        if isinstance(expression, Constant):
            return self._render_constant(expression)
        if isinstance(expression, Variable):
            return self._render_variable(expression)
        if isinstance(expression, Arithmetic):
            return self._render_arithmetic(expression)
        if isinstance(expression, Negative):
            return self._render_negative(expression)
        raise TypeError("Unsupported expression type")

    def _render_constant(self, expr):
        raise NotImplementedError("must be implemented in subclass")

    def _render_variable(self, expr):
        raise NotImplementedError("must be implemented in subclass")

    def _render_arithmetic(self, expr):
        raise NotImplementedError("must be implemented in subclass")

    def _render_negative(self, expr):
        raise NotImplementedError("must be implemented in subclass")


class StringRenderer(ExpressionRenderer):
    """Default renderer producing Python-like infix string expressions."""

    _operand_lookup = {
        "add": " + ",
        "sub": " - ",
        "mul": " * ",
        "div": " / ",
        "pow": "**",
    }
    _operand_brackets = {
        "add": True,
        "sub": True,
        "mul": False,
        "div": False,
        "pow": False,
    }

    def _render_constant(self, expr):
        return str(expr.value)

    def _render_variable(self, expr):
        return f"{expr.variable}"

    def _render_negative(self, expr):
        return f"(-{expr.inner})"

    def _render_arithmetic(self, expr):
        operand = expr.operand.lower()
        operand_render = type(self)._operand_lookup[operand]
        inner_expr_render = f"{self.render(expr.first)}{operand_render}{self.render(expr.second)}"
        if type(self)._operand_brackets[operand]:
            return f"({inner_expr_render})"
        return f"{inner_expr_render}"


Expression._string_renderer = StringRenderer()
