"""
#autogenerated#header#do#not#modify############################################
#
# File:        instruction3.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/10/2024
# Last Update: 17/03/2026, 10:20
# Version:     0.1.119
#
#################################################end#of#autoheader#do#not#modify
"""


from __future__ import annotations

__doc__ = """
Instruction tree primitives used by the code-generation pipeline.

This module defines the backend-neutral intermediate representation that the
builder layer consumes. Instructions distinguish between two classification
axes:

- ``ftype`` describes the structural role of a node, such as ``group``,
  ``environment``, ``map``, or a concrete leaf operation.
- ``itype`` describes how a node behaves when interpreted on data and is used
  to group compatible instructions, preserve lowering constraints, and validate
  transformations.

The main building blocks are:

- :class:`Instruction`, the common traversal and serialization base class
- :class:`GenericInstruction` and :class:`LeafInstruction`, which store
  parameterized leaf operations
- :class:`InstructionGroup` and :class:`ParametricInstructionGroup`, which
  aggregate compatible instructions
- :class:`ContentInstruction` and its subclasses, which wrap instructions in
  environments, map-apply structures, and variation selectors
- arithmetic leaf instructions such as
  :class:`AffineOperationInstruction` and
  :class:`BiLinearOperationInstruction`

The classes are intentionally independent of any concrete output language. They
encode symbolic variables, scalar parameters, structural control, and
environment application so that Fortran, C, CUDA, Python, and NumPy builders
can lower the same instruction graph in different ways.
"""

from typing import Any, Callable, Dict, Iterable, Iterator, List, Tuple
import weakref

from ..aux import segment_overlap
from .checksum import stable_checksum, stable_normalize
from ..keymap import Key, KeyMap
from .instructionvar import (
    InstructionVariable,
    KeyOffset,
    StringOffset,
    SymbolicOffset,
    InstructionEnvironment,
    InstructionScalar,
)

# class _PartialFormatDict(dict):
#     """allows partial formatting of strings"""

#     def __setitem__(self, key, value):
#         if not isinstance(key, str):
#             raise ValueError("Key must be a string")
#         return super().__setitem__(key, value)

#     def __getitem__(self, key):
#         if key in self:
#             return super().__getitem__(key)
#         return "{" + key + "}"


def _next_recursive(recursive: bool | int) -> bool | int:
    """
    Compute the recursion flag for the next nested walk step.

    :param recursive: Current recursion mode. ``True`` means unlimited
        recursion, ``False`` means a single step only, and integers count the
        remaining recursion depth.
    :returns: The recursion mode that should be forwarded to the next nested
        instruction.
    :raises ValueError: If an integer recursion count is negative.
    :raises TypeError: If ``recursive`` is neither ``bool`` nor ``int``.
    """
    if isinstance(recursive, bool):
        if recursive is True:
            return True
        assert (
            False
        ), "you should not be here. You forgot to implement _interpret_recursive"
    elif isinstance(recursive, int):
        if recursive < 0:
            raise ValueError(
                "Number of recursive executions must be non-negative."
            )
        return recursive - 1
    raise TypeError(
        "The recursive argument must be a boolean or a non-negative integer."
    )


def _interpret_recursive(recursive: bool | int) -> bool | int:
    """
    Normalize a recursion flag into the value used by ``walk`` helpers.

    :param recursive: Requested recursion mode. ``True`` means unlimited
        recursion, ``False`` is normalized to a single recursion step, and an
        integer expresses the remaining explicit recursion depth.
    :returns: The normalized recursion marker.
    :raises ValueError: If an integer recursion count is negative.
    :raises TypeError: If ``recursive`` is neither ``bool`` nor ``int``.
    """
    if isinstance(recursive, bool):
        if recursive is True:
            return True
        # False is treated as a single recursion
        return 1
    elif isinstance(recursive, int):
        if recursive < 0:
            raise ValueError(
                "Number of recursive executions must be non-negative."
            )
        return recursive
    raise TypeError(
        "The recursive argument must be a boolean or a non-negative integer."
    )


###############################################################################
#
#  .oPYo.       .oo  .oPYo.  .oPYo.
#  8   `8      .P 8  8       8.
# o8YooP'     .P  8  `Yooo.  `boo
#  8   `b    oPooo8      `8  .P
#  8    8   .P    8       8  8
#  8oooP'  .P     8  `YooP'  `YooP'
# :......: ..:::::.. :.....: :.....:
# :::::::: ::::::::: ::::::: :::::::
# :::::::: ::::::::: ::::::: :::::::
###############################################################################


class Instruction:
    """Base class for all instruction nodes.

    Instructions form a tree that is later lowered into backend-specific code.
    Each node exposes a functional type via :attr:`ftype` and an implementation
    type via :attr:`itype`, plus traversal helpers used by environments and
    grouped instructions.
    """

    _ftype = "instruction"
    _obj_id_count = 0

    def _get_obj_id(self) -> str:
        """Return the next unique identifier for this concrete subclass."""
        type(self)._obj_id_count += 1
        return f"{self._ftype}#{type(self)._obj_id_count}"

    def _instruction_hash(self, generating: Any) -> int:
        """
        Create the stable hash used by :meth:`checksum`.

        :param generating: Hashable payload that uniquely represents the
            current instruction state.
        :returns: Hash value derived from ``generating``.
        """
        return stable_checksum(generating)

    @staticmethod
    def _get_itype_common_root(instruction_list: List[Instruction]) -> str:
        """
        Derive the longest common ``itype`` prefix shared by a list of
        instructions.

        :param instruction_list: Instructions whose implementation types should
            be compared.
        :returns: The common ``itype`` prefix, or an empty string if the input
            list is empty.
        """
        if len(instruction_list) == 0:
            return ""
        segments_list = [instr.itype.split(".") for instr in instruction_list]
        latest_parent_itype = ".".join(segment_overlap(*segments_list))
        return latest_parent_itype

    def __str__(self):
        return f"<{self.identifier}>"

    def __repr__(self):
        return f"<{self.identifier}>"

    def __len__(self) -> int:
        """
        Return the length of the instruction

        :returns: instruction length
        """
        return 1

    def to_dict(
        self, *keys: str, defaults: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """
        Materialize the instruction as a dictionary.

        :param keys: Optional subset of keys to extract. If omitted, the full
            dictionary contributed by the class hierarchy is returned.
        :param defaults: Optional fallback mapping used when a requested key is
            not present on the instruction.
        :returns: Dictionary representation of the instruction.
        """
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        data_dict = {}  # _PartialFormatDict
        provided = {}
        for cls in reversed(self.__class__.__mro__):
            if hasattr(cls, "contribute_to_dict"):
                provided.update(cls.contribute_to_dict(self))
        if keys:
            data_dict.update(
                {
                    key: provided.get(key, defaults.get(key, None))
                    for key in keys
                }
            )
        else:
            data_dict.update(provided)
        return data_dict

    def __init__(self, *, itype: str | None = None):
        """
        Initialize the common instruction state.

        :param itype: Optional implementation type. Subclasses typically derive
            this from their content if not provided explicitly.
        """
        self._sort_key = None
        self._itype = itype
        self._obj_id = self._get_obj_id()
        self._protected = True

    def __init_subclass__(cls, ftype: str):
        """
        Register the functional type of a concrete instruction subclass.

        :param ftype: Functional type segment to append to the parent class
            ``ftype``.
        """
        ftype = ftype.replace(".", ":")
        cls._obj_id_count = 0
        cls._ftype += f".{ftype}"

    def __enter__(self) -> Instruction:
        """
        Temporarily disable write protection for context-managed mutation.

        :returns: ``self`` so the instruction can be modified inside a
            ``with`` block.
        """
        self._protected = False
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        """
        Re-enable write protection after a context-managed mutation block.

        :param exc_type: Exception type raised inside the context, if any.
        :param exc_val: Exception instance raised inside the context, if any.
        :param exc_tb: Traceback raised inside the context, if any.
        """
        self._protected = True

    def checksum_payload(self) -> int:
        """
        Return the payload used to identify logically identical instructions.

        :returns: Hashable payload representing the generic instruction state.
        """
        return (
            type(self).__module__,
            type(self).__qualname__,
            self._itype,
            self._ftype,
        )

    def checksum(self) -> int:
        """
        Return the hash-based checksum of the instruction.

        :returns: Integer checksum generated from :meth:`checksum_payload`.
        """
        return self._instruction_hash(self.checksum_payload())

    def record_payload(self, *, detailed: bool = False) -> dict[str, Any]:
        """
        Return a JSON-friendly record for manifests and debugging.

        :param detailed: If ``True``, include nested or parameter detail when
            available.
        :returns: Dictionary describing the instruction node.
        """
        return {
            "class": f"{type(self).__module__}.{type(self).__qualname__}",
            "ftype": self.ftype,
            "itype": self.itype,
        }

    @property
    def identifier(self) -> str:
        """
        Return the unique identifier of this instruction instance.

        The identifier is composed from the class ``ftype`` and a monotonically
        increasing per-class counter.

        :returns: Stable instance identifier.
        """
        return self._obj_id

    @property
    def instructions(self) -> Iterator[Instruction]:
        """
        Yield the instruction itself.

        Leaf-like instructions expose themselves as a single-item iterable so
        callers can treat all instruction nodes uniformly.
        """
        yield self

    # pylint: disable=unused-argument
    def unpack(
        self, environment: InstructionEnvironment | None = None
    ) -> Iterator[Instruction]:
        """
        Yield the fully environment-applied leaf instructions below this node.

        :param environment: Optional starting environment. If omitted, an empty
            :class:`InstructionEnvironment` is used.
        :returns: Iterator over leaf instructions after environment fusion.
        """
        if environment is None:
            environment = InstructionEnvironment()
        for _, is_leaf, ref, ref_env in self.walk(
            recursive=True,
            environment=environment,
            include_control=False,
        ):
            assert is_leaf
            yield ref.apply_environment(ref_env)

    def walk(
        self,
        environment: InstructionEnvironment | None = None,
        recursive: bool | int = True,
        include_control: bool = True,
        level: int = 0,
    ):
        """
        Traverse the instruction tree.

        :param environment: Optional starting environment.
        :param recursive: Recursion mode. ``True`` means unlimited recursion,
            ``False`` means one level, and integers specify an explicit depth.
        :param include_control: If ``True``, yield container/control nodes in
            addition to leaf instructions.
        :param level: Current nesting level used while recursing.
        :returns: Iterator yielding ``(level, is_leaf, instruction,
            environment)`` tuples.
        """
        raise NotImplementedError("subclass must implement this method")

    # pylint: enable=unused-argument

    def contribute_to_dict(self) -> Dict[str, Any]:
        """
        Return this class' contribution to :meth:`to_dict`.

        :returns: Dictionary describing the generic instruction state.
        """
        return {
            "identifier": self.identifier,
            "ftype": self.ftype,
            "itype": self.itype,
            "size": len(self),
        }

    @property
    def itype(self):
        """access read-only attribute itype"""
        return self._itype

    @property
    def ftype(self):
        """property for class level ftype attribute"""
        return type(self)._ftype

    @property
    def sort_key(self):
        """access protected sort key attribute"""
        if self._sort_key is None:
            self._sort_key = self._get_sort_key()
        return self._sort_key

    def update_sort_key(self, function: Callable[[Instruction], Any] | None = None) -> None:
        """
        Recompute the cached sort key.

        :param function: Optional sort-key function. If omitted, the class'
            default sort key is used.
        """
        self._sort_key = self._get_sort_key(function=function)

    def _get_default_sort_key(self) -> tuple:
        """Return the default sort key for this instruction."""
        return tuple()

    def _get_sort_key(
        self, function: Callable[[Instruction], Any] | None = None
    ) -> Any:
        """
        Build the sort key used by :attr:`sort_key`.

        :param function: Optional sort-key function. If omitted, the class'
            default implementation is used.
        :returns: Sort key object.
        """
        if function is None:
            return self._get_default_sort_key()
        return function(self)

    def is_subtype(self, itype: str | Instruction) -> bool:
        """
        Check whether this instruction's ``itype`` is compatible with another.

        :param itype: Reference implementation type, either as a string or as
            another instruction.
        :returns: ``True`` if this instruction is equal to or more specific than
            the requested ``itype``.
        """
        if isinstance(itype, Instruction):
            itype = itype.itype
        overlap = segment_overlap(*[self.itype.split("."), itype.split(".")])
        return overlap == itype.split(".")

    def __gt__(self, other):
        return self.itype > other.itype

    def __eq__(self, other):
        return self.itype == other.itype

    def __deepcopy__(self, memo: dict[int, weakref.ReferenceType] | None = None):
        """Implement subclass-specific deep-copy support."""
        raise NotImplementedError("subclasses must implement this method")

    def deepcopy(
        self, memo: dict[int, weakref.ReferenceType] | None = None
    ) -> Instruction:
        """
        Create a deep copy of the instruction tree.

        :param memo: Optional memoization dictionary using weak references to
            preserve shared structure during copying.
        :returns: Deep copy of the instruction.
        """
        if memo is None:
            memo = {}
        # keep the linter happy...
        # pylint: disable=unnecessary-dunder-call
        return self.__deepcopy__(memo=memo)
        # pylint: enable=unnecessary-dunder-call

    def apply_environment(
        self,
        environment: InstructionEnvironment,
        memo: dict | None = None,
    ) -> Instruction:
        """
        Apply an environment to the instruction.

        :param environment: Environment to fuse into the instruction.
        :param memo: Optional memoization dictionary used by subclasses.
        :returns: New instruction with the environment applied.
        """
        raise NotImplementedError("Must be implemented in subclass")

    # def apply_environment(
    #     self,
    #     environment: InstructionEnvironment | None = None,
    #     **kwargs,
    # ) -> Instruction:
    #     """
    #     Apply an environment to the instruction. User call, handles memo and environment initialization.
    #     """
    #     if environment is None:
    #         environment = InstructionEnvironment()
    #     if memo is not None:
    #         if (id(environment), id(self)) in memo:
    #             if (
    #                 memorized := memo[(id(environment), id(self))]()
    #             ) is not None:
    #                 return memorized

    #     env_applied = self.apply_environment(environment, memo=memo)
    #     if memo is not None:
    #         memo[(id(environment), id(self))] = weakref.ref(env_applied)
    #     return env_applied

    def get_instruction_variables(self) -> Iterator[InstructionVariable]:
        """
        Yield the :class:`InstructionVariable` objects referenced by this node.

        Subclasses override this when they store instruction variables directly.
        The base implementation yields no variables.
        """
        return
        yield

    @classmethod
    def class_identifier(cls) -> str:
        """
        Return the functional type identifier of the class.

        :returns: Class-level ``ftype`` string.
        """
        return cls._ftype

    def as_type(self, other_class: type[Instruction]) -> Instruction:
        """
        Rebuild the instruction as another compatible instruction class.

        :param other_class: Target instruction class. ``self`` must already be
            an instance of that class or one of its subclasses.
        :returns: Reconstructed instruction of ``other_class``.
        :raises TypeError: If the conversion is not type-safe.
        """
        if not isinstance(self, other_class):
            raise TypeError(
                f"Cannot convert {self.__class__.__name__} to {other_class.__name__}"
            )
        return other_class.from_dict(self.to_dict())


###############################################################################
#
# .oPYo.  .oPYo.  o    o  .oPYo.   .oPYo.  o  .oPYo.
# 8    8  8.      8b   8  8.       8   `8  8  8    8
# 8       `boo    8`b  8  `boo    o8YooP'  8  8
# 8   oo  .P      8 `b 8  .P       8   `b  8  8
# 8    8  8       8  `b8  8        8    8  8  8    8
# `YooP8  `YooP'  8   `8  `YooP'   8    8  8  `YooP'
# :....8  :.....: ..:::.. :.....: :..:::.. .. :.....:
# :::::8  ::::::: ::::::: ::::::: :::::::: :: :::::::
# :::::.. ::::::: ::::::: ::::::: :::::::: :: :::::::
###############################################################################


class GenericInstruction(Instruction, ftype="generic"):
    """Instruction implementation backed by a free-form parameter mapping.

    Generic instructions are the common storage layer used by leaf
    instructions. Parameters are stored by name and may contain instruction
    variables, scalars, or other backend-neutral metadata.
    """

    # _alias: dict[str, str] = {}

    def __init__(self, itype: str | None = None, **params: Any):
        """
        Initialize a generic instruction.

        :param itype: Optional implementation type. Defaults to the class
            ``ftype`` when omitted.
        :param params: Arbitrary instruction parameters stored verbatim.
        """
        if itype is None:
            itype = self.ftype
        super().__init__(itype=itype)
        # itype of generic instructions is by default the ftype
        self._params = params

    def __gt__(self, other):
        return self.sort_key > other.sort_key

    def __eq__(self, other):
        return self.sort_key == other.sort_key

    def _get_default_sort_key(self):
        return tuple(self.values())

    def keys(self) -> Iterator[str]:
        """Yield the parameter keys stored on the instruction."""
        yield from self._params.keys()

    def items(self) -> Iterator[tuple[str, Any]]:
        """Yield ``(key, value)`` pairs from the parameter mapping."""
        yield from self._params.items()

    def values(self) -> Iterator[Any]:
        """Yield the parameter values stored on the instruction."""
        yield from self._params.values()

    def __getitem__(self, key: str) -> Any:
        """Return a parameter by key."""
        if key in self._params:
            return self._params[key]
        raise KeyError(f"Key '{key}' not found in instruction parameters")
        # return self._from_alias(key)

    def __setitem__(self, key, value):
        self.set(key, value)

    # @classmethod
    # def set_alias(cls, alias, reference):
    #     """add an alias to the class"""
    #     cls._alias[alias] = reference

    def checksum_payload(self):
        """Extend the base checksum payload with the instruction parameters."""
        test_tuple = (
            *super().checksum_payload(),
            tuple(self.params),
        )
        return test_tuple

    def record_payload(self, *, detailed: bool = False) -> dict[str, Any]:
        """Return a record including the stored parameter mapping."""
        payload = super().record_payload(detailed=detailed)
        payload["params"] = stable_normalize(self._params)
        return payload

    @property
    def params(self) -> tuple[Any, ...]:
        """Return the stored parameter values as an immutable tuple."""
        return tuple(self.values())

    def get(self, *in_args: Any) -> Any:
        """
        Return a parameter value with optional default handling.

        :param in_args: ``(key,)`` or ``(key, default)`` exactly, mirroring
            :meth:`dict.get`.
        :returns: Stored value or the provided default.
        :raises KeyError: If the key is missing and no default is provided.
        :raises ValueError: If more than one default is supplied.
        """
        key, *default = in_args
        # if key in type(self)._alias:
        #     return self._from_alias(key)
        if key in self._params:
            return self._params[key]
        if len(default) == 0:
            raise KeyError(f"Key '{key}' not found in instruction parameters")
        if len(default) == 1:
            return default[0]
        raise ValueError(
            "get requires a key and an optional default value to return"
        )

    def set(self, key: str, value: Any) -> None:
        """
        Set a parameter value while honoring write protection.

        :param key: Parameter name to update.
        :param value: New parameter value.
        :raises ValueError: If the instruction is currently write-protected.
        """
        if self._protected:
            raise ValueError(
                f"cannot access protected value of key '{key}' for writing"
            )
        self._params[key] = value

    def contribute_to_dict(self):
        """Return the stored parameter mapping for :meth:`to_dict`."""
        # mapped_alias = {
        #     alias: self._params[target]
        #     for alias, target in type(self)._alias.items()
        # }
        return {**self._params}  # , **mapped_alias}

    def to_tuple(
        self, *keys: str, defaults: dict[str, Any] | None = None
    ) -> tuple[Any, ...]:
        """
        Return selected parameter values as a tuple.

        :param keys: Optional subset of keys. If omitted, all stored parameters
            are returned in iteration order.
        :param defaults: Optional mapping of fallback values for missing keys.
        :returns: Tuple of parameter values.
        """
        if defaults is None:
            defaults = {}
        # check params first, then check defaults, return None for miss
        if keys:
            return tuple(
                self.get(key, defaults.get(key, None)) for key in keys
            )
        return tuple(
            self.get(key, defaults.get(key, None)) for key in self.keys()
        )

    def __deepcopy__(
        self, memo: dict[int, weakref.ReferenceType] | None = None
    ) -> Instruction:
        """Return a deep copy of the generic instruction."""
        if memo is None:
            memo = {}
        if id(self) in memo:
            return memo[id(self)]()  # beware, must be called due to weakref
        copied = type(self).from_dict(self._params)
        memo[id(self)] = weakref.ref(copied)
        return copied

    @classmethod
    def from_dict(cls, params: dict[str, Any]) -> Instruction:
        """
        Reconstruct an instruction instance from a parameter dictionary.

        :param params: Serialized parameter mapping.
        :returns: New instruction instance of ``cls``.
        """
        return cls(**params)

    def walk(
        self,
        environment=None,
        recursive: bool | int = True,
        include_control=True,
        level=0,
    ):
        """
        Yield the generic instruction as a leaf node.

        :param environment: Optional active environment.
        :param recursive: Recursion mode used by the traversal API.
        :param include_control: Included for API compatibility; generic
            instructions are always yielded as leaves.
        :param level: Current traversal depth.
        :returns: Iterator yielding a single leaf tuple.
        """
        recursions = _interpret_recursive(recursive)
        if not recursions:
            return
        if environment is None:
            environment = InstructionEnvironment()
        yield level, True, self, environment

    def apply_environment(
        self,
        environment: InstructionEnvironment,
    ) -> Instruction:
        """
        Apply an instruction environment to all variable-valued parameters.

        :param environment: Environment whose variable mappings should be fused
            into the stored parameters.
        :returns: New instruction with transformed parameters.
        """
        modified_params = {}
        for key, val in self._params.items():
            if isinstance(val, InstructionVariable):
                if val.__class__ in environment:
                    modified_params[key] = environment[val.__class__].fuse(val)
                else:
                    modified_params[key] = val
            else:
                modified_params[key] = val
        return type(self).from_dict(modified_params)


###############################################################################
#
# LEAF INSTRUCTION
# ================


class LeafInstruction(GenericInstruction, ftype="leaf"):
    """
    Represents a Call or and Assignment.
    Leaf Instructions are exclusively defined via the keyword arguments
    listed in _DEFINING_KEYS. Positional args are not allowed.
    """

    _DEFINING_KEYS = []
    # _GENERAL_KEYS = ["inplace_add"]

    def __init__(
        self,
        *args: Any,
        itype: str | None = None,
        **kwargs: Any,
    ):
        """
        Initialize a leaf instruction from keyword-only defining parameters.

        :param args: Positional arguments are rejected to keep leaf
            instructions declarative.
        :param itype: Optional implementation type. Defaults to the class
            ``ftype``.
        :param kwargs: Defining parameter values for the leaf instruction.
        """
        if args:
            raise ValueError(
                "Positional arguments are not allowed in LeafInstruction"
            )
        if itype is None:
            itype = self.ftype
        super().__init__(
            **kwargs,
            itype=itype,
            # inplace_add=inplace_add,
        )

    def __init_subclass__(
        cls, ftype: str, defining_keys: Iterable[str] | None = None
    ):
        """
        Register the leaf subclass and its defining keys.

        :param ftype: Functional type suffix of the subclass.
        :param defining_keys: Keys required to reconstruct the instruction from
            its serialized form.
        """
        if defining_keys is None:
            defining_keys = cls._DEFINING_KEYS
        super().__init_subclass__(ftype=ftype)
        cls._DEFINING_KEYS = list(defining_keys)

    @classmethod
    def from_dict(cls, params: dict[str, Any]) -> Instruction:
        """
        Reconstruct the leaf instruction using its defining keys only.

        :param params: Serialized parameter mapping.
        :returns: New instruction instance of ``cls``.
        """
        return cls(
            **{key: params[key] for key in cls.get_generating_keys()},
        )

    @classmethod
    def get_generating_keys(cls) -> Iterator[str]:
        """
        Yield the keys required to recreate the leaf instruction.

        :returns: Iterator over defining parameter names.
        """
        yield from cls._DEFINING_KEYS
        # yield from cls._GENERAL_KEYS


###############################################################################
#
# .oPYo.   .oPYo.  .oPYo.  o    o   .oPYo.  .oPYo.
# 8    8   8   `8  8    8  8    8   8    8  8
# 8       o8YooP'  8    8  8    8  o8YooP'  `Yooo.
# 8   oo   8   `b  8    8  8    8   8           `8
# 8    8   8    8  8    8  8    8   8            8
# `YooP8   8    8  `YooP'  `YooP'   8       `YooP'
# :....8  :..:::.. :.....: :.....: :..::::: :.....:
# :::::8  :::::::: ::::::: ::::::: :::::::: :::::::
# :::::.. :::::::: ::::::: ::::::: :::::::: :::::::
###############################################################################

###############################################################################
#
# GROUP PARENT CLASS
# ==================

from types import GeneratorType


class InstructionGroup(Instruction, ftype="group"):
    """Ordered collection of child instructions.

    Groups preserve instruction order while exposing convenience helpers for
    sorting, regrouping, flattening, and environment propagation.
    """

    # TODO
    # I consider an allow_parallel keyword, that enables or disables the
    # parallel execution of content.

    # Is it required?
    # Operations that enforce an order should maybe be executed in separate
    # subroutines.

    # Is it transferable?
    # Will an operation, that should be parallelized on a gpu will be properly
    # parallelized on a cpu, where blocks might be better?

    # Is it useful?
    # Most definitely, as we have some say in the later code design.

    # How would I do it?
    # Right now I think of parallelization levels, that can be chosen and even
    # varied in the implementation step. A single operation parallelization
    # could have a higher level, that we only enable on GPUs.

    def __init__(
        self,
        instructions: Iterable[Instruction | list[Instruction] | GeneratorType],
        itype: str | None = None,
    ):
        """
        Initialize a group from instructions or nested iterables.

        :param instructions: Iterable of instructions. Nested lists or
            generators are wrapped into nested :class:`InstructionGroup`
            instances.
        :param itype: Optional explicit implementation type. If omitted, the
            common ``itype`` prefix of the children is used.
        """
        self._instructions = []
        for instr in instructions:
            if isinstance(instr, Instruction):
                self._instructions.append(instr)
            elif isinstance(instr, (list, GeneratorType)):
                self._instructions.append(InstructionGroup(instr))
            else:
                raise TypeError("Unsupported input to InstructionGroup")
        if itype is None:
            itype = InstructionGroup._get_itype_common_root(self._instructions)
        # self._loop_safe = loop_safe
        # self._loop_wrap = loop_wrap
        super().__init__(itype=itype)

    # @property
    # def loop_safe(self):
    #     """check if the group is safe to be wrapped by a loop"""
    #     return self._loop_safe

    # @property
    # def loop_wrap(self):
    #     """check if the group shall be wrapped in a loop capture, which will wrap it in a loop capture"""
    #     return self._loop_wrap

    def __len__(self) -> int:
        """Return the total logical size of all child instructions."""
        return sum(len(instr) for instr in self.instructions)

    def append(self, instruction: Instruction) -> None:
        """
        Append an instruction while preserving the group's ``itype`` contract.

        :param instruction: Instruction to append.
        :raises TypeError: If ``instruction`` is not an :class:`Instruction`.
        :raises ValueError: If the appended instruction is incompatible with the
            group's existing ``itype``.
        """
        if not isinstance(instruction, Instruction):
            raise TypeError("Can only append Instruction instances")
        if not self._instructions:
            self._instructions.append(instruction)
            self._itype = instruction.itype
            return
        if not instruction.is_subtype(self._itype):
            raise ValueError(
                "Appended instruction must match existing group itype"
            )
        self._instructions.append(instruction)

    def __deepcopy__(
        self, memo: dict[int, weakref.ReferenceType] | None = None
    ) -> Instruction:
        """Return a deep copy of the group and all nested instructions."""
        if memo is None:
            memo = {}
        if id(self) in memo:
            return memo[id(self)]()  # beware, must be called due to weakref
        copied_instructions = []
        for instr in self._instructions:
            if id(instr) in memo:
                copied_instr = memo[id(instr)]()
            else:
                copied_instr = instr.deepcopy(memo)
            copied_instructions.append(copied_instr)
        copied_group = type(self)(copied_instructions, itype=self.itype)
        memo[id(self)] = weakref.ref(copied_group)
        return copied_group

    def contribute_to_dict(self) -> dict[str, Any]:
        """Return the group's serialized child list."""
        return {"instructions": self._instructions}

    def record_payload(self, *, detailed: bool = False) -> dict[str, Any]:
        """Return a compact or expanded record for the instruction group."""
        payload = super().record_payload(detailed=detailed)
        payload["count"] = len(self._instructions)
        if detailed:
            payload["instructions"] = [
                instruction.record_payload(detailed=True)
                for instruction in self._instructions
            ]
        else:
            payload["children"] = [
                {
                    "class": f"{type(instruction).__module__}.{type(instruction).__qualname__}",
                    "ftype": instruction.ftype,
                    "itype": instruction.itype,
                }
                for instruction in self._instructions
            ]
        return payload

    @property
    def itype(self):
        return self._itype

    @property
    def instructions(self) -> Iterator[Instruction]:
        """Yield the group's child instructions in order."""
        yield from self._instructions

    def walk(
        self,
        environment=None,
        recursive: bool | int = True,
        include_control=True,
        level=0,
    ):
        """
        Traverse the group and optionally its descendants.

        :param environment: Optional starting environment.
        :param recursive: Recursion mode controlling how deeply children are
            traversed.
        :param include_control: If ``True``, include the group node itself.
        :param level: Current traversal depth.
        :returns: Iterator yielding traversal tuples.
        """
        recursions = _interpret_recursive(recursive)
        if not recursions:
            return
        if environment is None:
            environment = InstructionEnvironment()
        if include_control:
            yield level, False, self, environment
            for instr in self.instructions:
                # iterate level and recursion parameter as control structure itself has been yielded
                yield from instr.walk(
                    environment=environment,
                    recursive=_next_recursive(recursions),
                    include_control=include_control,
                    level=level + 1,
                )
        else:
            for instr in self.instructions:
                yield from instr.walk(
                    environment=environment,
                    recursive=recursions,
                    include_control=include_control,
                    level=level,
                )

    def flatten(self) -> InstructionGroup:
        """
        Return a new group with all nested control structure unpacked.

        :returns: Flattened instruction group built from :meth:`unpack`.
        """
        return type(self)(list(self.unpack()))

    def sorted(
        self,
        ordering_function: Callable[[Instruction], Any] | None = None,
        sort_function: Callable[[Iterable[Any]], list[Any]] | None = None,
    ) -> InstructionGroup:
        """
        Return a sorted copy of the group.

        :param ordering_function: Optional key function. When omitted, the
            child instructions' native ordering is used.
        :param sort_function: Optional sorting function, defaulting to
            :func:`sorted`.
        :returns: New sorted instruction group.
        """
        if sort_function is None:
            sort_function = sorted
        if ordering_function is None:
            return type(self)(
                list(sort_function(self.instructions)), itype=self._itype
            )
        sorted_instructions = sort_function(
            [(ordering_function(instr), instr) for instr in self.instructions]
        )
        return type(self)(
            [instr for _, instr in sorted_instructions], itype=self._itype
        )

    def grouped(
        self,
        function: Callable[[Instruction], Any] | None = None,
        size: int | None = None,
        number: int | None = None,
    ) -> InstructionGroup:
        """
        Partition the group using one grouping strategy.

        :param function: Optional grouping key function.
        :param size: Optional maximum subgroup size.
        :param number: Optional number of output batches.
        :returns: Group containing subgroup instructions.
        :raises ValueError: If more than one grouping mode is requested.
        """

        match (function, size, number):
            case (function, None, None):
                assert callable(function)
                return self.grouped_by_key(function)

            case (None, size, None):
                assert isinstance(size, int)
                return self.grouped_to_size(size)

            case (None, None, number):
                assert isinstance(number, int)
                return self.grouped_to_batches(number)

            case _:
                raise ValueError(
                    "only one of 'function', 'size' and 'number' can be set"
                )

    def grouped_by_key(
        self,
        function: Callable[[Instruction], Any],
        group_type: type[InstructionGroup] | None = None,
        subgroup_type: type[InstructionGroup] | None = None,
    ) -> InstructionGroup:
        """
        Group instructions by a user-provided key.

        :param function: Key function applied to each child instruction.
        :param group_type: Optional outer group class.
        :param subgroup_type: Optional subgroup class.
        :returns: Group of grouped instructions.
        """
        groups: Dict[Any, List[Instruction]] = {}
        for instr in self.instructions:
            group_id = function(instr)
            if group_id not in groups:
                groups[group_id] = []
            groups[group_id].append(instr)
        if group_type is None:
            group_type = type(self)
        if subgroup_type is None:
            subgroup_type = type(self)
        return group_type(
            [
                subgroup_type(group, itype=self._itype)
                for group in groups.values()
            ],
            itype=self._itype,
        )

    def grouped_to_batches(
        self,
        batches: int,
        group_type: type[InstructionGroup] | None = None,
        subgroup_type: type[InstructionGroup] | None = None,
    ) -> InstructionGroup:
        """
        Partition instructions into round-robin batches.

        :param batches: Number of output batches.
        :param group_type: Optional outer group class.
        :param subgroup_type: Optional subgroup class.
        :returns: Group containing the batches.
        """
        groups: List[List[Instruction]] = [[] for _ in range(batches)]
        if group_type is None:
            group_type = type(self)
        if subgroup_type is None:
            subgroup_type = type(self)
        for num, instr in enumerate(self.instructions):
            groups[num % batches].append(instr)
        return group_type(
            [subgroup_type(group) for group in groups], itype=self._itype
        )

    def grouped_to_size(
        self,
        max_size: int,
        group_type: type[InstructionGroup] | None = None,
        subgroup_type: type[InstructionGroup] | None = None,
    ) -> InstructionGroup:
        """
        Partition instructions into consecutive fixed-size groups.

        :param max_size: Maximum number of instructions per subgroup.
        :param group_type: Optional outer group class.
        :param subgroup_type: Optional subgroup class.
        :returns: Group containing the size-limited subgroups.
        """
        group: List[Instruction] = []
        collect: List[List[Instruction]] = []
        if group_type is None:
            group_type = type(self)
        if subgroup_type is None:
            subgroup_type = type(self)
        for instr in self.instructions:
            if len(group) >= max_size:
                collect.append(subgroup_type(group, itype=self._itype))
                group = []
            group.append(instr)
        if group:
            collect.append(subgroup_type(group, itype=self._itype))
        return group_type(collect, itype=self._itype)

    def apply_environment(
        self, environment: InstructionEnvironment
    ) -> Instruction:
        """
        Apply one environment to every child instruction.

        :param environment: Environment to fuse into the entire group.
        :returns: New group whose children have the environment applied.
        """
        return type(self)(
            [
                instr.apply_environment(environment)
                for instr in self.instructions
            ],
            itype=self.itype,
        )


class ParametricInstructionGroup(InstructionGroup, ftype="pgroup"):
    """
    Within this group, all instructions must be of the same type.
    So far I will not allow any internal groups, only leaf instructions.
    """

    def __init__(
        self,
        instructions: Iterable[Instruction],
        generating_instruction_class: type[LeafInstruction] | None = None,
    ):
        """
        Initialize a group whose children all share one leaf instruction type.

        :param instructions: Leaf instructions to normalize into one class.
        :param generating_instruction_class: Explicit leaf class to use for all
            children. When omitted, the first instruction determines the class.
        """
        if generating_instruction_class is None:
            for instruction in instructions:
                if generating_instruction_class is None:
                    generating_instruction_class = type(instruction)
                if not isinstance(instruction, generating_instruction_class):
                    raise TypeError(
                        "ParametricGroup can only contain instructions of the same type,"
                        + " or type must be given as argument"
                    )
        if not issubclass(generating_instruction_class, LeafInstruction):
            raise TypeError(
                "generating instruction class must be a leaf class"
            )
        super().__init__(
            [
                instruction.as_type(generating_instruction_class)
                for instruction in instructions
            ],
            itype=generating_instruction_class._ftype,
        )
        self._gen_instr_class = generating_instruction_class

    def generate_instruction(self, *args: Any, **kwargs: Any) -> LeafInstruction:
        """
        Create a new instruction using the group's generating class.

        :param args: Positional arguments forwarded to the generating class.
        :param kwargs: Keyword arguments forwarded to the generating class.
        :returns: Newly constructed leaf instruction.
        """
        return self._gen_instr_class(*args, **kwargs)

    def get_generating_keys(self) -> Iterator[str]:
        """Yield the defining keys of the generating instruction class."""
        yield from self._gen_instr_class.get_generating_keys()

    def iterate_parameters(self) -> Iterator[dict[str, Any]]:
        """
        Yield serialized parameter dictionaries for all child instructions.

        :returns: Iterator over per-instruction parameter mappings.
        """
        for instruction in self.instructions:
            yield instruction.to_dict(*self.get_generating_keys())

    def grouped_by_key(self, function, subgroup_type=None):
        return super().grouped_by_key(
            function, group_type=InstructionGroup, subgroup_type=subgroup_type
        )

    def grouped_to_batches(self, batches, subgroup_type=None):
        return super().grouped_to_batches(
            batches, group_type=InstructionGroup, subgroup_type=subgroup_type
        )

    def grouped_to_size(self, max_size, subgroup_type=None):
        return super().grouped_to_size(
            max_size, group_type=InstructionGroup, subgroup_type=subgroup_type
        )


######################################################################################
#
# .oPYo.                   o                    o   .oPYo.
# 8    8                   8                    8   8.
# 8       .oPYo.  odYo.   o8P  .oPYo.  odYo.   o8P  `boo    odYo.  o    o
# 8       8    8  8' `8    8   8oooo8  8' `8    8   .P      8' `8  Y.  .P
# 8    8  8    8  8   8    8   8.      8   8    8   8       8   8  `b..d'
# `YooP'  `YooP'  8   8    8   `Yooo'  8   8    8   `YooP'  8   8   `YP'
# :.....: :.....: ..::.. ::..: :.....: ..::.. ::..: :.....: ..::.. ::...::
# ::::::: ::::::: :::::: ::::: ::::::: :::::: ::::: ::::::: :::::: :::::::
# ::::::: ::::::: :::::: ::::: ::::::: :::::: ::::: ::::::: :::::: :::::::
######################################################################################

###############################################################################
#
# CONTENT INSTRUCTION PARENT CLASS
# ================================


class ContentInstruction(Instruction, ftype="content"):
    """Instruction wrapper that owns exactly one nested instruction."""

    def __init__(self, content: Instruction, itype: str | None = None):
        """
        Initialize a content-bearing instruction.

        :param content: Nested instruction wrapped by this node.
        :param itype: Optional explicit implementation type. Defaults to the
            nested instruction's ``itype``.
        """
        if itype is None:
            itype = content.itype
        super().__init__(itype=itype)
        if not isinstance(content, Instruction):
            raise TypeError(
                "content of environment must be of type instruction"
            )
        self._content = content

    def contribute_to_dict(self) -> dict[str, Any]:
        """Return the wrapped content for serialization."""
        return {"content": self._content}

    def __len__(self) -> int:
        """Return the logical size of the wrapped instruction."""
        return len(self._content)

    @property
    def instructions(self) -> Iterator[Instruction]:
        """Yield the wrapped instruction."""
        yield self._content

    @property
    def content(self) -> Instruction:
        """Return the wrapped instruction."""
        return self._content

    def __deepcopy__(
        self, memo: dict[int, weakref.ReferenceType] | None = None, **kwargs: Any
    ) -> Instruction:
        """Return a deep copy of the wrapper and its nested content."""
        if memo is None:
            memo = {}
        copied_content = self.content.deepcopy(memo=memo, **kwargs)
        return type(self)(
            copied_content,
            itype=self.itype,
            **kwargs,
        )

    def walk(
        self,
        environment=None,
        recursive: bool | int = True,
        include_control=True,
        level=0,
    ):
        """
        Traverse the wrapped content.

        :param environment: Optional starting environment.
        :param recursive: Recursion mode controlling nested traversal depth.
        :param include_control: If ``True``, include the wrapper itself before
            traversing the nested instruction.
        :param level: Current traversal depth.
        :returns: Iterator yielding traversal tuples.
        """
        # an environment does not count as recursive step!!
        recursions = _interpret_recursive(recursive)
        if not recursions:
            return
        if environment is None:
            environment = InstructionEnvironment()
        if include_control:
            yield level, False, self, environment
            for instr in self.instructions:
                # iterate level and recursion parameter, as control structure itself has been yielded
                yield from instr.walk(
                    environment=environment,
                    recursive=_next_recursive(recursions),
                    include_control=include_control,
                    level=level + 1,
                )
        else:
            for instr in self.instructions:
                yield from instr.walk(
                    environment=environment,
                    recursive=recursions,
                    include_control=include_control,
                    level=level,
                )

    def apply_environment(
        self, environment: InstructionEnvironment, **kwargs
    ) -> Instruction:
        """
        Apply an environment to the wrapped content and rebuild the wrapper.

        :param environment: Environment to fuse into the nested instruction.
        :param kwargs: Extra constructor arguments forwarded while rebuilding.
        :returns: New wrapper containing the transformed content.
        """
        return type(self)(
            self.content.apply_environment(environment),
            **kwargs,
        )

    def record_payload(self, *, detailed: bool = False) -> dict[str, Any]:
        """Return a compact or expanded record for wrapped content."""
        payload = super().record_payload(detailed=detailed)
        if detailed:
            payload["content"] = self.content.record_payload(detailed=True)
        else:
            payload["content"] = {
                "class": f"{type(self.content).__module__}.{type(self.content).__qualname__}",
                "ftype": self.content.ftype,
                "itype": self.content.itype,
            }
        return payload


# TODO: maybe here is a good place to put a loop capture instruction?

######################################################################################
#
# .oPYo.  o    o  o     o  o   .oPYo.  .oPYo.  o    o  o     o  .oPYo.  o    o  ooooo
# 8.      8b   8  8     8  8   8   `8  8    8  8b   8  8b   d8  8.      8b   8    8
# `boo    8`b  8  8     8  8  o8YooP'  8    8  8`b  8  8`b d'8  `boo    8`b  8    8
# .P      8 `b 8  `b   d'  8   8   `b  8    8  8 `b 8  8 `o' 8  .P      8 `b 8    8
# 8       8  `b8   `b d'   8   8    8  8    8  8  `b8  8     8  8       8  `b8    8
# `YooP'  8   `8    `8'    8   8    8  `YooP'  8   `8  8     8  `YooP'  8   `8    8
# :.....: ..:::.. :::..::: .. :..:::.. :.....: ..:::.. ..::::.. :.....: ..:::.. ::..::
# ::::::: ::::::: :::::::: :: :::::::: ::::::: ::::::: :::::::: ::::::: ::::::: ::::::
# ::::::: ::::::: :::::::: :: :::::::: ::::::: ::::::: :::::::: ::::::: ::::::: ::::::
######################################################################################


###############################################################################
#
# ENVIRONMENT PARENT CLASS
# ========================


class EnvironmentInstruction(ContentInstruction, ftype="environment"):
    """Wrapper that associates a nested instruction with an environment."""

    def __init__(
        self,
        content: Instruction,
        *,
        environment: InstructionEnvironment,
        itype: str | None = None,
    ):
        """
        Initialize an environment wrapper.

        :param content: Nested instruction to execute in the environment.
        :param environment: Environment providing variable substitutions or
            offsets.
        :param itype: Optional explicit implementation type.
        """
        super().__init__(content, itype=itype)
        self._environment = environment

    @property
    def environment(self) -> InstructionEnvironment:
        """Return the environment stored on this wrapper."""
        return self._environment

    def contribute_to_dict(self) -> dict[str, Any]:
        """Return the stored environment for serialization."""
        return {"environment": self.environment}

    def record_payload(self, *, detailed: bool = False) -> dict[str, Any]:
        """Return a record for an environment wrapper."""
        payload = super().record_payload(detailed=detailed)
        if detailed:
            payload["environment"] = stable_normalize(dict(self.environment))
        else:
            payload["environment_size"] = len(self.environment)
        return payload

    def __deepcopy__(
        self, memo: dict[int, weakref.ReferenceType] | None = None, **kwargs: Any
    ) -> Instruction:
        """Return a deep copy of the environment wrapper."""
        if memo is None:
            memo = {}
        return super().__deepcopy__(
            memo=memo,
            environment={
                key: (
                    val.deepcopy(memo=memo)
                    if isinstance(val, Instruction)
                    else val
                )
                for key, val in self.environment.items()
            },
            **kwargs,
        )

    def apply_environment(
        self, environment: InstructionEnvironment, **kwargs
    ) -> Instruction:
        """
        Fuse an outer environment into this wrapper's local environment.

        :param environment: Outer environment to combine with this wrapper.
        :param kwargs: Extra constructor arguments forwarded while rebuilding.
        :returns: Content instruction with the combined environment applied.
        """
        combined_environment = environment.fuse(self.environment)
        return self.content.apply_environment(combined_environment, **kwargs)

    def walk(
        self,
        environment=None,
        recursive: bool | int = True,
        include_control=True,
        level=0,
    ):
        """
        Traverse the wrapped content using the combined active environment.

        :param environment: Optional incoming environment.
        :param recursive: Recursion mode controlling nested traversal depth.
        :param include_control: If ``True``, include the environment node.
        :param level: Current traversal depth.
        :returns: Iterator yielding traversal tuples.
        """

        recursions = _interpret_recursive(recursive)
        if not recursions:
            return
        if environment is None:
            environment = InstructionEnvironment()
        combined_environment = environment.fuse(self.environment)
        if include_control:
            yield level, False, self, environment
            for instr in self.instructions:
                # iterate level and recursion parameter, as control structure itself has been yielded
                yield from instr.walk(
                    environment=combined_environment,
                    recursive=_next_recursive(recursions),
                    include_control=include_control,
                    level=level + 1,
                )
        else:
            for instr in self.instructions:
                yield from instr.walk(
                    environment=combined_environment,
                    recursive=recursions,
                    include_control=include_control,
                    level=level,
                )


###############################################################################
#
# OFFSET ENVIRONMENT
# ==================


class OffsetEnvironmentInstruction(EnvironmentInstruction, ftype="offset"):
    """
    Within this environment, variables are offsetted
    """

    # TODO
    # Unpack (and therefore indirectly flatten) needs to consider offsets!

    # Contains
    # - Instructions to be offsetted

    # requires:
    # - value of offset
    # - variable mapping if names change

    def __init__(
        self,
        content: Instruction,
        *,
        offsets: dict[type[InstructionVariable], InstructionVariable] | None = None,
        itype: str | None = None,
    ):
        """
        Initialize an offset-only environment.

        :param content: Nested instruction to execute with offsets applied.
        :param offsets: Optional mapping from inner variable classes to outer
            variables.
        :param itype: Optional explicit implementation type.
        """
        super().__init__(
            content, environment=InstructionEnvironment(), itype=itype
        )
        if offsets:
            for offset_target, offset_value in offsets.items():
                self.set_offset(offset_target, offset_value)

    def set_offset(
        self,
        inner_class: type[InstructionVariable],
        outer_variable: InstructionVariable,
    ) -> OffsetEnvironmentInstruction:
        """
        Register one variable offset mapping.

        :param inner_class: Instruction-variable class looked up inside the
            nested content.
        :param outer_variable: Variable providing the outer offset.
        :returns: ``self`` for call chaining.
        """
        if not isinstance(outer_variable, InstructionVariable):
            raise TypeError(
                "Outer variable must be of type InstructionVariable"
            )
        self.environment.update(inner_class, outer_variable)
        return self


###############################################################################
#
# .oPYo.                           o          8
# 8                                           8
# `Yooo.  .oPYo.  .oPYo.  .oPYo.  o8  .oPYo.  8
#     `8  8    8  8oooo8  8    '   8  .oooo8  8
#      8  8    8  8.      8    .   8  8    8  8
# `YooP'  8YooP'  `Yooo'  `YooP'   8  `YooP8  8
# :.....: 8 ....: :.....: :.....: :.. :.....: ..
# ::::::: 8 ::::: ::::::: ::::::: ::: ::::::: ::
# ::::::: ..::::: ::::::: ::::::: ::: ::::::: ::
###############################################################################


###############################################################################
#
# MAP APPLY
# =========


class MapApplyInstruction(ContentInstruction, ftype="map"):
    """
    Within this environment, Environment groups (e.g. OffsetGroups) are applied
    to an instructiongroup that is then executed from within every environment.
    """

    def __init__(
        self,
        content: Instruction,
        environments: Iterable[InstructionEnvironment],
        itype: str | None = None,
    ):
        """
        Initialize a map-apply wrapper.

        :param content: Instruction to execute for every supplied environment.
        :param environments: Iterable of environments to apply to ``content``.
        :param itype: Optional explicit implementation type.
        """
        super().__init__(content, itype=itype)
        self._environments = list(environments)

    @property
    def environments(self) -> Iterator[InstructionEnvironment]:
        """Yield the environments applied by the map instruction."""
        yield from self._environments

    def contribute_to_dict(self) -> dict[str, Any]:
        """Return the stored environments for serialization."""
        return {"environments": self._environments}

    def record_payload(self, *, detailed: bool = False) -> dict[str, Any]:
        """Return a compact or expanded record for map-apply content."""
        payload = super().record_payload(detailed=detailed)
        payload["environment_count"] = len(self._environments)
        if detailed:
            payload["environments"] = [
                stable_normalize(dict(environment))
                for environment in self._environments
            ]
        return payload

    def __len__(self) -> int:
        """Return the flattened logical size across all environments."""
        return len(self._content) * len(self._environments)

    def __deepcopy__(
        self, memo: dict[int, weakref.ReferenceType] | None = None, **kwargs: Any
    ) -> Instruction:
        """Return a deep copy of the map instruction and all environments."""
        if memo is None:
            memo = {}
        copied_content = self.content.deepcopy(memo=memo, **kwargs)
        return type(self)(
            copied_content,
            itype=self.itype,
            environments=[
                environment.deepcopy(memo=memo, **kwargs)
                for environment in self.environments
            ],
            **kwargs,
        )

    def walk(
        self,
        environment=None,
        recursive: bool | int = True,
        include_control=True,
        level=0,
    ):
        """
        Traverse the mapped content once for every stored environment.

        :param environment: Optional incoming environment.
        :param recursive: Recursion mode controlling nested traversal depth.
        :param include_control: If ``True``, include the map instruction node.
        :param level: Current traversal depth.
        :returns: Iterator yielding traversal tuples.
        """

        recursions = _interpret_recursive(recursive)
        if not recursions:
            return
        if environment is None:
            environment = InstructionEnvironment()
        if include_control:
            yield level, False, self, environment
            for thisenv in self.environments:
                combined_environment = environment.fuse(thisenv)
                for instr in self.instructions:
                    # iterate level and recursion parameter, as control structure itself has been yielded
                    yield from instr.walk(
                        environment=combined_environment,
                        recursive=_next_recursive(recursions),
                        include_control=include_control,
                        level=level + 1,
                    )
        else:
            for thisenv in self.environments:
                combined_environment = environment.fuse(thisenv)
                for instr in self.instructions:
                    yield from instr.walk(
                        environment=combined_environment,
                        recursive=recursions,
                        include_control=include_control,
                        level=level,
                    )

    def flatten(self) -> InstructionGroup:
        """
        Expand the map instruction into a flat instruction group.

        :returns: Group containing one unpacked content expansion per
            environment.
        """
        return InstructionGroup(
            sum(
                (
                    list(self.content.unpack(environment=env))
                    for env in self.environments
                ),
                start=[],
            ),
        )

        # return InstructionGroup(
        #     [self.content.apply_environment(env) for env in self.environments]
        # )

    def apply_environment(
        self,
        environment: InstructionEnvironment,
        **kwargs,
    ) -> Instruction:
        """
        Apply an outer environment to each stored map environment.

        :param environment: Environment fused into each stored environment.
        :param kwargs: Extra constructor arguments forwarded while rebuilding.
        :returns: Group containing the environment-applied content instances.
        """
        return InstructionGroup(
            [
                self.content.apply_environment(environment.fuse(env), **kwargs)
                for env in self.environments
            ]
        )


###############################################################################
#
# VARIATION
# =========


class VariationInstruction(ContentInstruction, ftype="variation"):
    """
    A variation is a special kind of offset that implies, that data contains copies
    that are addressable via offsets and independent and non-overlapping. E.g. a state
    operator interacts with several different sets of dynamic, but these different
    versions do not interact anywhere, implying some wiggle room for safe parallelization
    """

    def __init__(self, content: Instruction, key: str, itype: str | None = None):
        """
        Initialize a variation selector with one named variant.

        :param content: Initial active variation content.
        :param key: Name of the initial variation.
        :param itype: Optional explicit implementation type.
        """
        super().__init__(content, itype=itype)
        if not isinstance(key, str):
            raise KeyError("Key must be a string")
        self._variations = {key: content}

    def add_variation(self, key: str, variation: Instruction) -> None:
        """
        Register an additional selectable variation.

        :param key: Name of the variation.
        :param variation: Instruction used when the variation is selected.
        """
        if not isinstance(key, str):
            raise KeyError("Key must be a string")
        if not isinstance(variation, Instruction):
            raise TypeError("Variation must be of type instruction")
        self._variations[key] = variation

    def select(self, key: str) -> None:
        """
        Switch the active variation.

        :param key: Name of the variation to activate.
        """
        self._content = self._variations[key]


###############################################################################
#
# .oPYo.   .oPYo.  .oPYo.  .oPYo.  o   ooooo  o  .oPYo.
# 8        8    8  8.      8    8  8   8      8  8    8
# `Yooo.  o8YooP'  `boo    8       8  o8oo    8  8
#     `8   8       .P      8       8   8      8  8
#      8   8       8       8    8  8   8      8  8    8
# `YooP'   8       `YooP'  `YooP'  8   8      8  `YooP'
# :.....: :..::::: :.....: :.....: .. :..:::: .. :.....:
# ::::::: :::::::: ::::::: ::::::: :: ::::::: :: :::::::
# ::::::: :::::::: ::::::: ::::::: :: ::::::: :: :::::::
###############################################################################


class CallInstruction(
    LeafInstruction, ftype="call", defining_keys=["routine", "mapping"]
):
    """
    Leaf instruction representing a library-routine invocation.
    """

    def __init__(
        self,
        routine,
        mapping=None,
    ):
        """
        Initialize a call instruction.

        :param routine: Routine object to invoke when this instruction is
            lowered by a backend.
        :param mapping: Optional remapping dictionary used to translate the
            routine's definition-time instruction-variable assignments to
            assignments available at the call site.
        """
        merged_mapping = {}
        if mapping is not None:
            merged_mapping.update(
                self._normalize_mapping(routine, mapping)
            )
        super().__init__(
            routine=routine,
            mapping=merged_mapping,
            itype=self.ftype,
        )
        self._routine = routine
        self._mapping = merged_mapping

    @property
    def routine(self):
        """Return the routine referenced by the call instruction."""
        return self._routine

    @property
    def mapping(self):
        """Return the call-site assignment remapping."""
        return dict(self._mapping)

    @staticmethod
    def _expand_mapping_key(raw_key, routine):
        """Expand one mapping key to explicit assignment tuples."""
        assignments = [
            argument.assignment
            for argument in routine.get_arguments()
            if argument.assignment is not None
        ]
        if isinstance(raw_key, tuple) and len(raw_key) == 2:
            return [raw_key]
        matches = [
            assignment
            for assignment in assignments
            if assignment[0] == raw_key
        ]
        if matches:
            return matches
        raise TypeError(
            "call mapping keys must be assignment tuples or assignment sources "
            "present in the callee signature"
        )

    @staticmethod
    def _normalize_mapping_value(raw_value, *, key_assignment, allow_expand):
        """Normalize one mapping value to an explicit assignment tuple."""
        if isinstance(raw_value, tuple) and len(raw_value) == 2:
            return raw_value
        if allow_expand:
            return raw_value, key_assignment[1]
        raise TypeError(
            "call mapping values must be assignment tuples when one key maps "
            "to multiple callee assignments"
        )

    @classmethod
    def _normalize_mapping(cls, routine, mapping):
        """Canonicalize mappings to strict ``(source, key) -> (source, key)``."""
        normalized = {}
        for raw_key, raw_value in mapping.items():
            expanded_keys = cls._expand_mapping_key(raw_key, routine)
            for expanded_key in expanded_keys:
                normalized[expanded_key] = cls._normalize_mapping_value(
                    raw_value,
                    key_assignment=expanded_key,
                    allow_expand=not (
                        isinstance(raw_value, tuple) and len(raw_value) == 2
                    ),
                )
        return normalized


class ToZeroInstruction(
    LeafInstruction, ftype="tozero", defining_keys=["target"]
):
    """
    Leaf instruction requesting zero-initialization through a backend routine.
    """

    def __init__(self, target):
        """
        Initialize a reset instruction for a symbolic target variable.

        :param target: Instruction variable whose assigned routine-level
            components should be reset via a backend-provided helper routine.
        """
        if not (
            isinstance(target, InstructionVariable)
            or (
                isinstance(target, type)
                and issubclass(target, InstructionVariable)
            )
        ):
            raise TypeError(
                "ToZeroInstruction target must be an InstructionVariable"
            )
        super().__init__(
            target=target,
            itype=self.ftype,
        )
        self._target = target

    @property
    def target(self):
        """Return the symbolic target that should be zeroed."""
        return self._target


###############################################################################
#
# POLYNOMIAL INSTRUCTION
# ======================


class PolynomialInstruction(
    LeafInstruction,
    ftype="polynomial",
    defining_keys=["tgt0", "src0", "coeffs"],
):
    """Leaf instruction representing a polynomial update."""

    def __init__(
        self,
        tgt0: InstructionVariable,
        src0: InstructionVariable,
        coeffs: Iterable[Any],
        **more_args: Any,
    ):
        """
        Initialize a polynomial update instruction.

        :param tgt0: Target instruction variable.
        :param src0: Source instruction variable whose values are raised to
            increasing powers.
        :param coeffs: Polynomial coefficients ordered by ascending power.
        :param more_args: Additional leaf-instruction parameters.
        """
        assert isinstance(tgt0, InstructionVariable)
        assert isinstance(src0, InstructionVariable)
        super().__init__(
            tgt0=tgt0,
            src0=src0,
            coeffs=[InstructionScalar.convert(coeff) for coeff in coeffs],
            **more_args,
        )


###############################################################################
#
# AFFINE INSTRUCTION
# ==================


class AffineOperationInstruction(
    LeafInstruction,
    ftype="affine",
    defining_keys=["tgt0", "src0", "alpha", "beta"],
):
    """Leaf instruction representing an affine update."""

    def __init__(
        self,
        tgt0: InstructionVariable,
        src0: InstructionVariable,
        alpha: Any,
        beta: Any,
        **more_args: Any,
    ):
        """
        Initialize an affine update instruction.

        :param tgt0: Target instruction variable.
        :param src0: Source instruction variable.
        :param alpha: Multiplicative coefficient applied to ``src0``.
        :param beta: Constant offset added to the affine expression.
        :param more_args: Additional leaf-instruction parameters.
        """
        assert isinstance(tgt0, InstructionVariable)
        assert isinstance(src0, InstructionVariable)
        super().__init__(
            tgt0=tgt0,
            src0=src0,
            alpha=InstructionScalar.convert(alpha),
            beta=InstructionScalar.convert(beta),
            **more_args,
        )


###############################################################################
#
# LINEAR INSTRUCTION
# ==================


class LinearOperationInstruction(
    AffineOperationInstruction,
    ftype="linear",
    defining_keys=["tgt0", "src0", "alpha"],
):
    """Leaf instruction representing a linear update."""

    def __init__(
        self,
        tgt0: InstructionVariable,
        src0: InstructionVariable,
        alpha: Any,
        **more_args: Any,
    ):
        """
        Initialize a linear update instruction.

        :param tgt0: Target instruction variable.
        :param src0: Source instruction variable.
        :param alpha: Multiplicative coefficient applied to ``src0``.
        :param more_args: Additional leaf-instruction parameters.
        """
        assert isinstance(tgt0, InstructionVariable)
        assert isinstance(src0, InstructionVariable)
        super().__init__(
            tgt0=tgt0,
            src0=src0,
            alpha=InstructionScalar.convert(alpha),
            beta=InstructionScalar.convert(0),
            **more_args,
        )


###############################################################################
#
# ADD INSTRUCTION
# ==================


class AccumulateOperationInstruction(
    LinearOperationInstruction,
    ftype="linear",
    defining_keys=["tgt0", "src0"],
):
    """Leaf instruction representing direct accumulation."""

    def __init__(
        self,
        tgt0: InstructionVariable,
        src0: InstructionVariable,
        **more_args: Any,
    ):
        """
        Initialize an accumulation instruction with unit coefficient.

        :param tgt0: Target instruction variable.
        :param src0: Source instruction variable.
        :param more_args: Additional leaf-instruction parameters.
        """
        assert isinstance(tgt0, InstructionVariable)
        assert isinstance(src0, InstructionVariable)
        super().__init__(
            tgt0=tgt0,
            src0=src0,
            alpha=InstructionScalar.convert(1),
            **more_args,
        )


###############################################################################
#
# BILINEAR INSTRUCTION
# ====================


class BiLinearOperationInstruction(
    LeafInstruction,
    ftype="bilinear",
    defining_keys=["tgt0", "src0", "src1", "alpha"],
):
    """Leaf instruction representing a bilinear update."""

    def __init__(
        self,
        tgt0: InstructionVariable,
        src0: InstructionVariable,
        src1: InstructionVariable,
        alpha: Any,
        **more_args: Any,
    ):
        """
        Initialize a bilinear update instruction.

        :param tgt0: Target instruction variable.
        :param src0: First source instruction variable.
        :param src1: Second source instruction variable.
        :param alpha: Multiplicative coefficient applied to the bilinear term.
        :param more_args: Additional leaf-instruction parameters.
        """
        assert isinstance(tgt0, InstructionVariable)
        assert isinstance(src0, InstructionVariable)
        assert isinstance(src1, InstructionVariable)
        super().__init__(
            tgt0=tgt0,
            src0=src0,
            src1=src1,
            alpha=InstructionScalar.convert(alpha),
            **more_args,
        )


###############################################################################
#
# TESTING
# =======

#
#
#
#
#
#
#
if __name__ == "__nothing__":
    import gc
    import weakref

    import psutil
    import os

    def memory_usage():
        process = psutil.Process(os.getpid())
        return process.memory_info().rss / 1024**2  # Convert to MB

    class LeakyClass:
        def __init__(self):
            self.ref = None  # Will hold circular reference
            self.something_big = ["some string"] * 60000000

        def __del__(self):
            # print(f"__del__ called for {self}")
            pass

    for _ in range(4):
        print(f"Memory usage: {memory_usage():.2f} MB")

        # Create objects with cyclic references
        a = LeakyClass()
        b = LeakyClass()

        a.ref = weakref.ref(b)  # Circular reference
        b.ref = weakref.ref(a)  # Circular reference

        a.ref = b  # Circular reference
        b.ref = a  # Circular reference

    print("before del")
    del a  # Delete objects
    print("del 1")
    del b
    print("del 2")

    print("call gc")
    gc.collect()  # Force garbage collection
    print("called")

    print("Garbage objects:", gc.garbage)  # Objects remain in gc.garbage
