"""
#autogenerated#header#do#not#modify############################################
#
# File:        lrvariable.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   04/02/2025
# Last Update: 30/03/2026, 14:30
# Version:     0.1.234
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterator, Self

__doc__ = """
Routine-level variable representations used by the code-generation backends.

This module bridges symbolic instruction-layer objects and concrete code
containers. It provides:

- :class:`Namespace`, which tracks allocated routine variables, temporary names,
  and instruction-variable assignments within nested scopes.
- :class:`LibRoutineVariable` and subclasses, which model routine arguments,
  locals, constants, imports, numeric literals, indexed accesses, and
  multiframe selectors.
- :class:`LibRoutineMultiFrame`, which represents loop- or kernel-driven index
  selectors that can later be expanded by compute resources into loops, thread
  IDs, block IDs, or combined structures.

The objects defined here are still language-neutral. Backends such as Fortran,
C, Python, NumPy, and CUDA specialize them further or wrap them in
backend-specific code containers.
"""

from ..toolbox.logger import GLOBAL_LOGGER as log


class Namespace:
    """Registry for routine variables, assignments, and scoped naming."""

    def __init__(self, parent: Namespace | None = None) -> None:
        # self._content: weakref.WeakValueDictionary[
        #     str, LibRoutineVariable
        # ] = weakref.WeakValueDictionary()
        # if this is weak, the namespace probably cannot remember temp variables that
        # have been set in another branch
        self._content = {}
        self._parent = parent
        self._assigned: Dict[type, Dict[str, LibRoutineVariable]] = {}
        # self._buffer = {}
        self._imports = {}

    def __contains__(self, element: object) -> bool:
        """Return whether a variable name or variable object is present."""
        if isinstance(element, LibRoutineVariable):
            element = element.name
        if element in self._content:
            return True
        if self._parent is not None:
            return self._parent.__contains__(element)
        return False

    def assign(self, ivariable_type, key, lvariable) -> None:
        """Assign an instruction-variable/key pair to a routine variable."""
        if ivariable_type not in self._assigned:
            self._assigned[ivariable_type] = {}
        self._assigned[ivariable_type][key] = lvariable
        log.debug(
            f"Namespace assigned {ivariable_type.get_name()}[{key}] -> {lvariable.name}",
            source=type(self).__name__,
        )

    # def request_buffer(
    #     self, generating, ivariable_type, key, name, dtype, size
    # ):
    # """
    # Request a buffer object. Adapt the size of the buffer object if a larger
    # buffer is required. Once imports are more complicated, I will probably change that.
    # """
    #     if name not in self._buffer:
    #         lrv = generating(
    #             name=name,
    #             dtype=dtype,
    #             size=size,
    #             status=LibRoutineVariable.STATUS_INOUT,
    #             assignment=(ivariable_type, key),
    #             namespace=self,
    #         )
    #         self._buffer[name] = (dtype, size, lrv)
    #         self.assign(ivariable_type, key, lrv)
    #         return lrv

    #     tdtype, tsize, lrv = self._buffer[name]
    #     if tsize < size:
    #         lrv._size = size
    #         self._buffer[name] = (dtype, size, lrv)
    #     return lrv

    def find_import(self, import_obj, import_class=None):
        """
        Return a namespace-local import wrapper.

        :param import_obj: Imported object descriptor.
        :param import_class: Wrapper class used when the import is first seen.
        """
        if import_obj.name in self._imports:
            log.debug(
                f"Reusing import {import_obj.name}",
                source=type(self).__name__,
            )
            return self._imports[import_obj.name]
        if import_class is None:
            raise TypeError("import_class must be provided for new imports")
        external_import = import_class(import_obj)
        self._imports[import_obj.name] = external_import
        log.info(
            f"Registered import {import_obj.name}",
            f"class: {type(external_import).__module__}.{type(external_import).__qualname__}",
            source=type(self).__name__,
        )
        return external_import

    def add(self, variable: LibRoutineVariable) -> None:
        """Register a named non-numeric variable in the namespace."""
        if not isinstance(variable, Numeric):
            self._content[variable.name] = variable
            log.debug(
                f"Namespace registered variable {variable.name}",
                f"type: {type(variable).__module__}.{type(variable).__qualname__}",
                source=type(self).__name__,
            )
            return
        raise TypeError(
            f"Cannot add numeric variable to namespace: {variable}"
        )

    def add_new(self, variable: LibRoutineVariable) -> None:
        """Register a variable and require that its name is unused."""
        if variable.name in self:
            raise ValueError(f"Variable '{variable.name}' already exists")
        self._content[variable.name] = variable
        log.debug(
            f"Namespace registered new variable {variable.name}",
            source=type(self).__name__,
        )

    def remove(self, variable: LibRoutineVariable) -> None:
        """Remove a variable by name from the local namespace node."""
        del self._content[variable.name]

    def get_all_content(self):
        """Yield all variables visible from this namespace node outward."""
        yield from self._content.values()
        if self._parent is not None:
            yield from self._parent.get_all_content()

    @staticmethod
    def combine_name(name, prefix=None, suffix=None) -> str:
        """Combine optional prefix and suffix with a base name."""
        if prefix is not None:
            name = f"{prefix}_{name}"
        if suffix is not None:
            name = f"{name}_{suffix}"
        return name

    @staticmethod
    def wrap_name_combine(func: Callable) -> Callable:
        """Decorator adding ``prefix`` / ``suffix`` support to a method."""

        def wrapper(self, name, *args, prefix=None, suffix=None, **kwargs):
            name = Namespace.combine_name(name, prefix=prefix, suffix=suffix)
            return func(self, name, *args, **kwargs)

        return wrapper

    def autoname(
        self, name, prefix=None, suffix=None, enum_first=False, **_
    ) -> str:
        """Generate a visible unique name in the current namespace chain."""
        cname = self.combine_name(name, prefix=prefix, suffix=suffix)
        num = 0
        if enum_first:
            out = f"{cname}{num}"
        else:
            out = cname
        while self.find(out, exception_existing=False) is not None:
            num += 1
            out = f"{cname}{num}"
        return out

    def find(self, name, exception_existing=True):
        """Resolve a variable name in the current namespace chain."""
        if name in self._content:
            return self._content[name]
        if self._parent is not None:
            return self._parent.find(
                name, exception_existing=exception_existing
            )
        if exception_existing:
            raise KeyError(f"variable {name} not found")
        return None

    def _find_assignment_dict(
        self, ivariable_type, exception_not_existing=True
    ):
        """Resolve the assignment table for a symbolic variable class."""
        if ivariable_type in self._assigned:
            return self._assigned[ivariable_type]
        if self._parent is not None:
            return self._parent._find_assignment_dict(
                ivariable_type, exception_not_existing=exception_not_existing
            )
        if exception_not_existing:
            raise KeyError(
                f"instruction variable {ivariable_type} not assigned."
            )
        return None

    def find_assignment(
        self, ivariable_type, key=None, exception_not_existing=True
    ):
        """
        Resolve one or all previously assigned routine variables.

        When ``key`` is ``None``, the full visible assignment dictionary for the
        symbolic variable class is returned.
        """
        assignment_dict = self._find_assignment_dict(
            ivariable_type, exception_not_existing=exception_not_existing
        )
        if assignment_dict is None:
            if exception_not_existing:
                raise KeyError(
                    f"assignment of instruction variable {ivariable_type} does not provide key {key}."
                )
            return None
        if key is None:
            return dict(assignment_dict)
        if key not in assignment_dict:
            if exception_not_existing:
                raise KeyError(
                    f"assignment of instruction variable {ivariable_type} does not provide key {key}."
                )
            return None
        return assignment_dict[key]

    def get_unique_name(self, name, origin=None) -> str:
        """Generate a stable unique name for a semantic singleton."""
        myhash = ""
        if origin is not None:
            caps = "".join([c for c in type(origin).__name__ if c.isupper()])
            myhash = f"_{caps.lower()}"
        return f"{name}{myhash}"

    def get_temp_name(self, name, origin=None) -> str:
        """Generate a reusable temporary name tied to a builder level."""
        myhash = ""
        level = "_LN"
        if origin is not None:
            caps = "".join([c for c in type(origin).__name__ if c.isupper()])
            myhash = f"_{caps.lower()}" + str(id(self))[-4:]
            level = f"_L{origin.level}"
        name = f"{name}{myhash}{level}"
        return name

    def request_unique(self, generating, name, *args, origin=None, **genargs):
        """Look up or create a stable single-instance variable."""
        processed_name = self.get_unique_name(name, origin)
        temp = self.request_variable(
            generating=generating,
            name=processed_name,
            *args,
            **genargs,
            try_lookup=True,
            enum_first=False,
        )
        return temp

    def request_temp(self, generating, name, *args, origin=None, **genargs):
        """Look up or create a level-scoped reusable temporary."""
        processed_name = self.get_temp_name(name, origin)
        temp = self.request_variable(
            generating=generating,
            name=processed_name,
            *args,
            **genargs,
            try_lookup=True,
            enum_first=False,
        )
        return temp

    def request_variable(
        self,
        generating,
        name,
        *args,
        try_lookup=True,
        **genargs,
    ):
        """Look up or create a variable with the given constructor and name."""
        if try_lookup:
            if name in self:
                variable = self.find(name)
                log.debug(
                    f"Namespace reused variable {variable.name}",
                    source=type(self).__name__,
                )
                return variable
        temp = generating(
            name,
            *args,
            namespace=self,
            **genargs,
        )
        self.add(temp)
        log.info(
            f"Namespace created variable {temp.name}",
            f"type: {type(temp).__module__}.{type(temp).__qualname__}",
            source=type(self).__name__,
        )
        return temp

    def __len__(self) -> int:
        return len(self._content)

    def __str__(self):
        return (
            "{"
            + str(", ".join(var.name for var in self._content.values()))
            + "}"
        )

    def inherit(self) -> Namespace:
        """Create a child namespace inheriting lookup from ``self``."""
        return type(self)(parent=self)

    @property
    def assigned(self):
        """access the assigned variables"""
        yield from self._assigned.items()


class LibRoutineVariable:
    """Base class for variables, constants, imports, and expressions."""

    _VAR_IDENTIFIER = "GENERIC"
    _CLASS_BASE = "var"

    # some public globals to handle status
    STATUS_INPUT = 1
    STATUS_OUTPUT = 2
    STATUS_INOUT = STATUS_INPUT | STATUS_OUTPUT
    STATUS_BUFFER = 4

    _class_namespace = Namespace(None)
    # if this ever becomes a dict, it must be weak!

    def __init__(
        self,
        name=None,
        *,
        size=None,
        dtype="f64",
        status=0,
        prefix=None,
        suffix=None,
        namespace=None,
        enum_first=True,
        no_entry=False,
    ) -> None:
        self._namespace = namespace

        if name is None:
            name = type(self)._CLASS_BASE

        if namespace is None:
            self._namespace = type(self)._class_namespace
        else:
            self._namespace = namespace

        aname = self._namespace.autoname(
            name=name,
            prefix=prefix,
            suffix=suffix,
            enum_first=enum_first,
        )

        assert aname not in self._namespace
        assert aname is not None

        self._name = aname
        self._size = size
        self._dtype = dtype
        self._status = status
        self._dependencies = set()

        if not no_entry:
            self._namespace.add(self)

        self.handle_dependencies()

    @property
    def plain(self) -> LibRoutineVariable:
        """Return the non-indexed variable represented by this object."""
        return self

    def handle_dependencies(self) -> None:
        """Populate dependency metadata after construction."""
        # overwrite in subclass if required

    def use_as_input(self) -> None:
        """Mark the variable as read by a routine."""
        self._status |= type(self).STATUS_INPUT  # set the first bit in status

    def use_as_output(self) -> None:
        """Mark the variable as written by a routine."""
        self._status |= type(
            self
        ).STATUS_OUTPUT  # set the second bit in status

    def release(self) -> None:
        """Release the registered name from the namespace, if any."""
        self._free_name()

    def _free_name(self) -> None:
        """Discard the variable name from its namespace if present."""
        if self._namespace is not None:
            try:
                self._namespace.remove(self)
            except KeyError:
                pass
            except AttributeError as exc:
                # Interpreter shutdown can invalidate namespace attributes.
                return

    def __str__(self):
        # return self.expr()
        if self.is_scalar:
            return f"{self.name}"
        return f"{self.name}[{self.size}]"

    def __repr__(self):
        return self.name

    def __init_subclass__(cls, prefix=None) -> None:
        """Initialize subclass-local naming defaults."""
        if prefix is not None:
            cls._CLASS_BASE = prefix
        cls._class_namespace = Namespace(None)

    def __del__(self):
        self.release()

    def get_sort_group(self) -> int:
        """Return the primary argument-sorting bucket for this variable."""
        status = self.status
        io_status = status & (
            type(self).STATUS_INPUT | type(self).STATUS_OUTPUT
        )
        is_buffer = bool(status & type(self).STATUS_BUFFER)

        if io_status in (
            type(self).STATUS_OUTPUT,
            type(self).STATUS_INOUT,
        ):
            if is_buffer:
                return 1
            return 0
        if io_status == type(self).STATUS_INPUT:
            return 2
        return 3

    def get_sort_key(self) -> tuple[int, str]:
        """Return the stable ordering key used for routine arguments."""
        return self.get_sort_group(), self.name

    def __lt__(self, other):
        if not isinstance(other, LibRoutineVariable):
            return NotImplemented
        return self.get_sort_key() < other.get_sort_key()

    def __gt__(self, other):
        if not isinstance(other, LibRoutineVariable):
            return NotImplemented
        return self.get_sort_key() > other.get_sort_key()

    def get_definition_lines(self):
        """Yield backend-neutral variable definition lines."""
        status = "??"
        if self.status & type(self).STATUS_INOUT == type(self).STATUS_INOUT:
            status = "RW"
        elif self.status & type(self).STATUS_INPUT:
            status = "RO"
        elif self.status & type(self).STATUS_OUTPUT:
            status = "WO"
        if self.size is None:
            yield f":DEFINE: {status} {self.datatype} {self.name}"
        else:
            yield f":DEFINE: {status} {self.datatype} {self.name}[{self.size}]"

    def as_argument(self) -> str:
        """Return the routine-call expression for this variable."""
        return self.name

    def lookup_dtype(self, dtype):
        """Map the internal dtype code to a backend-facing type string."""
        return dtype

    @property
    def name(self):
        """access name attribute"""
        return self._name

    @property
    def is_scalar(self):
        """return boolean deciding whether the variable is a scalar"""
        return self._size is None

    @property
    def size(self):
        """access size attribute"""
        return self._size

    @property
    def dtype(self):
        """access datatype attribute"""
        return self._dtype

    @property
    def datatype(self):
        """access datatype attribute"""
        return self.lookup_dtype(self._dtype)

    @property
    def dependencies(self):
        """Yield routine variables that this variable depends on."""
        yield from self._dependencies

    def depends_on(self, other, recursive=False) -> None:
        """Register that this variable depends on another variable."""
        self._dependencies.add(other)
        if recursive:
            for dep in other.dependencies:
                self._dependencies.add(dep)

    @property
    def status(self):
        """access the status binary set as integer"""
        return self._status

    @property
    def vtype(self):
        """access variable type"""
        return self._VAR_IDENTIFIER

    def at(self, *offsets, simplify=True) -> ValueAt:
        """Return an indexed access expression into this variable."""
        assert not self.is_scalar
        return ValueAt(self, *offsets, simplify=simplify, allow_strings=True)

    def expr(self) -> str:
        """Return the scalar expression representing the whole variable."""
        return f"{self.name}"

    def expr_at(self, offset_string) -> str:
        """Return a backend-neutral indexed access expression."""
        return f"{self.name} [ {offset_string} ]"

    def get_zero_value(self) -> str:
        """Return a backend-neutral zero literal for the variable dtype."""
        if self.dtype.startswith("i"):
            return "0"
        if self.dtype.startswith("f"):
            return "0.0"
        if self.dtype.startswith("c"):
            return "0.0"
        return "0"

    def generate_tozero_lines(self):
        """Yield code lines that explicitly reset this variable to zero."""
        zero_value = self.get_zero_value()
        if self.is_scalar:
            yield f"{self.expr()} = {zero_value}"
            return
        for offset in range(self.size):
            yield f"{self.at(offset).expr()} = {zero_value}"


class UniqueString(LibRoutineVariable):
    """Look at the namespace when you name a routine"""

    _VAR_IDENTIFIER = "UNIQUE"
    _CLASS_BASE = "unq"

    def __init__(self, name, *args, **kwargs):
        super().__init__(
            *args,
            name=name,
            **kwargs,
            enum_first=False,
        )


class ExternalImport(LibRoutineVariable):
    """
    An import. Maybe part of the variable concept in a broader sense.
    When a routine, variable or macro is used that has to be imported,
    it can be provided like that and ultimately requested
    """

    _VAR_IDENTIFIER = "IMPORT"
    _CLASS_BASE = "imp"

    def __init__(self, imported, *args, **kwargs):
        # imported is a library object
        super().__init__(
            *args,
            name=imported.name,
            **kwargs,
            status=LibRoutineVariable.STATUS_INPUT,
            enum_first=False,
        )
        self._imported = imported
        self._call_name = None

    def set_call_name(self, name) -> None:
        """Set the concrete callee name used at call sites."""
        self._call_name = name

    # def get_call_requirements(self):
    #     """yields the requirements used in the call"""

    @property
    def imported(self):
        """read-only access for libroutine"""
        return self._imported

    @property
    def name(self):
        """read-only access for name"""
        return self._name

    @property
    def library(self):
        """read-only access for library"""
        return self._imported.library

    @property
    def call_name(self):
        """access the call name"""
        if self._call_name is None:
            raise ValueError("Call name not set!")
        return self._call_name


class LibRoutineLocalVariable(LibRoutineVariable):
    """Any kind of variable used in the library"""

    _VAR_IDENTIFIER = "LOCAL"
    _CLASS_BASE = "loc"

    def __init__(self, *args, enum_first=False, **kwargs):
        super().__init__(
            *args,
            **kwargs,
            status=LibRoutineVariable.STATUS_INOUT,
            enum_first=enum_first,
        )


class LibRoutineAssignedVariable(LibRoutineVariable):
    """
    Anything that is IO and therefore considered to appear in a routines
    argument list and matchable to an instruction variable.
    """

    _VAR_IDENTIFIER = "ASSIGNED"
    _CLASS_BASE = "asd"

    def __init__(
        self,
        assignment=None,
        status=LibRoutineVariable.STATUS_INOUT,
        **kwargs,
    ):
        super().__init__(status=status, **kwargs)
        # keep a reference to the thing that the variable is assigned to
        self._assignment = assignment

    @property
    def assignment(self):
        """Return the originating instruction-variable assignment tuple."""
        return self._assignment


class LibRoutineInputVariable(LibRoutineAssignedVariable):
    """Input Variable. Potentially includes Read-Only behaviour"""

    _VAR_IDENTIFIER = "INPUT"
    _CLASS_BASE = "inp"

    # in some languages, input variables are treated differently than output.
    # inputs are assumed constant

    def __init__(
        self,
        *,
        name=None,
        assignment=None,
        **kwargs,
    ) -> None:
        if assignment is not None:
            assigned_variable, _ = assignment
        if name is None:
            if assignment is None:
                raise ValueError("Either assignment or name must be provided!")
            name = assigned_variable._name
        super().__init__(
            name=name,
            assignment=assignment,
            status=LibRoutineVariable.STATUS_INPUT,
            enum_first=False,
            **kwargs,
        )


class LibRoutineOutputVariable(LibRoutineAssignedVariable):
    """Output Variable. Potentially includes Auto Initialization"""

    _VAR_IDENTIFIER = "OUTPUT"
    _CLASS_BASE = "out"

    # in some languages, output variables are treated differently than input.
    # outputs are assumed read-write, or inout and not constant

    def __init__(
        self,
        *,
        name=None,
        assignment=None,
        **kwargs,
    ) -> None:
        assigned_variable = None
        if assignment is not None:
            assigned_variable, _ = assignment
        if name is None:
            if assigned_variable is None:
                raise ValueError("Either assignment or name must be provided!")
            name = assigned_variable._name
        super().__init__(
            name=name,
            assignment=assignment,
            status=LibRoutineVariable.STATUS_OUTPUT,
            enum_first=False,
            **kwargs,
        )


class LibRoutineInOutVariable(LibRoutineAssignedVariable):
    """Output Variable. Potentially includes Auto Initialization"""

    _VAR_IDENTIFIER = "INOUT"
    _CLASS_BASE = "ref"

    # in some languages, in/out variables are treated differently than input.
    # outputs are assumed read-write, or inout and not constant

    def __init__(
        self,
        *,
        name=None,
        assignment=None,
        **kwargs,
    ) -> None:
        assigned_variable = None
        if assignment is not None:
            assigned_variable, _ = assignment
        if name is None:
            if assigned_variable is None:
                raise ValueError("Either assignment or name must be provided!")
            name = assigned_variable._name
        super().__init__(
            name=name,
            assignment=assignment,
            status=LibRoutineVariable.STATUS_INOUT,
            enum_first=False,
            **kwargs,
        )


class LibRoutineBufferVariable(LibRoutineInOutVariable):
    """Buffer-backed in/out variable that should be wrapper-allocated."""

    _VAR_IDENTIFIER = "BUFFER"
    _CLASS_BASE = "buf"

    def __init__(
        self,
        *,
        name=None,
        assignment=None,
        **kwargs,
    ) -> None:
        super().__init__(
            name=name,
            assignment=assignment,
            **kwargs,
        )
        self._status |= LibRoutineVariable.STATUS_BUFFER


class LibRoutineConstant(LibRoutineVariable):
    """Literal constant or constant array appearing in generated code."""

    # the idea of a constant is that this representative class also contains the associated values
    # and the constant is initialized somewhere

    # maybe introduce the is_set flag? -> no, instead set constants right within the same header
    # that they are defined in!
    # Also, some ideas of counters transfer, they have to be both initialized and handled in potentially
    # differnt places.

    _VAR_IDENTIFIER = "CONSTANT"
    _CLASS_BASE = "cns"

    def __init__(self, name, value, size=None, **kwargs):
        if size is None:
            if hasattr(value, "__iter__"):
                self._value = value
                size = len(value)
            else:
                self._value = value
        else:
            if not hasattr(value, "__iter__"):
                raise ValueError("value must be iterable.")
            if len(value) != size:
                raise ValueError("value size does not match the given size.")
            self._value = value

        super().__init__(name=name, size=size, **kwargs)

    @property
    def value(self):
        """access value"""
        if self.is_scalar:
            return self._value
        return list(self._value)

    @property
    def values(self):
        """access value"""
        if self.is_scalar:
            raise ValueError(
                "Cannot access multiple values of a scalar variable."
            )
        yield from self._value

    def append(self, value) -> None:
        """Append a value to a constant array."""
        if self.is_scalar:
            raise ValueError("Cannot append to a scalar variable.")
        self._value.append(value)
        self._size = len(self._value)


class Numeric(LibRoutineVariable):
    """
    representation of a numeric value of any form
    """

    DTYPE_LOOKUP = {
        complex: "c128",
        float: "f64",
        int: "i32",
    }

    DTYPE_HIERARCHY = {
        "i32": 1.0,
        "i64": 1.1,
        "f32": 2.0,
        "f64": 2.1,
        "c64": 3.0,
        "f128": 3.1,
    }

    def __init__(self, value, dtype=None, **kwargs) -> None:
        if isinstance(value, Numeric):
            self._value = value.value
            if dtype is None:
                dtype = value.dtype
        elif isinstance(value, LibRoutineVariable):
            raise ValueError(
                "cannot cast value from LibRoutineVariable to Numeric"
            )
        else:
            assert isinstance(
                value, (int, float, complex)
            ), "value must be numeric"
            self._value = value
        if dtype is None:
            dtype = type(self).DTYPE_LOOKUP[type(value)]
        self._is_complex = dtype[0] == "c"
        super().__init__(
            name=f"__NUMERIC_{dtype}_{value}",
            dtype=dtype,
            prefix=None,
            no_entry=True,
            **kwargs,
        )

    def _dtype_combine(self, other) -> str:
        """Return the more general dtype across ``self`` and ``other``."""
        if isinstance(other, Numeric):
            other_dtype = other.dtype
        elif isinstance(other, str):
            other_dtype = other
        else:
            other_dtype = type(self).DTYPE_LOOKUP[type(other)]
        if (
            type(self).DTYPE_HIERARCHY[self.dtype]
            < type(self).DTYPE_HIERARCHY[other_dtype]
        ):
            return other_dtype
        return self.dtype

    def _free_name(self):
        """discard the name in the namespace"""
        # do nothing here. Numerics have no namespace
        return

    def expr(self):
        if self._value < 0:
            return f"({self._value})"
        return f"{self._value}"

    @property
    def value(self):
        """access read-only attribute value"""
        return self._value

    @property
    def real(self):
        """access real value"""
        if self._is_complex:
            return self.value.real
        return self.value

    @property
    def imag(self):
        """access imaginary value"""
        if self._is_complex:
            return self.value.imag
        return None

    def __neg__(self):
        return type(self)(-self.value, dtype=self.dtype)

    def __mul__(self, other):
        if isinstance(other, Numeric):
            return type(self)(
                self.value * other.value, self._dtype_combine(other)
            )
        return type(self)(self.value * other, self._dtype_combine(other))

    def __add__(self, other):
        if isinstance(other, Numeric):
            return type(self)(
                self.value + other.value, self._dtype_combine(other)
            )
        return type(self)(self.value + other, self._dtype_combine(other))

    def __rmul__(self, other):
        return type(self)(other * self.value, self._dtype_combine(other))

    def __radd__(self, other):
        return type(self)(other + self.value, self._dtype_combine(other))

    def __sub__(self, other):
        if isinstance(other, Numeric):
            return type(self)(
                self.value - other.value, self._dtype_combine(other)
            )
        return type(self)(self.value - other, self._dtype_combine(other))

    def __truediv__(self, other):
        if isinstance(other, Numeric):
            return type(self)(
                self.value / other.value, self._dtype_combine(other)
            )
        return type(self)(self.value / other, self._dtype_combine(other))

    def __rsub__(self, other):
        return type(self)(other - self.value, self._dtype_combine(other))

    def __rtruediv__(self, other):
        return type(self)(other / self.value, self._dtype_combine(other))


class ValueAt(LibRoutineVariable):
    """Indexed access expression into another routine variable."""

    def __init__(self, variable, *offsets, simplify=False, **kwargs):
        self._variable = variable
        self._offsets = offsets

        super().__init__(
            name=None,
            size=None,
            namespace=Namespace(),
            dtype=variable.dtype,
            no_entry=True,
        )

        if variable.is_scalar:
            raise ValueError(
                f"Scalar {variable.name} does not provide index access"
            )

        self.simplify = simplify

    @property
    def plain(self):
        """access inner type"""
        return self._variable

    @property
    def name(self):
        return self._variable.name

    @staticmethod
    def process_offsets(
        *offsets,
        simplify=True,
        allow_strings=False,
    ):
        """Normalize integer and symbolic offsets into expression fragments."""
        offset_str_list = []
        offset_int = 0
        for offset in offsets:
            if isinstance(offset, int):
                if simplify:
                    offset_int += offset
                else:
                    offset_str_list.append(str(offset))
            elif isinstance(offset, LibRoutineVariable):
                offset_str_list.append(offset.expr())
            else:
                if allow_strings:
                    offset_str_list.append(str(offset))
                else:
                    raise ValueError(
                        f"offset {offset} is not an integer or LibRoutineVariable"
                    )
        if simplify:
            if offset_int > 0:
                offset_str_list.append(str(offset_int))
        if not offset_str_list:
            offset_str_list = ["0"]
        return offset_str_list

    def handle_dependencies(self) -> None:
        """Record dependencies introduced by symbolic offsets."""
        for offset in self._offsets:
            if isinstance(offset, LibRoutineVariable):
                self.depends_on(offset, recursive=True)

    def expr(self):
        """expression at offset"""

        offset_str_list = self.process_offsets(
            *self._offsets,
            simplify=self.simplify,
        )

        offset_str = " + ".join(offset_str_list)
        return self._variable.expr_at(offset_str)
        # return f"{self.name}[{offset_str}]"

    # def expr(self):
    #     if isinstance(self._offsets, int):
    #         return f"{self._variable.expr()}[{self._offsets}]"
    #     return f"{self._variable.expr()}[{self._offsets.expr()}]"


class LibRoutineMultiFrame(LibRoutineVariable):
    """
    An integer type variable made for iterating through an array or instructions,
    assuming order does not matter!
    """

    _VAR_IDENTIFIER = "MultiFrame"
    _CLASS_BASE = "mfr"

    local_variable_class = LibRoutineLocalVariable
    input_variable_class = LibRoutineInputVariable
    extra_offset = None

    # it can be associated with a range-like source, such as a loop or the grid/block ID on GPUs
    # maybe let it rise like other variables and introduce a "handled" flag that is true once the
    # looping structure has been enabled, which may still require proper initialization.
    # this is the counter object, not the lookup object. Each parallel environment will have
    # exactly one of these.

    def get_sort_group(self) -> int:
        """Place multiframe selectors after ordinary routine arguments."""
        return 99

    def __init__(
        self,
        max_value,
        min_value=0,
    ) -> None:
        super().__init__(
            size=None,
            namespace=None,
            prefix=None,
            status=2,
            dtype="i32",
        )

        # the container that the frame selector is attached to
        self._max_value = max_value
        self._min_value = min_value
        self._local = None

        # default value when branching needs to be suppressed
        self._default_value = min_value

    def recreate(self, namespace=None, key=None):
        """
        Recreate the selector in a new namespace, with caching per assignment.

        :param namespace: Namespace into which the recreated selector should be
            assigned.
        :param key: Optional assignment key used for caching in ``namespace``.
        :returns: Recreated or previously cached multiframe instance.
        """
        if namespace is None:
            # simply recreate.
            return type(self)(self.max_value, min_value=self.min_value)
        # try to find assignment in namespace
        lookup = namespace.find_assignment(
            self, key=key, exception_not_existing=False
        )
        # if not successful, ...
        if lookup is None:
            copy = type(self)(self.max_value, min_value=self.min_value)
            namespace.assign(self, key, copy)
            # create it as above and register it in namespace
            return copy
        # if you are here, then you found it
        return lookup

    def create_local_representative(
        self,
        context=None,
        local_variable_class=None,
        name="loc",
        autorequire=True,
        **kwargs,
    ):
        """
        Create a local representative variable for the selector.

        :param context: Builder context used for namespace allocation.
        :param local_variable_class: Variable class to instantiate.
        :param name: Temporary base name.
        :param autorequire: Whether the created representative should be
            required by the current container immediately.
        """
        if local_variable_class is None:
            local_variable_class = type(self).local_variable_class
        assert local_variable_class is not None
        if context is None:
            raise ValueError("No context provided")
        self._local = context.namespace.request_temp(
            local_variable_class,
            name=name,
            origin=context.container,
            dtype=self._dtype,
        )
        # this was the old way, that does not allow recycling of temp variables,
        # which would be bad in GPU kernels, where threadId.x needs to map to all
        # self._local = local_variable_class(
        #     namespace=context.namespace,
        #     **kwargs,
        # )
        if autorequire:
            context.container.requires(self.local)
        return self._local

    def create_input_representative(
        self,
        context=None,
        input_variable_class=None,
        autorequire=True,
        **kwargs,
    ):
        """Create an input-style representative for the selector."""
        if input_variable_class is None:
            input_variable_class = type(self).input_variable_class
        assert input_variable_class is not None
        if context is None:
            raise ValueError("No context provided")
        if self._local is None:
            self._local = input_variable_class(
                # assigned_variable=self,
                assignment=(self, None),
                # key=None,
                namespace=context.namespace,
                **kwargs,
            )
        if autorequire:
            context.container.requires(self.local)
        context.namespace.assign(self, None, self.local)
        return self._local

    def as_argument(self) -> str:
        """Return the representative as a routine-call argument."""
        return self.local.as_argument()

    def reset_representative(self) -> None:
        """Discard any created representative variable."""
        self._local = None

    def expr(self) -> str:
        """Return the representative expression for this selector."""
        return f"{self.local.expr()}"

    @property
    def max_value(self):
        """access max value"""
        return self._max_value

    @property
    def min_value(self):
        """access min value"""
        return self._min_value

    @property
    def local(self):
        """access the local representation of the frame selector"""
        return self._local

    @property
    def is_scalar(self):
        """return boolean deciding whether the variable is a scalar"""
        return self._size is None

    @property
    def size(self):
        """access size attribute"""
        return self._size

    @property
    def dtype(self):
        """access datatype attribute"""
        return self.local.dtype

    @property
    def datatype(self):
        """access datatype attribute"""
        return self.local.lookup_dtype(self.dtype)

    @property
    def status(self):
        """access the status binary set as integer"""
        return self.local.status

    def split(self, max_val):
        """
        Split the covered range into two nested multiframe variables.

        :param max_val: Maximum extent that the inner selector may cover.
        :returns: ``(inner_selector, outer_selector)``.
        """
        irange = self.max_value - self.min_value

        div = (irange + max_val - 1) // max_val
        lim = min(irange, max_val)

        first = type(self)(lim, min_value=0)
        second = type(self)(div, min_value=0)
        return first, second


class KernelRequest(LibRoutineMultiFrame):
    """Multiframe-like metadata request emitted by kernel expansion."""

    _VAR_IDENTIFIER = "KernelRequest"
    _CLASS_BASE = "krq"

    def __init__(self, descriptor, max_value, min_value=0, source=None):
        super().__init__(max_value=max_value, min_value=min_value)
        self._source = source
        self._descriptor = descriptor

    @property
    def source(self):
        """Return the request source object, if one was recorded."""
        return self._source

    @property
    def descriptor(self):
        """Return the human-readable descriptor of the request."""
        return self._descriptor
