"""
#autogenerated#header#do#not#modify############################################
#
# File:        library.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2024
# Last Update: 01/04/2026, 16:05
# Version:     0.2.63
#
#################################################end#of#autoheader#do#not#modify


NOTES
=====

Dependencies in LibRoutine and in Library are always LibRoutines.

In MakeFileManager, the associated Targets are extracted and targets depend on targets,
to stay in the ecosystem. 

"""


__doc__ = """
Library assembly, build orchestration, and artifact management.

The :mod:`phoenix.fgen.library` module provides the high-level objects that tie
the symbolic instruction layer to concrete generated artifacts. A
:class:`Library` instance owns:

- the registered :class:`LibRoutine` objects exposed by the generated backend,
- the build records that describe how those routines were constructed,
- the code containers and import/definition sections needed for source output,
- the checksum-derived output folder, manifest, and makefile targets used to
  cache and rebuild artifacts only when necessary.

Libraries sit above builders and code containers. Builders lower instructions
into routine containers, while libraries decide where generated files are
written, how dependencies are tracked, and which compilation target should be
executed for a backend.

The module also defines :class:`LibraryContent` and :class:`LibRoutine`, which
represent named entities attached to one library. Those objects carry
dependency information so makefile targets, wrappers, and manifests can be
constructed from the same routine graph.
"""


import importlib.util
import json
from pathlib import Path

from .backend_config import Configuration
from .codecontainer import (
    DefinitionContainer,
    ImportSectionContainer,
    ImportContainer,
    CaptureContainer,
    CodeContainer,
    CodeLine,
)
from .computeresource import DefaultComputeResource
from .context import Context
from .builder import Builder
from .checksum import stable_checksum, stable_normalize
from .makefile import MFTSource, MakeFileManager
from ..toolbox.logger import GLOBAL_LOGGER as log

from .libroutinevar import (
    LibRoutineMultiFrame,
    ExternalImport,
    LibRoutineConstant,
    LibRoutineVariable,
    Namespace,
)


class LibraryContent:
    """parent class for anything that lives in a library"""

    def __init__(self, identifier, *, library=None, dependencies=None):
        # there has to be a base name, which we refer to as identifier
        self._identifier = identifier

        # the library the libroutine is attached to
        if library is None:
            raise ValueError("LibRoutine must be associated with a library")
        self._library = library
        if dependencies is None:
            dependencies = set()
        else:
            dependencies = set(dependencies)
        self._dependencies = dependencies
        if library is not None:
            self._dependencies.add(library)

    @property
    def dependencies(self):
        """read-only access to attribute library"""
        yield from self._dependencies

    @property
    def library(self):
        """read-only access to attribute library"""
        return self._library

    @property
    def name(self):
        """read-only access to attribute name"""
        suffix = self.get_suffix()
        if suffix:
            suffix = f"_{suffix}"
        return f"{self._identifier}{suffix}"

    def get_suffix(self):
        """get the naming suffix, which will be some kind of hash"""
        return ""

    @property
    def identifier(self):
        """read-only access to attribute identifier"""
        return str(self._identifier)

    def get_meta(self):
        """return meta information on the library"""
        return {
            "library": self.library,
            "identifier": self.identifier,
        }


class LibRoutine(LibraryContent):
    """
    LibRoutine collects and manages all information for a routine in a library.
    It stores everything necessary to define, call and import the object.

    The init does not require instructions or containers, as the object is more
    of a representative that could also represent code that does not come from
    containers.
    """

    def __init__(
        self,
        identifier: str,
        library=None,
        arguments=None,
        dependencies=None,
        container=None,
        lrv_assignments=None,
        daa_assignments=None,
        # bff_assignments=None,
    ):
        super().__init__(
            identifier, library=library, dependencies=dependencies
        )
        if arguments is None:
            arguments = []
        self._arguments = arguments
        self._container = container
        self._lrv_assignments = lrv_assignments
        self._daa_assignments = daa_assignments
        # self._bff_assignments = bff_assignments

    @property
    def key(self):
        """read-only access to attribute identifier"""
        return self.create_key()

    @property
    def container(self):
        """access the originating routine container"""
        return self._container

    @property
    def daa_assignments(self):
        """access read-only attribute assignments"""
        if self._daa_assignments is not None:
            yield from self._daa_assignments.items()

    # @property
    # def bff_assignments(self):
    #     """access read-only attribute assignments"""
    #     if self._bff_assignments is not None:
    #         yield from self._bff_assignments.items()

    @property
    def lrv_assignments(self):
        """access read-only attribute assignments"""
        if self._lrv_assignments is not None:
            yield from self._lrv_assignments.items()

    def get_meta(self):
        """return meta information on the library"""
        return (
            super()
            .get_meta()
            .update(
                {
                    "subroutine_name": self.name,
                }
            )
        )

    def get_arguments(self):
        """get the arguments"""
        yield from self._arguments

    def get_argument_assignments(self):
        """get the arguments' assignments"""
        for variable in self.get_arguments():
            if isinstance(variable, LibRoutineMultiFrame):
                yield variable.recreate(), None
            else:
                yield variable.assignment

    def get_import(self):
        """get the import statement for this libroutine"""
        return f"from {self.library.libname} import {self.identifier}"

    def create_key(self):
        """create a key that represents the libroutine in lists etc"""
        return self._identifier


class Library:
    """
    Library class description.

    Used to create, manage, adapt and compile libraries.
    """

    FILEENDING = "txt"
    INDENTSTR = "  "

    # also allow global libraries such as omp, cuda intrinsics, ...
    # LIBTYPE = "LOC"

    LIBROUTINE_CLASS = LibRoutine
    IMPORTLINE_CLASS = ImportContainer
    IMPORTSECTION_CLASS = ImportSectionContainer
    DEFAULT_BUILDER = Builder
    DEFAULT_BACKEND = None
    DEFAULT_CONTAINER_CLASS = None
    BUILD_ROOT = "phoenix_build"
    BACKEND_IDENTIFIER = "generic"

    def __init__(
        self,
        plain_name,
        build_hash=None,
        resource=None,
        configuration=None,
        general_configuration=None,
    ):
        if resource is None:
            resource = DefaultComputeResource()
        self._initialize_library_state(
            plain_name=plain_name,
            build_hash=build_hash,
            resource=resource,
            import_section_class=type(self).IMPORTSECTION_CLASS,
            backend_configuration=configuration,
            general_configuration=general_configuration,
        )

    def _initialize_library_state(
        self,
        *,
        plain_name,
        build_hash,
        resource,
        import_section_class,
        backend_configuration=None,
        general_configuration=None,
    ):
        self._build_hash = build_hash
        self._plain_name = plain_name
        self._manual_build_hash = build_hash is not None
        self._build_checksum = None
        self._build_identity_dirty = True
        self._backend = None
        self._logging_initialized = False
        self._last_log_path = None
        self._status = {}
        self.reset_status()
        self._dependencies = set()
        self._libcontent = {}
        self._routine_build_records = {}
        self._context = Context(
            name=self.libname, _library=self, resource=resource
        )
        self._backend_configuration = self._prepare_backend_configuration(
            backend_configuration
        )
        self._general_configuration = self._prepare_general_configuration(
            general_configuration
        )
        self._rout_containers = []
        self._raw_routines = []
        self._saf_capture = CaptureContainer(context=self._context)
        self._imp_capture = import_section_class(
            context=self._saf_capture.context,
            import_line_class=type(self).IMPORTLINE_CLASS,
        )
        self._def_capture = DefinitionContainer(
            context=self._imp_capture.context
        )
        self._saf_capture.add_capture_trigger(lambda x: True)
        self._imp_capture.add_capture_trigger(ExternalImport)
        self._def_capture.add_capture_trigger(LibRoutineConstant)
        self._meta = {}
        self._refresh_meta()

    def _prepare_backend_configuration(self, configuration):
        """Prepare the backend-specific configuration instance."""
        if configuration is None:
            return Configuration.for_backend(type(self).BACKEND_IDENTIFIER)
        if not isinstance(configuration, Configuration):
            raise TypeError("configuration must be a Configuration")
        return configuration.clone()

    def _prepare_general_configuration(self, configuration):
        """Prepare the general configuration instance."""
        if configuration is None:
            return Configuration.general()
        if not isinstance(configuration, Configuration):
            raise TypeError("general_configuration must be a Configuration")
        return configuration.clone()

    def _mark_build_identity_dirty(self):
        """Mark checksum-dependent path metadata as outdated."""
        self._build_identity_dirty = True
        self._build_checksum = None

    def relative_to_basepath(self, filename):
        """Return the absolute path for a relative artifact inside ``basepath``."""
        relative_path = Path(filename)
        if relative_path.is_absolute():
            raise ValueError(
                "filename must be relative to the library basepath"
            )
        return str((Path(self.basepath) / relative_path).resolve())

    @staticmethod
    def _iter_text_lines(text):
        """Yield text content as newline-free logical lines."""
        for line in text.splitlines():
            yield line

    def write_basepath_file(
        self,
        filename,
        *,
        lines=None,
        text=None,
        append=False,
    ):
        """
        Write or append a text file under the library base path.

        Exactly one of ``lines`` or ``text`` must be provided. ``lines`` may be
        any iterable or generator yielding one logical line per item. ``text``
        may be a multi-line string and will be split into logical lines.

        :param filename: Relative path under :attr:`basepath`.
        :param lines: Iterable yielding newline-free lines to write.
        :param text: Multi-line text to write.
        :param append: When ``True``, append to an existing file instead of
            truncating it.
        :returns: Absolute path of the written file.
        """
        if (lines is None) == (text is None):
            raise ValueError("set exactly one of lines or text")
        target = Path(self.relative_to_basepath(filename))
        target.parent.mkdir(parents=True, exist_ok=True)
        mode = "a" if append else "w"
        line_iterable = lines if text is None else self._iter_text_lines(text)
        with open(target, mode) as file:
            for line in line_iterable:
                file.write(str(line))
                file.write("\n")
        return str(target)

    def _refresh_meta(self):
        self._meta = {
            "backend_configuration": self.backend_configuration.to_dict(),
            "base_path": self.basepath,
            "file_name": self.filename,
            "general_configuration": self.general_configuration.to_dict(),
            "doc_name": self.docname,
            "makefile_name": self.makefilename,
            "manifest_name": self.manifestname,
            "log_name": self.logname,
            "library_name": self.libname,
            "plain_name": self._plain_name,
            "build_hash": self._build_hash,
            "build_checksum": self._build_checksum,
            "file_ending": self.fileending,
        }

    def codelines_from_text(self, text: str, context=None) -> CodeContainer:
        """generate a plain codeline from text"""
        if context is None:
            context = (
                self.context
            )  # just to be sure, send to go through def and safety
        for line in text.split("\n"):
            yield CodeLine(
                line=line,
                context=context,
            )

    @property
    def import_capture(self):
        """access read-only attribute import_capture"""
        return self._imp_capture

    @property
    def definition_capture(self):
        """access read-only attribute definition_capture"""
        return self._def_capture

    @property
    def safety_capture(self):
        """access read-only attribute safety_capture"""
        return self._saf_capture

    @property
    def context(self):
        """access read-only forwarded attribute context"""
        return self.definition_capture.context

    @property
    def backend_configuration(self):
        """Return the backend-specific configuration for this library."""
        return self._backend_configuration

    @property
    def general_configuration(self):
        """Return the general configuration for this library."""
        return self._general_configuration

    @property
    def backend(self):
        """Return the attached backend abstraction, if one was set."""
        return self._backend

    def attach_backend(self, backend):
        """Attach a high-level backend abstraction to this library."""
        self._backend = backend
        return self

    def prepare_sections(self, **kwargs):
        """build the sections"""
        log.debug(
            f"Preparing sections for {self.libname}",
            source=type(self).__name__,
        )
        self.definition_capture.build_all(**kwargs)
        self.import_capture.build_all(**kwargs)
        self.safety_capture.build_all(**kwargs)
        for imp in self.import_capture.captured:
            self._dependencies.add(imp.library)
        assert self.perform_safety_checks()
        return True

    def generate_head_containers(self, **_):
        """make the enclosings for this container"""
        yield from self.codelines_from_text(f"LIBRARY {self.libname}")

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text(f"END LIBRARY {self.libname}")

    def generate_prmb_containers(self, **_):
        yield from self.codelines_from_text("# IMPORTS")
        yield self.import_capture
        yield from self.codelines_from_text("")
        yield from self.codelines_from_text("# CONSTANTS")
        yield self.definition_capture
        yield from self.codelines_from_text("")
        yield from self.codelines_from_text("# ROUTINES")
        yield from self.codelines_from_text("")

    def generate_clsg_containers(self, **_):
        return
        yield

    def get_codelines(self, indent=0):
        """get the codelines from the inner container object"""
        yield from self.get_codelines_head(indent=indent)
        yield from self.get_codelines_prmb(indent=indent + 1)
        yield indent, ""
        yield from self.iter_routine_codelines(indent=indent + 1)
        yield from self.get_codelines_clsg(indent=indent + 1)
        yield from self.get_codelines_foot(indent=indent)

    def iter_routine_codelines(self, indent=0):
        """Yield generated routine and raw-code blocks in library order."""
        for routine_container in self.routine_containers:
            yield from routine_container.get_codelines(indent=indent)
            yield indent - 1 if indent > 0 else 0, ""
        for _routine_name, lines in self._raw_routines:
            for line in lines:
                yield indent, line
            yield indent - 1 if indent > 0 else 0, ""

    def get_codelines_head(self, indent=0):
        for container in self.generate_head_containers():
            yield from container.get_codelines(indent=indent)

    def get_codelines_foot(self, indent=0):
        for container in self.generate_foot_containers():
            yield from container.get_codelines(indent=indent)

    def get_codelines_prmb(self, indent=0):
        for container in self.generate_prmb_containers():
            yield from container.get_codelines(indent=indent)

    def get_codelines_clsg(self, indent=0):
        for container in self.generate_clsg_containers():
            yield from container.get_codelines(indent=indent)

    @property
    def routine_containers(self):
        """access the container where to put new stuff"""
        return self._rout_containers

    @staticmethod
    def _serialize_adaa_class(adaa_class):
        if adaa_class is None:
            return None
        data = {
            "class": f"{adaa_class.__module__}.{adaa_class.__qualname__}",
            "identifier": getattr(adaa_class, "_IDENTIFIER", None),
            "fixed_size": getattr(adaa_class, "_FIXED_SIZE", None),
            "keymap": None
            if getattr(adaa_class, "_KEYMAP", None) is None
            else str(adaa_class._KEYMAP),
            "datatypes": list(adaa_class.datatypes()),
        }
        return stable_normalize(data)

    @staticmethod
    def _serialize_assignments(assignments):
        if assignments is None:
            return []
        serialized = []
        for instr_var, (adaa_class, status) in assignments.items():
            serialized.append(
                {
                    "variable": instr_var.get_name(),
                    "adaa": Library._serialize_adaa_class(adaa_class),
                    "status": status,
                }
            )
        serialized.sort(key=lambda item: item["variable"])
        return serialized

    @staticmethod
    def _serialize_lrv_assignments(assignments):
        if assignments is None:
            return []
        serialized = []
        for (instr_var, key), variable in assignments.items():
            serialized.append(
                {
                    "variable": instr_var.get_name(),
                    "key": key,
                    "name": variable.name,
                    "dtype": variable.dtype,
                    "size": variable.size,
                    "status": variable.status,
                }
            )
        serialized.sort(key=lambda item: (item["variable"], str(item["key"])))
        return serialized

    def _build_record_from_inputs(
        self,
        *,
        name,
        instructions,
        builder,
        container_class,
        resource,
        buildargs,
        detailed_record,
        routine_container,
        libroutine,
    ):
        record = {
            "routine_name": name,
            "builder": builder.checksum_payload(),
            "container_class": f"{container_class.__module__}.{container_class.__qualname__}",
            "detailed_record": detailed_record,
            "resource": None
            if resource is None
            else resource.checksum_payload(),
        }
        if buildargs:
            record["buildargs"] = stable_normalize(buildargs)
        record["instructions"] = [
            instruction.record_payload(detailed=detailed_record)
            for instruction in instructions
        ]
        arguments = []
        for arg in libroutine.get_arguments():
            entry = {
                "name": arg.name,
                "dtype": arg.dtype,
                "size": arg.size,
                "status": arg.status,
            }
            if arg.assignment is not None:
                entry["assignment"] = stable_normalize(arg.assignment)
            arguments.append(entry)
        if arguments:
            record["arguments"] = arguments
        used_lrv_assignments = {}
        for argument in routine_container.get_argument_variables():
            assignment = argument.assignment
            if assignment is None:
                continue
            key = (
                type(assignment).__module__,
                type(assignment).__qualname__,
                argument.name,
            )
            used_lrv_assignments[key] = argument
        resolved_assignments = [
            {
                "instruction_variable": f"{key[0]}.{key[1]}",
                "routine_variable": variable.name,
                "dtype": variable.dtype,
                "size": variable.size,
                "status": variable.status,
            }
            for key, variable in sorted(used_lrv_assignments.items())
        ]
        if resolved_assignments:
            record["resolved_assignments"] = resolved_assignments
        return record

    def libroutine_from_instructions(
        self,
        name,
        *instructions,
        builder=None,
        daa_assignments=None,
        lrv_assignments=None,
        # bff_assignments=None,
        container_class=None,
        namespace=None,
        resource=None,
        detailed_record=False,
        **buildargs,
    ):
        """add a new libroutine from a container"""
        instructions = tuple(instructions)
        if container_class is None:
            container_class = type(self).DEFAULT_CONTAINER_CLASS
            if container_class is None:
                raise ValueError("No container class provided")

        if builder is None:
            builder = type(self).DEFAULT_BUILDER(f"default:lib{name}")

        if namespace is None:
            namespace = self.context.namespace

        context = self.context.inherit()
        log.info(
            f"Registering routine {name} in library {self._plain_name}",
            f"instruction roots: {len(instructions)}",
            f"builder: {type(builder).__module__}.{type(builder).__qualname__}",
            f"resource: {'default' if resource is None else type(resource).__module__ + '.' + type(resource).__qualname__}",
            source=type(self).__name__,
        )

        routine_container = builder.instructions_to_routine_container(
            name,
            instructions,
            context=context.set_resource(resource),
            daa_assignments=daa_assignments,
            lrv_assignments=lrv_assignments,
            container_class=container_class,
            **buildargs,
        )

        routine_container.build_all()
        self.routine_containers.append(routine_container)
        routine_arguments = list(routine_container.get_argument_variables())
        log.info(
            f"Built routine container for {name}",
            f"arguments: {len(routine_arguments)}",
            source=type(self).__name__,
        )

        libroutine = self.create_libroutine_entry(
            name=name,
            arguments=routine_arguments,
            container=routine_container,
            lrv_assignments=lrv_assignments,
            daa_assignments=daa_assignments,
            # bff_assignments=bff_assignments,
        )
        record = self._build_record_from_inputs(
            name=name,
            instructions=instructions,
            builder=builder,
            container_class=container_class,
            resource=resource,
            buildargs=buildargs,
            detailed_record=detailed_record,
            routine_container=routine_container,
            libroutine=libroutine,
        )
        self._routine_build_records[name] = record
        self._mark_build_identity_dirty()
        log.info(
            f"Finished routine registration for {name}",
            source=type(self).__name__,
        )
        return libroutine

    def create_libroutine_entry(
        self,
        name,
        arguments,
        container,
        lrv_assignments,
        daa_assignments=None,
        # bff_assignments=None,
    ):
        libroutine = type(self).LIBROUTINE_CLASS(
            name,
            library=self,
            arguments=arguments,
            container=container,
            lrv_assignments=lrv_assignments,
            daa_assignments=daa_assignments,
            # bff_assignments=bff_assignments,
        )
        self.append_libroutine(libroutine)
        return libroutine

    def _create_interface_argument(self, spec, *, namespace):
        """Create one backend-specific argument variable for raw code."""
        if isinstance(spec, LibRoutineVariable):
            return spec
        if isinstance(spec, str):
            spec = {"name": spec}
        if not isinstance(spec, dict):
            raise TypeError(f"unsupported raw routine argument spec: {spec}")
        name = spec["name"]
        dtype = spec.get("dtype", "f64")
        size = spec.get("size")
        status = spec.get("status", "IN")
        assignment = spec.get("assignment")
        builder = type(self).DEFAULT_BUILDER(f"interface:{name}")
        if isinstance(status, str):
            status = builder.lookup_status(status)
        return builder.create_libroutine_variable(
            name=name,
            dtype=dtype,
            status=status,
            size=size,
            namespace=namespace,
            assignment=assignment,
        )

    def _register_manual_routine(
        self,
        name,
        *,
        code,
        arguments,
        dependencies=None,
        daa_assignments=None,
        lrv_assignments=None,
    ):
        """Register one backend-owned manual routine with explicit metadata."""
        if name in self._libcontent:
            return self._libcontent[name]
        if isinstance(code, str):
            code_lines = list(self._iter_text_lines(code))
        else:
            code_lines = [str(line) for line in code]
        namespace = Namespace(None)
        variables = [
            self._create_interface_argument(spec, namespace=namespace)
            for spec in arguments
        ]
        libroutine = type(self).LIBROUTINE_CLASS(
            name,
            library=self,
            arguments=variables,
            container=None,
            dependencies=dependencies,
            lrv_assignments=lrv_assignments,
            daa_assignments=daa_assignments,
        )
        self.append_libroutine(libroutine)
        self._raw_routines.append((name, code_lines))
        self._routine_build_records[name] = {
            "routine_name": name,
            "raw_code": stable_normalize(code_lines),
            "arguments": [
                {
                    "name": arg.name,
                    "dtype": arg.dtype,
                    "size": arg.size,
                    "status": arg.status,
                    "assignment": None
                    if arg.assignment is None
                    else stable_normalize(arg.assignment),
                }
                for arg in variables
            ],
        }
        self._mark_build_identity_dirty()
        return libroutine

    def append_libroutine(self, libroutine):
        """add the libroutine to the known libroutines. Also include dependencies"""
        self._libcontent[libroutine.name] = libroutine
        if (lib := libroutine.library) is not None:
            self._dependencies.add(lib)

    def perform_safety_checks(self):
        """perform some safety checks"""
        # the safety capture should be empty
        lost = list(self.safety_capture.captured)
        if lost:
            raise RuntimeError(f"safety capture caught variables: {lost}")
        return True

    @property
    def fileending(self):
        """file type ending"""
        return type(self).FILEENDING

    @property
    def libname(self):
        """read-only access to property name"""
        if hasattr(self, "_backend_configuration"):
            self._ensure_build_identity()
        return self._get_libname()

    def _get_libname(self):
        """Compose the effective library name."""
        if self._build_hash is None:
            return f"{self._plain_name}"
        return f"{self._plain_name}_{self._build_hash}"

    @property
    def build_checksum(self):
        """Return the full stable checksum of the current library payload."""
        self._ensure_build_identity()
        assert self._build_checksum is not None
        return self._build_checksum

    def _ensure_build_identity(self):
        """Refresh the checksum-derived build identity if required."""
        if not self._build_identity_dirty and self._build_checksum is not None:
            return
        payload = self.checksum_payload()
        checksum = stable_checksum(payload)
        self._build_checksum = checksum
        if not self._manual_build_hash:
            self._build_hash = checksum[:12]
        self._build_identity_dirty = False
        self._refresh_meta()

    def checksum_payload(self):
        """Return the stable payload describing this library build."""
        return {
            "backend_configuration": self.backend_configuration.to_dict(),
            "class": f"{type(self).__module__}.{type(self).__qualname__}",
            "plain_name": self._plain_name,
            "fileending": self.fileending,
            "resource": None
            if self._context.resource is None
            else self._context.resource.checksum_payload(),
            "records": [
                self._routine_build_records[name]
                for name in sorted(self._routine_build_records)
            ],
        }

    @property
    def content(self):
        """generator-access to libroutines and other content"""
        yield from self._libcontent.items()

    @property
    def dependencies(self):
        """generator-access to libroutines and other dependencies"""
        yield from self.get_dependencies(recursive=False)

    def get_dependencies(
        self, *, recursive=False, _known=None, ignore_self=True
    ):
        """gather dependencies, optionally recursive"""
        if _known is None:
            _known = set()
        for dependency in self._dependencies:
            if ignore_self:
                if dependency == self:
                    continue
            if dependency not in _known:
                _known.add(dependency)
                yield dependency
                if recursive:
                    yield from dependency.get_dependencies(
                        recursive=True, _known=_known
                    )

    def __getitem__(self, key):
        return self._libcontent.get(key)

    def reset_status(self):
        # self._status["built"] = False
        self._status["compiled"] = False
        self._status["written"] = False
        self._status["prepared"] = False

    def perform_compilation(self, makefile=None, *, execute=True):
        if makefile is not None:
            makefile.append_library(self)
        execution_target = self.get_execution_target()
        local_makefile = MakeFileManager(self.libname)
        local_makefile.set_filename(
            self.relative_to_basepath(self.makefilename)
        )
        local_makefile.append_library(self)
        local_makefile.create_file(include_silent=True)
        if not execute or execution_target is None:
            return True
        result = local_makefile.execute_file(
            execution_target.target_name(),
            cwd=self.basepath,
        )
        if result.stdout:
            for line in result.stdout.splitlines():
                log.debug(line, source=type(self).__name__)
        if result.stderr:
            for line in result.stderr.splitlines():
                log.debug(line, source=type(self).__name__)
        if result.returncode != 0:
            log.error(
                f"make failed for {self.libname} with exit code {result.returncode}",
                source=type(self).__name__,
            )
            return False
        return True

    def ensure_output_dir(self):
        """Create the checksum-specific output directory if needed."""
        Path(self.basepath).mkdir(parents=True, exist_ok=True)

    def get_output_files(self):
        """Yield the files that must exist for a completed library build."""
        yield self.filename
        yield self.docname
        yield self.makefilename
        yield self.manifestname

    def get_compilation_output_files(self):
        """Yield files that are only created by executing compilation."""
        return
        yield

    def output_files_exist(self, *, include_compiled=True):
        """Return whether all expected build outputs are present."""
        for filename in self.get_output_files():
            if filename is None:
                continue
            path = Path(filename)
            if not path.is_absolute():
                path = Path(self.relative_to_basepath(filename))
            if not path.exists():
                return False
        if include_compiled:
            for filename in self.get_compilation_output_files():
                if filename is None:
                    continue
                path = Path(filename)
                if not path.is_absolute():
                    path = Path(self.relative_to_basepath(filename))
                if not path.exists():
                    return False
        return True

    def get_manifest_payload(self):
        """Return the JSON manifest describing the current library build."""
        self._ensure_build_identity()
        routines = []
        for routine_name, libroutine in self.content:
            arguments = []
            for arg in libroutine.get_arguments():
                entry = {
                    "name": arg.name,
                    "dtype": arg.dtype,
                    "size": arg.size,
                    "status": arg.status,
                }
                if arg.assignment is not None:
                    entry["assignment"] = stable_normalize(arg.assignment)
                arguments.append(entry)
            routines.append(
                {
                    "name": routine_name,
                    "arguments": arguments,
                }
            )
        return {
            "library": {
                "backend_configuration": self.backend_configuration.to_dict(),
                "class": f"{type(self).__module__}.{type(self).__qualname__}",
                "plain_name": self._plain_name,
                "libname": self.libname,
                "basepath": self.basepath,
                "fileending": self.fileending,
                "general_configuration": self.general_configuration.to_dict(),
                "build_hash": self._build_hash,
                "build_checksum": self._build_checksum,
                "makefile": self.makefilename,
            },
            "compatibility": {
                "routines": routines,
                "dependencies": sorted(
                    dependency.libname
                    for dependency in self.get_dependencies(recursive=False)
                ),
            },
            "build": self.checksum_payload(),
        }

    def write_manifest(self):
        """Write the build manifest JSON file."""
        self.write_basepath_file(
            self.manifestname,
            text=json.dumps(
                self.get_manifest_payload(),
                indent=2,
                sort_keys=True,
            ),
        )

    def load_existing_manifest(self):
        """Load the on-disk manifest if it exists."""
        manifest_path = Path(self.relative_to_basepath(self.manifestname))
        if not manifest_path.exists():
            return None
        with open(manifest_path, "r") as file:
            return json.load(file)

    def is_current_build_available(self, *, include_compiled=True):
        """Return whether the current manifest matches the desired checksum."""
        manifest = self.load_existing_manifest()
        if manifest is None:
            return False
        on_disk_checksum = manifest.get("library", {}).get(
            "build_checksum"
        ) or manifest.get("build", {}).get("build_checksum")
        return (
            on_disk_checksum == self.build_checksum
            and self.output_files_exist(include_compiled=include_compiled)
        )

    def configure_logging(self, *, reset=False):
        """Route the shared build logger into the build directory."""
        self.ensure_output_dir()
        relative_log_name = Path(self.logname).name
        absolute_log_path = str(
            Path(self.relative_to_basepath(relative_log_name)).resolve()
        )
        if (
            self._last_log_path is not None
            and self._last_log_path != absolute_log_path
            and Path(self._last_log_path).exists()
        ):
            migrated_lines = Path(self._last_log_path).read_text().splitlines()
            self.write_basepath_file(
                relative_log_name,
                lines=migrated_lines,
                append=Path(absolute_log_path).exists(),
            )
        # A forced build must always start a fresh log file. Otherwise repeated
        # build(force=True) runs keep appending stale entries, which makes the
        # build log hard to trust during debugging.
        effective_reset = reset or not Path(absolute_log_path).exists()

        def write_lines(lines):
            self.write_basepath_file(
                relative_log_name,
                lines=lines,
                append=True,
            )

        def reset_lines(lines):
            self.write_basepath_file(
                relative_log_name,
                lines=lines,
            )

        log.set_logfile(
            relative_log_name,
            path=str(Path(self.basepath).resolve()),
            reset=effective_reset,
            write_hook=write_lines,
            reset_hook=reset_lines,
        )
        log.set_loglevel(
            self.general_configuration.get_nested(
                "logging", "level", default="INFO"
            )
        )
        log.log_to_stdout(
            self.general_configuration.get_nested(
                "logging", "stdout", default=False
            )
        )
        log.info(
            f"Configured build logging for {self.libname}",
            f"log file: {absolute_log_path}",
            f"build checksum: {self.build_checksum}",
            source=type(self).__name__,
        )
        self._logging_initialized = True
        self._last_log_path = absolute_log_path

    def write_all_files(self):
        self.ensure_output_dir()
        self.write_code()
        self.write_docs()
        self.write_manifest()
        return True

    def write_code(self):
        self.ensure_output_dir()
        self.write_basepath_file(
            self.filename,
            lines=(
                indent * type(self).INDENTSTR + line
                for indent, line in self.get_codelines()
            ),
        )

    def write_docs(self):
        self.ensure_output_dir()

        def generate_doc_lines():
            for routine_name, libroutine in self.content:
                args = []
                for arg in libroutine.get_arguments():
                    size = f"({arg.size})" if arg.size is not None else ""
                    args.append(f"{arg.dtype}{size} {arg.name}")
                yield f"provides {routine_name}({', '.join(args)})"

        self.write_basepath_file(
            self.docname,
            lines=generate_doc_lines(),
        )

    def prepare(self, force=False):
        """
        prepare the library object, the codecontainer and its sections
        """
        self._ensure_build_identity()
        # make sure library is built
        if self._status["prepared"] and (not force):
            log.debug(
                f"Skipping prepare for {self.libname}; already prepared.",
                source=type(self).__name__,
            )
            return True, None
        self._status["compiled"] = False
        self._status["written"] = False
        self._status["prepared"] = False
        log.info(
            f"Preparing library {self.libname}",
            source=type(self).__name__,
        )

        ret = False
        try:
            ret = self.prepare_sections()
        except Exception as exc:
            raise exc
            return False, exc

        self._status["prepared"] = True
        return ret, None

    def write(self, force=False):
        """write to file"""
        self._ensure_build_identity()
        if self._status["written"] and (not force):
            log.debug(
                f"Skipping write for {self.libname}; already written.",
                source=type(self).__name__,
            )
            return True, None
        self._status["compiled"] = False
        self._status["written"] = False
        if not self._status["prepared"]:
            raise ValueError("cannot write unprepared library")
        log.info(
            f"Writing library outputs for {self.libname} into {self.basepath}",
            source=type(self).__name__,
        )

        ret = False
        try:
            ret = self.write_all_files()
        except Exception as exc:
            return False, exc

        self._status["written"] = ret
        return ret, None

    def compile(self, makefile=None, force=False, *, execute=True):
        """compile the library"""
        self._ensure_build_identity()
        if execute and self._status["compiled"] and (not force):
            log.debug(
                f"Skipping compile for {self.libname}; already compiled.",
                source=type(self).__name__,
            )
            return True, None
        if execute:
            self._status["compiled"] = False
        if not self._status["written"]:
            raise ValueError("cannot compile when library is not written")
        log.info(
            f"Compiling library {self.libname}",
            source=type(self).__name__,
        )

        ret = False
        try:
            ret = self.perform_compilation(makefile, execute=execute)
        except Exception as exc:
            return False, exc

        self._status["compiled"] = execute and ret
        return ret, None

    def build(self, makefile=None, force=False, compile=True):
        """build the actual library objects, i.e. write to file(s), and compile.
        Wait, fileS?
        The source file is rather obvious, however, header files might be required
        and it could be useful to output a documentatory summary.
        """
        self._ensure_build_identity()
        self.configure_logging(
            reset=force
            or not Path(self.relative_to_basepath(self.logname)).exists()
        )
        log.info(
            f"Starting build for {self.libname}",
            f"output directory: {self.basepath}",
            f"checksum: {self.build_checksum}",
            source=type(self).__name__,
        )
        if not force and self.is_current_build_available(
            include_compiled=compile
        ):
            self._status["prepared"] = True
            self._status["written"] = True
            self._status["compiled"] = compile
            log.info(
                f"Reusing cached build for {self.libname}",
                source=type(self).__name__,
            )
            if makefile is not None:
                makefile.append_library(self)
            return

        # # do I have to do that??
        # if self._status["built"] and (not force):
        #     return True, None
        # COMMENT: I don't actually need that status flag

        # launch the built chain:

        # make sure library is prepared
        success, exc = self.prepare(force=force)
        if not success:
            raise RuntimeError(
                "Error during prep phase in build:", str(exc)
            ) from exc

        for dependency in self.get_dependencies(
            recursive=False, ignore_self=True
        ):
            dependency.build(force=force, compile=compile)

        # write all relevant files
        success, exc = self.write(force=force)
        if not success:
            raise RuntimeError(
                "Error during write phase in build:", str(exc)
            ) from exc

        # launch the compilation
        success, exc = self.compile(
            force=force,
            makefile=makefile,
            execute=compile,
        )
        if not success:
            raise RuntimeError(
                "Error during compile phase in build:", str(exc)
            ) from exc
        log.info(
            f"Completed build for {self.libname}", source=type(self).__name__
        )

    def get_meta(self, key=None):
        """return meta information on the library"""
        if key is None:
            return dict(self._meta)
        if key in self._meta:
            return self._meta.get(key)
        raise KeyError(f"unknown meta key: {key}")

    # @property
    # def built(self):
    #     """retrieve the created status from the status dictionary"""
    #     return self._status["built"]

    # @property
    # def compiled(self):
    #     """retrieve the compiled status from the status dictionary"""
    #     return self._status["compiled"]

    # @property
    # def written(self):
    #     """retrieve the written status from the status dictionary"""
    #     return self._status["written"]

    # @property
    # def prepared(self):
    #     """retrieve the prepared status from the status dictionary"""
    #     return self._status["prepared"]

    @property
    def basepath(self):
        """generate the basepath value"""
        self._ensure_build_identity()
        return self._get_basepath()

    def _get_basepath(self):
        """Compose the base path used for emitted files."""
        folder = self._plain_name
        if self._build_hash is not None:
            folder = f"{folder}_{self._build_hash}"
        build_root = self.general_configuration.get_nested(
            "paths", "build_root", default=type(self).BUILD_ROOT
        )
        return str(Path(build_root) / folder)

    @property
    def filename(self):
        """generate the filename value"""
        self._ensure_build_identity()
        return self._get_filename()

    def _get_filename(self):
        """Compose the primary source filename."""
        return f"{self.libname}.{self.fileending}"

    def locate_python_module(self):
        """
        Return the importable Python module artifact if this library exposes one.

        The generic implementation supports generated Python source files. Other
        backends should override this method when they produce importable shared
        libraries or different artifact layouts.
        """
        filename = Path(self.relative_to_basepath(self.filename))
        if filename.suffix == ".py":
            return str(filename)
        return None

    def import_python_module(self):
        """
        Import and return the generated Python module for this library.

        Backends that emit importable non-Python artifacts should override
        :meth:`locate_python_module` and, if needed, this method itself.
        """
        module_path = self.locate_python_module()
        if module_path is None:
            raise NotImplementedError(
                f"{type(self).__name__} does not provide an importable Python "
                f"module artifact"
            )
        resolved_module_path = Path(module_path).resolve()
        if not resolved_module_path.exists():
            raise ImportError(
                f"generated Python module was not found at {resolved_module_path}"
            )
        spec = importlib.util.spec_from_file_location(
            self.libname,
            resolved_module_path,
        )
        if spec is None or spec.loader is None:
            raise ImportError(
                f"cannot create import spec for {resolved_module_path}"
            )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    @property
    def docname(self):
        """generate the docname value"""
        self._ensure_build_identity()
        return self._get_docname()

    def _get_docname(self):
        """Compose the documentation sidecar filename."""
        suffix = self.general_configuration.get_nested(
            "paths", "doc_suffix", default="_doc.txt"
        )
        return f"{self.libname}{suffix}"

    @property
    def makefilename(self):
        """Return the per-library makefile path."""
        self._ensure_build_identity()
        return self._get_makefilename()

    def _get_makefilename(self):
        """Compose the per-library makefile filename."""
        return self.general_configuration.get_nested(
            "paths", "makefile_name", default="Makefile"
        )

    @property
    def manifestname(self):
        """Return the manifest path for this library build."""
        self._ensure_build_identity()
        return self.general_configuration.get_nested(
            "paths",
            "manifest_name",
            default="library_manifest.json",
        )

    @property
    def logname(self):
        """Return the build log path for this library build."""
        self._ensure_build_identity()
        return self.general_configuration.get_nested(
            "paths", "build_log_name", default="build.log"
        )

    # def construct_makefile_targets(self):
    #     """
    #     create the targets for this library, that can be attached to a makefile.
    #     If any dependencies are involved, the associated targets will be yielded here as well so
    #     that one can pipe that into a makefile directly.
    #     """
    #     return
    #     yield

    def get_makefile_compile_dependency_targets(self):
        """Yield targets required to compile this library's sources."""
        for dependency in self.get_dependencies(recursive=False):
            target = dependency.get_header_target()
            if target is None:
                target = dependency.get_codefile_target()
            if target is not None:
                yield target

    def get_makefile_dependency_targets(self):
        """Yield targets required to link this library."""
        for dependency in self.get_dependencies(recursive=False):
            target = dependency.get_library_target()
            if target is None:
                target = dependency.get_codefile_target()
            if target is not None:
                yield target

    def get_makefile_targets(self):
        """Yield all makefile targets contributed by this library."""
        code_target = self.get_codefile_target()
        if code_target is not None:
            yield code_target
        library_target = self.get_library_target()
        if library_target is not None:
            yield library_target

    def get_library_target(self):
        return None

    def get_execution_target(self):
        """Return the target that should be executed for compilation."""
        return self.get_library_target()

    def get_header_target(self):
        return None

    def get_codefile_target(self):
        return MFTSource(self.relative_to_basepath(self.filename))
