"""
#autogenerated#header#do#not#modify############################################
#
# File:        pywrapper_library.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   21/08/2025
# Last Update: 13/03/2026, 15:34
# Version:     0.1.2
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """Generic Python wrapper library infrastructure for generated backends."""

from types import SimpleNamespace
import weakref

from ...adaa import GenericADAA
from ..library import Library, LibRoutine
from ..libroutinevar import (
    LibRoutineBufferVariable,
    LibRoutineVariable,
    LibRoutineMultiFrame,
    LibRoutineInputVariable,
    LibRoutineOutputVariable,
    LibRoutineInOutVariable,
)


def variations(generators, accum=None):
    """Yield the cartesian product of nested argument generators."""
    if accum is None:
        accum = tuple()
    if generators:
        this_gen = generators[0]
        for val in this_gen:
            yield from variations(generators[1:], accum=(*accum, val))
    else:
        yield accum


class _Range:
    """Simple iterable range wrapper used in wrapper argument expansion."""

    def __init__(self, start, end):
        self._start = start
        self._end = end

    def __iter__(self):
        yield from range(self._start, self._end)

    def __repr__(self):
        return f"Range[{self._start}, {self._end}]"


class _Request:
    """Deferred lookup into a prepared wrapper storage dictionary."""

    def __init__(self, source, name, key):
        self._src = source
        self._name = name
        self._key = key

    def __iter__(self):
        yield _RequestValue(self._src[self._name], self._key)

    def __repr__(self):
        return f"Request[{self._name}].data[{self._key}]"


class _RequestValue:
    """Preserve the owning object when a wrapper argument is resolved."""

    def __init__(self, owner, key):
        self._owner = owner
        self._key = key

    @property
    def owner(self):
        return self._owner

    @property
    def key(self):
        return self._key

    @property
    def value(self):
        return self._owner.data[self._key]


class WrapperBase:
    """Language-agnostic wrapper orchestration."""

    def __init__(
        self,
        name,
        exe,
        arguments,
        libroutine=None,
        *,
        owner=None,
        owner_token=None,
        reuse_buffer=False,
        **_,
    ):
        self._name = name
        self._argument_specs = []
        self._args = []
        self._rets = {}
        self._ret_factories = {}
        self._input_factories = {}
        self._inouts = {}
        self._inout_factories = {}
        self._active_inouts = {}
        self._bufs = {}
        self._buf_factories = {}
        self._exec = exe
        self._libroutine = libroutine
        self._owner = owner
        self._owner_token = owner_token
        self._reuse_buffer = bool(reuse_buffer)
        self._input_slots = {}
        self._return_order = []
        self._owner_finalizer = None
        if owner is not None and owner_token is not None:
            self._owner_finalizer = weakref.finalize(
                self,
                type(self)._finalize_owner,
                weakref.ref(owner),
                owner_token,
            )
        self._analyse_arguments(arguments)

    def __call__(self, *args, **kwargs):
        return self.call(*args, **kwargs)

    @property
    def libroutine(self):
        return self._libroutine

    @property
    def argument_specs(self):
        yield from self._argument_specs

    @staticmethod
    def _finalize_owner(owner_ref, owner_token):
        owner = owner_ref()
        if owner is not None:
            owner.release_wrapper(owner_token)

    def _analyse_arguments(self, arguments):
        self._argument_specs = []
        self._args = []
        self._rets = {}
        self._ret_factories = {}
        self._input_factories = {}
        self._inouts = {}
        self._inout_factories = {}
        self._return_order = []
        self._bufs = {}
        self._buf_factories = {}
        for spec in arguments:
            arg_type, arg, name, key, adaa = spec
            self._argument_specs.append(spec)
            if arg_type == "V":
                self._args.append(_Range(arg.min_value, arg.max_value))
            elif arg_type == "I":
                self._input_factories[name] = adaa
                self._args.append(_Request(self._input_slots, name, key))
            elif arg_type == "R":
                self._ret_factories[name] = adaa
                self._args.append(_Request(self._rets, name, key))
                if name not in self._return_order:
                    self._return_order.append(name)
            elif arg_type == "RW":
                self._inout_factories[name] = adaa
                self._args.append(_Request(self._active_inouts, name, key))
                if name not in self._return_order:
                    self._return_order.append(name)
            elif arg_type == "B":
                self._buf_factories[name] = adaa
                self._args.append(_Request(self._bufs, name, key))
            else:
                raise KeyError(f"Unknown argument type: {arg_type}")

    def call(self, *args, **kwargs):
        self.prepare_inputs(args, kwargs)
        self.prepare_buffers()
        self.prepare_returns()
        self.prepare_inouts()
        for all_args in self.prepare_arguments_iter():
            call_args, _keepalive = self.adapt_call_arguments(all_args)
            self._exec(*call_args)
        return self.extract_from_returns()

    def prepare_inputs(self, args, kwargs):
        self._input_slots.clear()
        for num, arg in enumerate(args):
            self._input_slots[num] = arg
        for name, arg in kwargs.items():
            self._input_slots[name] = arg
        for name, factory in self._input_factories.items():
            if name not in self._input_slots:
                continue
            self._validate_adaa(self._input_slots[name], factory, name, "input")

    def prepare_buffers(self):
        if not self._reuse_buffer:
            self._bufs.clear()
        for name, factory in self._buf_factories.items():
            if name not in self._bufs:
                self._bufs[name] = factory()
        for buf in self._bufs.values():
            buf.to_zero()

    def prepare_returns(self):
        for name, factory in self._ret_factories.items():
            if name not in self._rets:
                self._rets[name] = factory()
        for ret in self._rets.values():
            ret.to_zero()
            ret.mark_dirty()

    def prepare_inouts(self):
        self._active_inouts.clear()
        for name, factory in self._inout_factories.items():
            if name in self._input_slots:
                self._validate_adaa(self._input_slots[name], factory, name, "inout")
                self._active_inouts[name] = self._input_slots[name]
            else:
                if name not in self._inouts:
                    self._inouts[name] = factory()
                target = self._inouts[name]
                target.to_zero()
                self._active_inouts[name] = target
            self._active_inouts[name].mark_dirty()

    @staticmethod
    def _validate_adaa(value, factory, name, role):
        if factory is None:
            return
        if not isinstance(value, GenericADAA):
            raise TypeError(
                f"Wrapper argument {name!r} for role {role} must be a Phoenix "
                f"ADAA instance, got {type(value).__name__}."
            )
        expected_dtypes = tuple(factory.datatypes())
        value_dtypes = tuple(value.__class__.datatypes())
        if value_dtypes != expected_dtypes:
            raise TypeError(
                f"Wrapper argument {name!r} for role {role} has incompatible "
                f"ADAA datatypes {value_dtypes}, expected {expected_dtypes}."
            )
        try:
            expected_size = factory.get_fixed_size()
        except ValueError:
            expected_size = None
        if expected_size is not None and value.size != expected_size:
            raise TypeError(
                f"Wrapper argument {name!r} for role {role} has size "
                f"{value.size}, expected {expected_size}."
            )

    def extract_from_returns(self):
        returned = []
        for name in self._return_order:
            if name in self._active_inouts:
                returned.append(self._active_inouts[name])
            elif name in self._rets:
                returned.append(self._rets[name])
        if len(returned) > 1:
            return tuple(returned)
        if len(returned) == 1:
            return returned[0]
        return True

    def prepare_arguments_iter(self):
        yield from variations(self._args)

    def adapt_call_arguments(self, all_args):
        """Adapt prepared arguments to the backend call ABI."""
        call_args = []
        for arg in all_args:
            if isinstance(arg, _RequestValue):
                call_args.append(arg.value)
            else:
                call_args.append(arg)
        return tuple(call_args), []


class PyWrapperLibraryBase(Library):
    """Language-independent base for Python-side wrapper libraries."""

    WRAPPER_CLASS = WrapperBase

    def __init__(self, wrapped_library, wrapper_lib=None, build_hash=None):
        wrapped_lib_name = wrapped_library.libname
        super().__init__("py_" + wrapped_lib_name, build_hash=build_hash)
        self._wrapped_library = wrapped_library
        self._dependencies.add(wrapped_library)
        for dependency in wrapped_library.get_dependencies(recursive=True):
            self._dependencies.add(dependency)
        self._wrapper_lib = wrapper_lib
        self._wrappers = weakref.WeakValueDictionary()
        self._wrapper_names_by_token = {}
        self._wrapper_tokens_by_name = {}
        self._next_wrapper_token = 0
        self._closed = False
        self._close_finalizer = weakref.finalize(
            self,
            type(self)._finalize_close,
            weakref.ref(self),
        )

    @classmethod
    def from_compiled_hash(
        cls,
        library_class,
        plain_name,
        build_hash,
        *,
        wrapper_lib=None,
        **library_kwargs,
    ):
        """Recreate a wrapper library from an on-disk manifest and build hash."""
        wrapped_library = library_class(
            plain_name,
            build_hash=build_hash,
            **library_kwargs,
        )
        manifest = wrapped_library.load_existing_manifest()
        if manifest is None:
            raise FileNotFoundError(
                f"no manifest found for {plain_name!r} with hash {build_hash!r}"
            )
        for routine_entry in manifest.get("compatibility", {}).get(
            "routines", []
        ):
            arguments = [
                cls._argument_from_manifest(argument_entry)
                for argument_entry in routine_entry.get("arguments", [])
            ]
            wrapped_library._libcontent[routine_entry["name"]] = (  # noqa: SLF001
                wrapped_library.LIBROUTINE_CLASS(
                    routine_entry["name"],
                    library=wrapped_library,
                    arguments=arguments,
                    container=SimpleNamespace(
                        is_kernel=bool(routine_entry.get("kernel", False))
                    ),
                )
            )
        return cls(
            wrapped_library,
            wrapper_lib=wrapper_lib,
            build_hash=build_hash,
        )

    @staticmethod
    def _argument_from_manifest(entry):
        """Reconstruct a routine variable from a manifest argument record."""
        kwargs = {
            "name": entry["name"],
            "dtype": entry["dtype"],
            "size": entry["size"],
        }
        status = int(entry["status"])
        io_status = status & (
            LibRoutineVariable.STATUS_INPUT | LibRoutineVariable.STATUS_OUTPUT
        )
        if io_status == LibRoutineVariable.STATUS_OUTPUT:
            variable = LibRoutineOutputVariable(**kwargs)
        elif status & LibRoutineVariable.STATUS_BUFFER:
            variable = LibRoutineBufferVariable(**kwargs)
        elif io_status == LibRoutineVariable.STATUS_INOUT:
            variable = LibRoutineInOutVariable(**kwargs)
        else:
            variable = LibRoutineInputVariable(**kwargs)
        if status & LibRoutineVariable.STATUS_BUFFER:
            variable._status |= LibRoutineVariable.STATUS_BUFFER  # noqa: SLF001
        return variable

    @property
    def wrapped_library(self):
        return self._wrapped_library

    @property
    def wrapper_lib(self):
        return self._wrapper_lib

    @staticmethod
    def _finalize_close(self_ref):
        instance = self_ref()
        if instance is not None:
            instance.close()

    def close(self):
        """Release Python-side wrapper state held by this library."""
        if self._closed:
            return
        self._closed = True
        self._wrappers.clear()
        self._wrapper_names_by_token.clear()
        self._wrapper_tokens_by_name.clear()
        self._wrapper_lib = None

    def _register_wrapper_token(self) -> int:
        token = self._next_wrapper_token
        self._next_wrapper_token += 1
        return token

    def release_wrapper(self, owner_token):
        """Drop one live wrapper registration and auto-close on last use."""
        if self._closed:
            return
        self._wrappers.pop(owner_token, None)
        name = self._wrapper_names_by_token.pop(owner_token, None)
        if name is not None:
            tokens = self._wrapper_tokens_by_name.get(name)
            if tokens is not None:
                tokens.discard(owner_token)
                if not tokens:
                    self._wrapper_tokens_by_name.pop(name, None)
        if not self._wrappers:
            self.close()

    def register_wrapper(self, name, token, wrapper):
        """Register one live wrapper under both token and routine name."""
        self._wrappers[token] = wrapper
        self._wrapper_names_by_token[token] = name
        self._wrapper_tokens_by_name.setdefault(name, set()).add(token)

    def get_wrapper(self, name):
        """Return the most recent live wrapper registered for `name`."""
        tokens = self._wrapper_tokens_by_name.get(name)
        if not tokens:
            raise KeyError(f"wrapper {name!r} is not registered")
        live_tokens = [token for token in sorted(tokens, reverse=True) if token in self._wrappers]
        if not live_tokens:
            self._wrapper_tokens_by_name.pop(name, None)
            raise KeyError(f"wrapper {name!r} is not registered")
        return self._wrappers[live_tokens[0]]

    def resolve_wrapper_callable(self, libroutine_name, libroutine):
        raise NotImplementedError("must be implemented in subclass")

    def create_wrapper_instance(
        self,
        name,
        exe,
        arguments,
        libroutine,
        *,
        owner=None,
        owner_token=None,
        reuse_buffer=False,
    ):
        return type(self).WRAPPER_CLASS(
            name=name,
            exe=exe,
            arguments=arguments,
            libroutine=libroutine,
            owner=owner,
            owner_token=owner_token,
            reuse_buffer=reuse_buffer,
        )

    def create_wrapper(
        self,
        libroutine_name,
        daa_assignments=None,
        debug=True,
        *,
        reuse_buffer=False,
    ):
        libroutine = self._wrapped_library[libroutine_name]
        if not isinstance(libroutine, LibRoutine):
            raise TypeError("can only wrap libroutine")

        all_assignments = {key: val for key, val in libroutine.daa_assignments}
        if daa_assignments is not None:
            all_assignments.update(daa_assignments)

        internally_call_with = []
        if debug:
            requst = {}
            buffer = {}
            retrns = {}

        for arg in libroutine.get_arguments():
            if arg.assignment is not None:
                src, key = arg.assignment
                if isinstance(src, LibRoutineMultiFrame):
                    internally_call_with.append(
                        ("V", arg, arg.name, None, None)
                    )
                elif src in all_assignments:
                    adaa, status = all_assignments[src]
                    name = src().name
                    io_status = status & (
                        LibRoutineVariable.STATUS_INPUT
                        | LibRoutineVariable.STATUS_OUTPUT
                    )
                    if (
                        status & LibRoutineVariable.STATUS_BUFFER
                        or isinstance(arg, LibRoutineBufferVariable)
                    ):
                        status |= LibRoutineVariable.STATUS_INOUT
                        if debug:
                            if (name, key) in buffer:
                                assert buffer[(name, key)] == (adaa, status)
                            else:
                                buffer[(name, key)] = adaa, status
                        internally_call_with.append(
                            ("B", arg, name, key, adaa)
                        )
                    elif io_status == LibRoutineVariable.STATUS_INOUT:
                        internally_call_with.append(
                            ("RW", arg, name, key, adaa)
                        )
                    elif io_status == LibRoutineVariable.STATUS_OUTPUT:
                        if debug:
                            if (name, key) in retrns:
                                assert retrns[(name, key)] == (adaa, status)
                            else:
                                retrns[(name, key)] = adaa, status
                        internally_call_with.append(
                            ("R", arg, name, key, adaa)
                        )
                    else:
                        if debug:
                            if (name, key) in requst:
                                assert requst[(name, key)] == status
                            else:
                                requst[(name, key)] = status
                        internally_call_with.append(
                            ("I", arg, name, key, adaa)
                        )
                else:
                    raise ValueError(f"assignment for {src} not found")

        routine = self.resolve_wrapper_callable(libroutine_name, libroutine)
        owner_token = self._register_wrapper_token()
        wrapper = self.create_wrapper_instance(
            libroutine_name,
            routine,
            internally_call_with,
            libroutine,
            owner=self,
            owner_token=owner_token,
            reuse_buffer=reuse_buffer,
        )
        self.register_wrapper(libroutine_name, owner_token, wrapper)
        return wrapper

    def create_direct_wrapper(
        self,
        libroutine_name,
        adaa_class,
        *,
        key=None,
        output_names=None,
        buffer_names=None,
        reuse_buffer=False,
    ):
        """Create a wrapper directly from routine argument metadata.

        This path is intended for reloading previously compiled libraries from a
        known build hash, where the original instruction-variable assignments are
        no longer available in memory.
        """
        libroutine = self._wrapped_library[libroutine_name]
        if key is None:
            data_keys = tuple(getattr(adaa_class, "_DATATYPES", {}).keys())
            if len(data_keys) != 1:
                raise ValueError(
                    "Direct wrapper creation needs an explicit data key for "
                    "multi-component ADAAs."
                )
            key = data_keys[0]
        if output_names is None:
            output_names = set()
        else:
            output_names = set(output_names)
        if buffer_names is None:
            buffer_names = set()
        else:
            buffer_names = set(buffer_names)

        internally_call_with = []
        for arg in libroutine.get_arguments():
            status = arg.status
            io_status = status & (
                LibRoutineVariable.STATUS_INPUT
                | LibRoutineVariable.STATUS_OUTPUT
            )
            logical_name = arg.name
            suffix = f"_{key}"
            if logical_name.endswith(suffix):
                logical_name = logical_name[: -len(suffix)]
            if (
                logical_name in buffer_names
                or arg.name in buffer_names
                or status & LibRoutineVariable.STATUS_BUFFER
                or isinstance(arg, LibRoutineBufferVariable)
            ):
                internally_call_with.append(("B", arg, logical_name, key, adaa_class))
            elif io_status == LibRoutineVariable.STATUS_INOUT:
                internally_call_with.append(("RW", arg, logical_name, key, adaa_class))
            elif logical_name in output_names or arg.name in output_names or (
                io_status == LibRoutineVariable.STATUS_OUTPUT
                and not status & LibRoutineVariable.STATUS_BUFFER
            ):
                internally_call_with.append(("R", arg, logical_name, key, adaa_class))
            else:
                internally_call_with.append(("I", arg, logical_name, key, adaa_class))

        routine = self.resolve_wrapper_callable(libroutine_name, libroutine)
        owner_token = self._register_wrapper_token()
        wrapper = self.create_wrapper_instance(
            libroutine_name,
            routine,
            internally_call_with,
            libroutine,
            owner=self,
            owner_token=owner_token,
            reuse_buffer=reuse_buffer,
        )
        self.register_wrapper(libroutine_name, owner_token, wrapper)
        return wrapper
