"""
#autogenerated#header#do#not#modify############################################
#
# File:        multispinlib.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   24/02/2026
# Last Update: 08/04/2026, 16:07
# Version:     0.0.1074
#
#################################################end#of#autoheader#do#not#modify


multispin_lib provides classes and routines to comfortably create multi spin
systems and connect them

"""

from __future__ import annotations

__doc__ = """Helpers for assembling and manipulating coupled multi-spin systems."""

import numpy as np
from scipy.spatial.transform import Rotation
from itertools import combinations

ZEROTOL = 1e-14


class Vector:
    """A class to store and manage a position"""

    def __init__(self, *components, dim=None):
        if dim is None:
            dim = len(components)
        else:
            if not len(components) == dim:
                raise ValueError("components and dimension do not match")
        self._dim = dim
        self._cmp = components

    def make_compatible(self, other):
        """check the compatibility between two positions"""
        if other is None:
            return Vector(*[0 for _ in range(self._dim)])
        if self.dim == other.dim:
            return other
        raise ValueError("cannot add incompatible vectors")

    def __str__(self):
        return str(self.as_tuple())

    def __repr__(self):
        return str(self.as_tuple())

    @property
    def dim(self):
        """request the dimension of this position"""
        return self._dim

    @property
    def components(self):
        """access the individual components"""
        yield from self._cmp

    def distance(self, other):
        """
        Compute the distance between this and another position.
        Defaults to euclidean distance.
        """
        other = self.make_compatible(other)
        if not other:
            raise ValueError("positions not compatible for distance measure")
        r2 = sum(
            (c1 - c2) ** 2 for c1, c2 in zip(self.components, other.components)
        )
        return np.sqrt(r2)

    def origin(self):
        """return an origin instance in the format of this vector"""
        return type(self)(*[0 for _ in range(self.dim)])

    @classmethod
    def get_cms(cls, *pos_weight_pairs):
        """get the center of mass"""
        if not pos_weight_pairs:
            raise ValueError("cannot compute CMS from empty list")
        if not isinstance(pos_weight_pairs[0], tuple):
            return cls.get_cms(*[(pos, 1) for pos in pos_weight_pairs])
        accum_pos = None
        accum_wgh = 0.0
        for pos, weight in pos_weight_pairs:
            if accum_pos is None:
                accum_pos = pos.origin()
            accum_pos += pos * weight
            accum_wgh += weight
        return accum_pos / accum_wgh

    @staticmethod
    def get_rot_matrix(angle, axis=None, degrees=False):
        """compute a rotation matrix for the vector"""
        if axis.dim == 2:
            if degrees:
                angle = np.deg2rad(angle)
            return np.array(
                [
                    [np.cos(angle), np.sin(angle)],
                    [-np.sin(angle), np.cos(angle)],
                ]
            )
        assert axis.dim == 3
        rotation = Rotation.from_rotvec(
            (angle * axis / abs(axis)).as_tuple(), degrees=degrees
        )
        # avoid numpy stuff here
        return [Vector(*map(float, line)) for line in rotation.as_matrix()]

    def scalar_product(self, other):
        """compute the scalar product of two vectors"""
        if not isinstance(other, Vector):
            other = Vector(*other)
        return sum(
            (cp * ot for cp, ot in zip(self.components, other.components))
        )

    def matrix_transform(self, matrix):
        """perform a matrix transform"""
        return type(self)(*[self.scalar_product(line) for line in matrix])

    def scale(self, alpha, offset=None):
        """scale the position w.r.t. reference. The reference defaults to the origin"""
        if offset is None:
            offset = self.origin()
        if not isinstance(offset, Vector):
            offset = Vector(*offset)
        return offset + alpha * (self - offset)

    def translate(self, vector):
        """translate a vector by another"""
        if not isinstance(vector, Vector):
            vector = Vector(*vector)
        return self + vector

    def rotate(self, angle, axis=None, offset=None, degrees=False):
        """rotate a position vector by an angle around an axis at an offset"""
        if offset is None:
            offset = self.origin()
        if not isinstance(offset, Vector):
            offset = Vector(*offset)
        if self.dim == 2:
            axis = Vector(0, 0)
        else:
            assert axis is not None
        if not isinstance(axis, Vector):
            axis = Vector(*axis)
        rot_mat = self.get_rot_matrix(angle, axis, degrees=degrees)
        return offset + (self - offset).matrix_transform(rot_mat)

    # provide some basic vector operations

    def __add__(self, other):
        # if other is None:
        #     other = tuple(*[0 for _ in range(self.dim)])
        other = self.make_compatible(other)
        return type(self)(
            *[cp + ot for cp, ot in zip(self.components, other.components)]
        )

    def __sub__(self, other):
        # if other is None:
        #     other = tuple(*[0 for _ in range(self.dim)])
        other = self.make_compatible(other)
        return type(self)(
            *[cp - ot for cp, ot in zip(self.components, other.components)]
        )

    def __abs__(self):
        return self.distance(self.origin())

    def __mul__(self, other):
        assert not isinstance(other, Vector)
        return type(self)(*[cp * other for cp in self.components])

    def __rmul__(self, other):
        assert not isinstance(other, Vector)
        return type(self)(*[cp * other for cp in self.components])

    def __truediv__(self, other):
        assert not isinstance(other, Vector)
        return type(self)(*[cp / other for cp in self.components])

    def __iter__(self):
        # allows list conversion, ...
        yield from map(float, self._cmp)

    def as_tuple(self):
        """convert to a component tuple"""
        return tuple(self)


class Unit:
    """a simple unit, acts as a system building block"""

    _counter = 0
    _species = "UNIT"

    def __init__(self, *, name=None, **kwargs):
        count = type(self)._counter
        self._idx = count
        if name is None:
            name = f"{type(self)._species}_{count}"
        type(self)._counter += 1
        self._enum = count
        self._name = name
        self._parent = None
        super().__init__()

    def content(
        self,
        **_,
    ):
        """access read-only property content"""
        yield self

    def level(self):
        """recursively compute the level of the unit. The default is a recursive break"""
        return 0

    def _get_gen_dict(self):
        return {"name": self._name}

    def copy(self, name=None):
        """make a copy of self"""
        if name is None:
            name = self.name
        obj = type(self)(**{**self._get_gen_dict(), "name": name})
        return obj

    @property
    def name(self):
        """read-only access to attribute name"""
        return self._name

    def __init_subclass__(cls, species=None):
        if species is None:
            species = cls.__name__.upper()
        if not isinstance(species, str):
            raise TypeError("species must be a string")
        cls._species = species
        cls._counter = 0

    @classmethod
    def new_species(cls, species, *co_classes):
        """derive a new species"""
        if co_classes and __debug__:
            print(
                "the use of co-classes is highly discouraged. But you do you."
            )
        return type(
            species,
            (*co_classes, cls),
            {},
        )

    def __gt__(self, other):
        if self.species == other.species:
            return self.index > other.index
        return self.species > other.species

    @property
    def species(self):
        """read-only access to class attribute species"""
        return type(self)._species

    @property
    def index(self):
        """read-only access to attribute index"""
        return self._idx

    @property
    def parent(self):
        """read-only access to attribute parent"""
        return self._parent

    def set_parent(self, parent, overwrite=False):
        """set the parent. Make sure parent is not set or allow overwrite"""
        if self._parent is not None:
            if not overwrite:
                raise ValueError("parent already set")
        if parent is self:
            raise ValueError("parent cannot point to self")
        if parent is not None:
            if self in parent.get_family_tree():
                raise ValueError("cyclic family trees are not allowed")
        self._parent = parent

    def get_family_tree(self):
        """create a family tree"""
        if self.parent is not None:
            yield from self.parent.get_family_tree()
        yield self

    def __str__(self):
        name = ".".join(obj.name for obj in self.get_family_tree())
        return f"<{name}[{self._enum}]>"  # @{self.position()}>"

    def __repr__(self):
        return f"<{self.name}>"


class Group(Unit, species="GROUP"):
    """A class to have a group of either spins or other groups"""

    def __init__(self, *units, **kwargs):
        self._content = []
        super().__init__(**kwargs)
        for unit in units:
            self.append(unit)

    def level(self):
        """recursively compute the level of the unit. The default is a recursive break"""
        if self._content:
            return 1 + max(con.level() for con in self._content)
        return 0

    def apply(self, key, *args, **kwargs):
        """apply a transform or operation"""
        for con in self.content():
            con.apply(key, *args, **kwargs)

    def content(
        self,
        *,
        recursive=False,
    ):
        """access read-only property content"""
        if recursive:
            for unit in self._content:
                yield from unit.content(recursive=True)
        else:
            for unit in self._content:
                yield unit

    def units(self):
        """Yield all spins in a deterministic order."""
        yield from self.content(recursive=True)

    def copy(self, name=None):
        if name is None:
            name = self.name
        obj = type(self)(**(self._get_gen_dict() | {"name": name}))
        for con in self._content:
            con_copy = con.copy()
            obj.append(con_copy)
        return obj

    def append(self, *units):
        """append to a group"""
        # automatically break collectives in groups
        for unit in units:
            unit.set_parent(self)
            self._content.append(unit)
        return self

    def __iter__(self):
        yield from self.content(recursive=False)


class Single(Unit, species="SINGLE"):
    """
    A class for a single spin.

    Currently implemented as a subclass of Unit, but I consider to implemented
    as a trivial group of size 1
    """

    def content(
        self,
        **_,
    ):
        """recursion break"""
        yield self

    def append(self, *units, **_):
        """Singles cannot contain child units"""
        raise TypeError("Cannot append to a Single")


#########################################
#
# o     o   o          o
# 8b   d8              8
# 8`b d'8  o8  `o  o'  8  odYo.  .oPYo.
# 8 `o' 8   8   `bd'   8  8' `8  Yb..
# 8     8   8   d'`b   8  8   8    'Yb.
# 8     8   8  o'  `o  8  8   8  `YooP'
# ..::::.. :.. ..:::.. .. ..::.. :.....:
# :::::::: ::: ::::::: :: :::::: :::::::
# :::::::: ::: ::::::: :: :::::: :::::::
#########################################


class _MixIn(Unit):
    def _get_gen_dict(self):
        return {}


class Nuclear(_MixIn):
    """Introduce features relevant for nuclear spins"""

    def __init__(self, *, gamma=1.0, spin2=1, **kwargs):
        self._gamma = gamma  # gyromagnetic ratio
        self._spin2 = spin2  # the spin number as a multiple of 1/2
        super().__init__(**kwargs)

    def _get_gen_dict(self):
        return super()._get_gen_dict() | {
            "gamma": self._gamma,
            "spin2": self._spin2,
        }

    def gamma(self):
        """get the value for the gyromagnetic ratio gamma"""
        return self._gamma

    def spin_half(self):
        """get the value for the spin number as a multiple of 1/2. For spin-3/2, the value is 3"""
        return self._spin2


class SpatialPosition(_MixIn):
    """summarize functionality for spatial positions"""

    _dim = None

    def __init__(self, *, pos=None, **kwargs):
        pos = self._pos_to_vec(pos)
        self._pos = pos
        super().__init__(**kwargs)

    def _get_gen_dict(self):
        return super()._get_gen_dict() | {"pos": self._pos}

    def _pos_to_vec(self, pos):
        if isinstance(pos, Vector):
            if pos.dim != self._dim:
                raise ValueError("Dimension mismatch")
        if pos is not None:
            return Vector(*pos, dim=type(self)._dim)
        if type(self)._dim is None:
            return None
        return Vector(
            *[0 for _ in range(type(self)._dim)], dim=type(self)._dim
        )

    def apply(self, key, *args, **kwargs):
        """apply a transform or operation"""
        match key:
            case "scale":
                return self.scale(*args, **kwargs)
            case "translate":
                return self.translate(*args, **kwargs)
            case "rotate":
                return self.rotate(*args, **kwargs)

        if not hasattr(self, "apply"):
            raise TypeError(
                "apply is only provided if you inherit from a unit!"
            )
        return super().apply(key, *args, **kwargs)

    def position(self, wrt=None):
        """read-only access to attribute position"""
        if wrt is None:
            return self._pos
        return self.position() - wrt.position()

    def distance(self, other):
        """compute the distance between this spin and another"""
        assert isinstance(self.position(), Vector)
        assert isinstance(other.position(), Vector)
        return self.position().distance(other.position())

    def scale(self, alpha, offset=None):
        """implement a scaling of the positions"""
        if self._pos is not None:
            self._pos = self._pos.scale(alpha, offset=offset)
        return self

    def translate(self, vector):
        """implement a translation by a vector"""
        if self._pos is not None:
            self._pos = self._pos.translate(vector)
        return self

    def rotate(self, angle, axis=None, offset=None, degrees=False):
        """implement a rotation around a given axis at an offset by an angle"""
        if self._pos is not None:
            self._pos = self._pos.rotate(
                angle, axis=axis, offset=offset, degrees=degrees
            )
        return self


class SpatialPosition3D(SpatialPosition):
    """explicitely use 3 dimensions"""

    _dim = 3


class SpatialPosition2D(SpatialPosition):
    """explicitely use 2 dimensions"""

    _dim = 2


class SpatialPosition1D(SpatialPosition):
    """explicitely use 1 dimension"""

    _dim = 1


class System:
    """Root object for a hierarchy of local sites and Hamiltonian helpers."""

    def __init__(self, units, hamiltonian=None, **properties):
        self._units = units
        self._hamiltonian = hamiltonian
        self._properties = properties

    def __getitem__(self, key):
        return self._properties.get(key, None)

    def units(self):
        yield from self._units.units()

    def unit_index_map(self):
        """Map local sites to dense tensor-product indices."""
        return {unit: idx for idx, unit in enumerate(self.units())}

    def pair_iter(self, *, excludes=None, considers=None):
        """Iterate over spin pairs with optional geometric filtering."""
        if excludes is None:
            excludes = []
        if considers is None:
            considers = []
        for unit_a, unit_b in combinations(self.units(), 2):
            if any(not consider(unit_a, unit_b) for consider in considers):
                continue
            if any(exclude(unit_a, unit_b) for exclude in excludes):
                continue
            yield unit_a, unit_b

    def create_hamiltonian(self, name="hamiltonian"):
        """Create a Hamiltonian bound to this system."""
        return Hamiltonian(system=self, name=name)


class HamiltonianTerm:
    """A generic Hamiltonian term acting on a system."""

    _KIND: str = "generic"
    __slots__ = (
        "_units",
        "_coefficient",
        "_specifier",
        "_system",
        "_metadata",
    )

    def __init__(self, units, coefficient, specifier, system, **metadata):
        self._units = units
        self._coefficient = coefficient
        self._specifier = specifier
        self._system = system
        self._metadata = metadata

    @property
    def units(self):
        return self._units

    @property
    def coefficient(self):
        return self._coefficient

    @property
    def specifier(self):
        return self._specifier

    @property
    def system(self):
        return self._system

    @property
    def kind(self):
        return type(self)._KIND

    def __gt__(self, other: HamiltonianTerm) -> bool:
        if len(self._units) < len(other._units):
            return False
        if len(self._units) > len(other._units):
            return True

        assert len(self._units) == len(other._units)
        if self._units > other._units:
            return True
        if self._units < other._units:
            return False

        if self._coefficient > other._coefficient:
            return True
        return False

    def __eq__(self, other: HamiltonianTerm) -> bool:
        if self._units != other._units:
            return False
        if callable(self.coefficient) or callable(other.coefficient):
            raise TypeError(
                "Cannot compare HamiltonianTerm with callable coefficients"
            )
        if abs(self.coefficient - other.coefficient) < ZEROTOL:
            return True
        return False

    def _evaluate_coeff(self, time=0.0, system=None):
        """Evaluate the coefficient, including dynamic callables."""
        coeff = self.coefficient
        if callable(coeff):
            return coeff(time, system, self)
        return coeff

    def fix(self, time=0.0, system=None):
        coeff = self._evaluate_coeff(time=time, system=system)
        return HamiltonianTerm(
            units=self.units,
            coefficient=coeff,
            specifier=self.specifier,
            system=self.system,
        )


class Hamiltonian:
    """Sparse symbolic Hamiltonian with optional explicit matrix terms."""

    def __init__(self, *terms, system=None, name="hamiltonian"):
        if system is None:
            raise ValueError("system must be specified")
        self._system = system
        self._name = name
        self._terms = []
        self.extend(*terms)

    @property
    def system(self):
        return self._system

    @property
    def name(self):
        return self._name

    @property
    def terms(self):
        return tuple(self._terms)

    def copy(self, name=None):
        clone = type(self)(
            *self.terms,
            system=self.system,
            name=self.name if name is None else name,
        )
        clone._terms = list(self._terms)
        return clone

    def extend(self, *terms):
        """add one or more terms to the hamiltonian"""
        for term in terms:
            if not isinstance(term, HamiltonianTerm):
                raise TypeError(
                    "can only append HamiltonianTerm to Hamiltonian"
                )
            self._terms.append(term)

        return self


if __name__ == "__main__":

    class NuclearSpin(Single, Nuclear, SpatialPosition3D):
        pass

    C13 = NuclearSpin.new_species("C13")

    test = C13()

    print(C13.__mro__)
    print(dir(test))
    print(test)
    print(test.gamma())
    print(test.position())
    # print(next(another_system.content(recursive=True)))
    test.apply("translate", (1, 2, 0))
    print(test.position())
    test.apply("rotate", angle=30, axis=(1, 0, 0), degrees=True)
    print(test.position())

    mol1 = Group()
    mol2 = Group()
    for _ in range(10):
        mol1.append(C13())
        mol2.append(C13())

    testsystem = Group(mol1, mol2, name="foo")
    for s in testsystem.units():
        print(s)
