"""
#autogenerated#header#do#not#modify############################################
#
# File:        plain_builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   19/03/2026
# Last Update: 19/03/2026, 13:35
# Version:     0.1.0
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """
Plain-text symbolic backend generation.

The plain backend renders instruction trees into an uppercase, parser-friendly
text format that mirrors the generic code-container structure without targeting
an executable programming language. It is useful for diagnostics, external
tooling, and IR inspection.
"""

from ....aux import configured_zero_tol, multiline_iterable
from ...builder import Builder
from ...codecontainer import (
    AccumulateStatementLine,
    AssignmentStatementLine,
    CaptureContainer,
    CodeLine,
    CommentLine,
    DefinitionContainer,
    DefinitionLines,
    HookContainer,
    ImportContainer,
    ImportSectionContainer,
    IntCombineExpandContainer,
    MultiFrameExpandContainer,
    RoutineCallContainer,
    RoutineContainer,
)
from ...computeresource import ComputeResource
from ...context import Context
from ...instruction import (
    AffineOperationInstruction,
    BiLinearOperationInstruction,
)
from ...library import Library, LibRoutine
from ...libroutinevar import (
    ExternalImport,
    LibRoutineBufferVariable,
    LibRoutineConstant,
    LibRoutineInOutVariable,
    LibRoutineInputVariable,
    LibRoutineLocalVariable,
    LibRoutineOutputVariable,
    LibRoutineVariable,
    Numeric,
)


class PlainNumeric(Numeric):
    """Plain-text builder numeric wrapper."""


ZERO_TOL = configured_zero_tol()


class PlainLibRoutineVariable(LibRoutineVariable):
    """Shared variable behaviour for the symbolic plain-text backend."""

    DTYPE_LOOKUP = {
        "f64": "F64",
        "f32": "F32",
        "i64": "I64",
        "i32": "I32",
    }

    ROLE = "VALUE"

    def lookup_dtype(self, dtype):
        if dtype in type(self).DTYPE_LOOKUP:
            return type(self).DTYPE_LOOKUP[dtype]
        raise ValueError(f"Unknown dtype: {dtype}")

    def expr_at(self, offset_string):
        return f"{self.name}[{offset_string}]"

    def _shape_suffix(self):
        if self.is_scalar:
            return ""
        return f"[{self._size}]"

    def get_definition_lines(self):
        yield (
            f"DEFINE {type(self).ROLE} {self.lookup_dtype(self._dtype)} "
            f"{self._name}{self._shape_suffix()}"
        )

    def get_zero_value(self):
        if self.dtype.startswith("i"):
            return "0"
        return "0.0"

    def generate_tozero_lines(self):
        zero_value = self.get_zero_value()
        if self.is_scalar:
            yield f"{self.expr()} = {zero_value}"
            return
        yield f"CALL PHOENIX_ZERO_{self.dtype.upper()}({self.name}, {self.size})"


class PlainLocalVariable(PlainLibRoutineVariable, LibRoutineLocalVariable):
    """Local plain-text variable."""

    ROLE = "LOCAL"


class PlainDummyVariable(PlainLibRoutineVariable):
    """Base class for plain-text routine arguments."""

    ROLE = "ARG"

    def as_argument_declaration(self):
        return self._name


class PlainInputVariable(PlainDummyVariable, LibRoutineInputVariable):
    """Read-only symbolic routine argument."""

    ROLE = "INPUT"


class PlainOutputVariable(PlainDummyVariable, LibRoutineOutputVariable):
    """Write-only symbolic routine argument."""

    ROLE = "OUTPUT"


class PlainInOutVariable(PlainDummyVariable, LibRoutineInOutVariable):
    """Read-write symbolic routine argument."""

    ROLE = "INOUT"


class PlainBufferVariable(PlainInOutVariable, LibRoutineBufferVariable):
    """Buffer-backed symbolic routine argument."""

    ROLE = "BUFFER"


class PlainConstant(PlainLibRoutineVariable, LibRoutineConstant):
    """Constant definition for symbolic output."""

    def get_definition_lines(self):
        dtype = self.lookup_dtype(self._dtype)
        if self.is_scalar:
            yield f"CONSTANT {dtype} {self._name} = {self.value}"
            return

        values = [
            int(v) if self.dtype[0] == "i" else float(v) for v in self.values
        ]
        prefix = f"CONSTANT {dtype} {self._name}[{self.size}] = ["
        suffix = "]"
        for line in multiline_iterable(
            values,
            separator=", ",
            max_line_length=100,
            indent="",
            extra_indent="",
            linebreak="",
            prefix=prefix,
            suffix=suffix,
            prefix_suffix_lines=False,
        ):
            yield line


class PlainAssignmentStatementLine(AssignmentStatementLine):
    """Plain-text assignment statement."""

    BLUEPRINT = "{target} = {expression}"


class PlainCommentLine(CommentLine):
    """Plain-text comment line."""

    COMMENT_PREFIX = "# "


class PlainRoutineCallContainer(RoutineCallContainer):
    """Symbolic routine call representation."""

    def get_call_string(self):
        return f"CALL {self.get_call_name()}({', '.join(self.get_args_list())})"


class PlainMultiFrameExpandContainer(MultiFrameExpandContainer):
    """Symbolic ``DO`` block for multiframe expansion."""

    INDENT_BODY = True
    DEFAULT_LOCAL_VARIABLE_CLASS = PlainLocalVariable

    def generate_head_containers(self):
        if self._multiframe_variable is not None:
            yield from self.codelines_from_text(
                f"DO {self._multiframe_variable.expr()} FROM {self._min_value} TO {self._max_value - 1}"
            )

    def generate_foot_containers(self):
        if self._multiframe_variable is not None:
            yield from self.codelines_from_text("END DO")


class PlainIntCombineExpandContainer(IntCombineExpandContainer):
    """Symbolic combined multiframe expansion."""

    INDENT_BODY = True
    DEFAULT_LOCAL_VARIABLE_CLASS = PlainLocalVariable

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(
            f"{self._multiframe_variable.local} = {self._second.local} * {self._first.max_value} + {self._first.local}"
            + (
                f" + {self._multiframe_variable.min_value}"
                if self._multiframe_variable.min_value
                else ""
            )
        )
        yield from self.codelines_from_text(
            f"IF {self._multiframe_variable.local} < {self._multiframe_variable.max_value} THEN"
        )

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text("END IF")


class PlainRoutineContainer(RoutineContainer):
    """Function-like container for symbolic plain-text output."""

    INDENT_BODY = True
    INPUT_VARIABLE_CLASS = PlainInputVariable

    def get_signature(self):
        call_args = [
            variable.as_argument_declaration()
            for variable in self.get_argument_variables()
        ]
        return f"FUNCTION {self.name}({', '.join(call_args)})"

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(self.get_signature())

    def generate_prmb_containers(self, **kwargs):
        yield from self.comment_from_text("IN/OUT/INOUT")
        for variable in self.get_inout_variables():
            yield DefinitionLines(variable, context=self.context, **kwargs)
        yield from self.codelines_from_text("")
        local_variables = list(self.get_local_variables())
        if local_variables:
            yield from self.comment_from_text("LOCAL")
            for variable in local_variables:
                yield DefinitionLines(variable, context=self.context, **kwargs)
            yield from self.codelines_from_text("")

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text(f"END FUNCTION {self.name}")


class PlainAccumulateStatementLine(AccumulateStatementLine):
    """Plain-text accumulation statement."""

    UPDATE_BLUEPRINT = "{target} += {expression}"


class PlainAffineContainer(PlainAccumulateStatementLine):
    """Affine update ``y += a * x + b``."""

    EXPRESSION_BLUEPRINT = "{a_value} * {x_expression} + {b_value}"

    def __init__(self, y, a, x, b, *, context, **params):
        super().__init__(
            target=y,
            value_dict={
                "target": y,
                "x_expression": x,
                "a_value": a,
                "b_value": b,
            },
            context=context,
            **params,
        )
        self.requires(y)
        self.requires(x)
        self.requires(a)
        self.requires(b)


class PlainBilinearContainer(PlainAccumulateStatementLine):
    """Bilinear update ``y += a * u * v``."""

    EXPRESSION_BLUEPRINT = "{a_value} * {u_expression} * {v_expression}"

    def __init__(self, y, a, u, v, *, context, **params):
        super().__init__(
            target=y,
            value_dict={
                "target": y,
                "u_expression": u,
                "v_expression": v,
                "a_value": a,
            },
            context=context,
            **params,
        )
        self.requires(y)
        self.requires(u)
        self.requires(v)
        self.requires(a)


class PlainImportContainer(ImportContainer):
    """Symbolic import statement container."""

    INDENT_BODY = False

    def construct_code_lines(self, **_):
        names = ", ".join(routine.name for routine in self.routines)
        yield f"IMPORT {names} FROM {self.library.libname}"


class PlainImportSectionContainer(ImportSectionContainer):
    """Plain-text import section."""

    def compose_call_name(self, importable, library):
        if library is None:
            return importable.name
        return f"{library.libname}.{importable.name}"


class PlainBuilder(Builder, identifier="PLAIN"):
    """Builder emitting symbolic plain-text code."""

    _assignment_class = PlainAssignmentStatementLine

    def create_libroutine_variable(
        self,
        *,
        name,
        dtype,
        status,
        size,
        assignment=None,
        namespace=None,
        **kwargs,
    ):
        if status & LibRoutineVariable.STATUS_BUFFER:
            return PlainBufferVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        status = status & 3
        if status == LibRoutineVariable.STATUS_INPUT:
            return PlainInputVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        if status == LibRoutineVariable.STATUS_OUTPUT:
            return PlainOutputVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        if status == LibRoutineVariable.STATUS_INOUT:
            return PlainInOutVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        return super().create_libroutine_variable(
            name=name,
            dtype=dtype,
            status=status,
            size=size,
            namespace=namespace,
            **kwargs,
        )

    def as_numeric(self, variable):
        return PlainNumeric(variable)

    def lookup_status(self, status):
        if status.upper().strip() == "OUT":
            status = "INOUT"
        return super().lookup_status(status)

    def check_relevance(self, *variables, hook=None):
        remember = []
        for var in variables:
            if var is None:
                return False
            if isinstance(var, LibRoutineVariable):
                remember.append(var)
                continue
            if abs(var) < ZERO_TOL:
                return False
        if hook is not None:
            for var in remember:
                hook.requires(var)
        return True

    def handle_affine_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        alpha = instruction_dict.get("alpha", 1)
        beta = instruction_dict.get("beta", 0)

        x_var_real = context.namespace.find_assignment(
            type(src0), "real", exception_not_existing=False
        )
        x_var_imag = context.namespace.find_assignment(
            type(src0), "imag", exception_not_existing=False
        )
        y_var_real = context.namespace.find_assignment(
            type(tgt0), "real", exception_not_existing=False
        )
        y_var_imag = context.namespace.find_assignment(
            type(tgt0), "imag", exception_not_existing=False
        )

        x_var_offs = src0.offsets
        y_var_offs = tgt0.offsets
        a_real = self.wrap_lrv(alpha.real)
        a_imag = self.wrap_lrv(alpha.imag)
        b_real = self.wrap_lrv(beta.real)
        b_imag = self.wrap_lrv(beta.imag)

        combinations = [
            (y_var_real, a_real, x_var_real, b_real, 1),
            (y_var_real, a_imag, x_var_imag, b_real, -1),
            (y_var_imag, a_real, x_var_imag, b_imag, 1),
            (y_var_imag, a_imag, x_var_real, b_imag, 1),
        ]
        hook = HookContainer(context=context)
        first_real = True
        first_imag = True
        for y_var, a_val, x_var, b_val, sign in combinations:
            if y_var is y_var_real and not first_real:
                b_val = self.wrap_lrv(0.0)
            if y_var is y_var_imag and not first_imag:
                b_val = self.wrap_lrv(0.0)
            ret = self.check_relevance(y_var, a_val, x_var, b_val, hook=hook)
            if ret:
                yield PlainAffineContainer(
                    y_var.at(*y_var_offs),
                    a_val * sign,
                    x_var.at(*x_var_offs),
                    b_val,
                    context=context,
                )
                if y_var is y_var_real:
                    first_real = False
                else:
                    first_imag = False

        yield CodeLine("", context=context)

    def handle_bilinear_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        src1 = instruction_dict.get("src1")
        alpha = instruction_dict.get("alpha")

        u_var_real = context.namespace.find_assignment(
            type(src0), "real", exception_not_existing=False
        )
        u_var_imag = context.namespace.find_assignment(
            type(src0), "imag", exception_not_existing=False
        )
        v_var_real = context.namespace.find_assignment(
            type(src1), "real", exception_not_existing=False
        )
        v_var_imag = context.namespace.find_assignment(
            type(src1), "imag", exception_not_existing=False
        )
        y_var_real = context.namespace.find_assignment(
            type(tgt0), "real", exception_not_existing=False
        )
        y_var_imag = context.namespace.find_assignment(
            type(tgt0), "imag", exception_not_existing=False
        )

        u_var_offs = src0.offsets
        v_var_offs = src1.offsets
        y_var_offs = tgt0.offsets
        a_real = self.wrap_lrv(alpha.real)
        a_imag = self.wrap_lrv(alpha.imag)

        hook = HookContainer(context=context)

        combinations = [
            (y_var_real, a_real, u_var_real, v_var_real, +1),
            (y_var_real, a_real, u_var_imag, v_var_imag, -1),
            (y_var_real, a_imag, u_var_imag, v_var_real, -1),
            (y_var_real, a_imag, u_var_real, v_var_imag, -1),
            (y_var_imag, a_real, u_var_imag, v_var_real, +1),
            (y_var_imag, a_real, u_var_real, v_var_imag, +1),
            (y_var_imag, a_imag, u_var_real, v_var_real, +1),
            (y_var_imag, a_imag, u_var_imag, v_var_imag, -1),
        ]

        for y_var, a_val, u_var, v_var, sign in combinations:
            ret = self.check_relevance(y_var, a_val, u_var, v_var, hook=hook)
            if ret:
                yield PlainBilinearContainer(
                    y_var.at(*y_var_offs),
                    sign * a_val,
                    u_var.at(*u_var_offs),
                    v_var.at(*v_var_offs),
                    context=context,
                )

        yield CodeLine("", context=context)

    def create_external_array(self, *args, context, **kwargs):
        return Builder.create_external_array(
            self,
            *args,
            context=context,
            local_class=PlainLocalVariable,
            constant_class=PlainConstant,
        )


class PlainComputeResource(ComputeResource):
    """Plain-text resource using symbolic loop expansion."""

    def create_mfe_container(
        self,
        *,
        context,
        local_variable_capture,
        name=None,
        loop_container=None,
        loop_capture=None,
    ) -> None | MultiFrameExpandContainer:
        del name, loop_container, loop_capture
        return PlainMultiFrameExpandContainer(
            context=context,
            local_variable_capture=local_variable_capture,
        )

    def create_combine_container(
        self,
        first,
        second,
        *,
        context,
        local_variable_capture,
        name=None,
        loop_container=None,
        loop_capture=None,
    ) -> None | MultiFrameExpandContainer:
        del name, loop_container, loop_capture
        return PlainIntCombineExpandContainer(
            first,
            second,
            context=context,
            local_variable_capture=local_variable_capture,
        )


class PlainLibRoutine(LibRoutine):
    """Plain-text routine descriptor."""


class PlainLibrary(Library):
    """Library emitting symbolic plain-text output."""

    BACKEND_IDENTIFIER = "plain"
    FILEENDING = "txt"
    INDENTSTR = "\t"
    LIBROUTINE_CLASS = PlainLibRoutine
    IMPORTLINE_CLASS = PlainImportContainer
    DEFAULT_BUILDER = PlainBuilder
    DEFAULT_CONTAINER_CLASS = PlainRoutineContainer

    def __init__(
        self,
        plain_name,
        build_hash=None,
        resource=None,
        configuration=None,
        general_configuration=None,
    ):
        if resource is None:
            resource = PlainComputeResource("PlainResource")
        self._initialize_library_state(
            plain_name=plain_name,
            build_hash=build_hash,
            resource=resource,
            import_section_class=PlainImportSectionContainer,
            backend_configuration=configuration,
            general_configuration=general_configuration,
        )

    def generate_head_containers(self, **_):
        yield from self.codelines_from_text(f"LIBRARY {self.libname}")
        yield from self.codelines_from_text("")

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text(f"END LIBRARY {self.libname}")

    def generate_prmb_containers(self, **_):
        imports = list(self.import_capture.list_imports())
        if imports:
            for library, routines in imports:
                yield PlainImportContainer(
                    library, routines, context=self.context
                )
            yield from self.codelines_from_text("")

        constants = list(self.definition_capture.captured)
        if constants:
            for variable in constants:
                for line in variable.get_definition_lines():
                    yield from self.codelines_from_text(line)
            yield from self.codelines_from_text("")

    def generate_clsg_containers(self, **_):
        return
        yield

    def get_to_zero_support_routine(self, dtype):
        """Return the external helper routine used to reset one buffer."""
        routine_name = f"phoenix_to_zero_{dtype}"
        existing = self[routine_name]
        if existing is not None:
            return existing
        zero_value = PlainLocalVariable(name="tmp", dtype=dtype, no_entry=True).get_zero_value()
        code = [
            f"ROUTINE {routine_name}(buffer, size)",
            f"\tZERO BUFFER[{dtype.upper()}] WITH {zero_value} UP TO size",
            "END ROUTINE",
        ]
        return self._register_manual_routine(
            routine_name,
            code=code,
            arguments=[
                {
                    "name": "buffer",
                    "dtype": dtype,
                    "size": 1,
                    "status": "INOUT",
                    "assignment": ("buffer", "data"),
                },
                {
                    "name": "size",
                    "dtype": "i32",
                    "status": "IN",
                },
            ],
        )

    def get_codelines(self, indent=0):
        yield from self.get_codelines_head(indent=indent)
        yield from self.get_codelines_prmb(indent=indent)
        yield from self.iter_routine_codelines(indent=indent)
        yield from self.get_codelines_clsg(indent=indent)
        yield from self.get_codelines_foot(indent=indent)


PlainBuilder.set_instruction_class_handler(
    AffineOperationInstruction, PlainBuilder.handle_affine_instruction
)
PlainBuilder.set_instruction_class_handler(
    BiLinearOperationInstruction, PlainBuilder.handle_bilinear_instruction
)

PlainRoutineContainer.set_comment_class(PlainCommentLine)
PlainBuilder.set_comment_class(PlainCommentLine)
PlainBuilder.set_routinecall_class(PlainRoutineCallContainer)
