"""
#autogenerated#header#do#not#modify############################################
#
# File:        f2py_utils.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   24/10/2025
# Last Update: 12/11/2025, 17:56
# Version:     0.1.7
#
#################################################end#of#autoheader#do#not#modify


"""

__doc__ = """Helpers for preprocessing and loading Fortran code through f2py."""


import tempfile
import hashlib
import importlib
import importlib.util
import importlib.machinery
import subprocess
import sys
import shutil
from pathlib import Path


def preprocess_f90(
    file,
    directory="./",
    output_file_name: str = None,
    options: str = None,
) -> Path:
    """preprocess the file and write the result into the directory"""

    # default output filename
    if output_file_name is None:
        output_file_name = f"tmp_{file}".replace(".F90", ".f90")

    # create directory path
    target = Path(directory) / output_file_name

    # compose the command
    cmd = ["gfortran", "-cpp", "-E", "-P", file]

    if options is not None:
        if isinstance(options, list):
            cmd += options
        elif isinstance(options, str):
            cmd += [options]
        else:
            raise TypeError("Invalid options type. Expected list or string.")

    # pipe output to target
    with open(target, "w") as outfile:
        subprocess.run(cmd, check=True, stdout=outfile)
    return target


def copy_file(file, directory):
    """copy a file to another directory. Returns copied path"""
    target = Path(directory) / file
    cmd = ["cp", file, target]
    subprocess.run(cmd, check=True)
    return target


def file_signature(path: str | Path) -> str:
    """Compute a combined hash of file content and modification time."""
    path = Path(path)
    h = hashlib.sha1()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    # include timestamp to rebuild if file was touched
    h.update(str(path.stat().st_mtime).encode())
    return h.hexdigest()


def compile_fortran_module(
    modulename,
    *src_files,
    f90flags: str = "",
    opt: str = "-O3",
    pp_options: str | str = None,
    include: list = None,
    delete=True,
    force_recompile=False,
):
    """compile a fortran module in a file"""

    # check if the file is there already. Make a hash that is unique to
    # the combination of flags and the source checksum and date
    combined_signature = (
        "".join(file_signature(f) for f in src_files)
        + (f90flags or "")
        + (opt or "")
        + (pp_options or "")
    )
    if include:
        combined_signature += "".join(file_signature(f) for f in include)

    build_hash = hashlib.sha1(combined_signature.encode()).hexdigest()[:12]
    cached_so_name = f"{modulename}_{build_hash}.cpython-{sys.version_info[0]}{sys.version_info[1]}-x86_64-linux-gnu.so"
    cached_so_path = Path.cwd() / cached_so_name

    if (not cached_so_path.exists()) or force_recompile:
        # need to rebuild.

        # preprocess everything to create a clean copy
        preprocessed_src_files = []

        # use temporary directory to keep the working dir clean
        with tempfile.TemporaryDirectory(delete=delete) as tmpdir:
            # handle every file
            if include is not None:
                for file in include:
                    copy_file(file, tmpdir)
            for file in src_files:
                preprocessed_src_files.append(
                    preprocess_f90(
                        file,
                        directory=tmpdir,
                        options=pp_options,
                    )
                )

            # Run f2py via subprocess
            cmd = [
                sys.executable,
                "-m",
                "numpy.f2py",
                "-c",
                "-m",
                modulename,
            ]

            # add all the file names. Cast to string to be sure
            cmd += [str(file) for file in preprocessed_src_files]

            # optimization flags
            if opt:
                cmd += [f"--opt='{opt}'"]

            # compiler flags
            if f90flags:
                cmd += [f"--f90flags='{f90flags}'"]

            cmd += ["-lgomp"]

            # execute compilation
            subprocess.run(
                cmd,
                check=True,
                cwd=tmpdir,
                # stdout=subprocess.PIPE,  # remove stdout from python out
            )

            # Locate the compiled shared object (.so / .pyd)
            sofile = next(Path(tmpdir).glob(f"{modulename}*.so"))

            for old_so in Path.cwd().glob(f"{modulename}_*.so"):
                try:
                    old_so.unlink()
                except Exception as e:
                    print(f"Warning: could not remove {old_so}: {e}")

            # Copy compiled .so to cache location
            shutil.copy(sofile, cached_so_path)

    loader = importlib.machinery.ExtensionFileLoader(
        modulename, str(cached_so_path)
    )
    spec = importlib.util.spec_from_loader(loader.name, loader)
    mod = importlib.util.module_from_spec(spec)
    loader.exec_module(mod)
    return mod
