"""
#autogenerated#header#do#not#modify############################################
#
# File:        fortran_pywrapper_library.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   13/03/2026
# Last Update: 10/04/2026, 13:40
# Version:     0.1.3
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """Python wrapper layer around generated Fortran and f2py libraries."""

from ..pywrapper_library import PyWrapperLibraryBase, WrapperBase


class FortranWrapper(WrapperBase):
    """Thin wrapper around f2py-exported Python callables."""


class FortranPyWrapperLibrary(PyWrapperLibraryBase):
    """Python wrapper library for Fortran90 libraries."""

    WRAPPER_CLASS = FortranWrapper

    @classmethod
    def from_compiled_hash(
        cls,
        library_class,
        plain_name,
        build_hash,
        *,
        wrapper_lib=None,
        **library_kwargs,
    ):
        if wrapper_lib is None:
            preview_library = library_class(
                plain_name,
                build_hash=build_hash,
                **library_kwargs,
            )
            wrapper_lib = preview_library.import_python_module()
        return super().from_compiled_hash(
            library_class,
            plain_name,
            build_hash,
            wrapper_lib=wrapper_lib,
            **library_kwargs,
        )

    def resolve_wrapper_callable(self, libroutine_name, _libroutine):
        if hasattr(self.wrapper_lib, libroutine_name):
            return getattr(self.wrapper_lib, libroutine_name)
        module_name = getattr(self.wrapped_library, "libname", None)
        if module_name and hasattr(self.wrapper_lib, module_name):
            module_object = getattr(self.wrapper_lib, module_name)
            if hasattr(module_object, libroutine_name):
                return getattr(module_object, libroutine_name)
        raise AttributeError(
            f"could not resolve Fortran routine {libroutine_name!r} in "
            f"{type(self.wrapper_lib).__name__}"
        )


# Backwards compatibility with the previous single-module implementation.
Wrapper = FortranWrapper
PyWrapperLibrary = FortranPyWrapperLibrary
