"""
#autogenerated#header#do#not#modify############################################
#
# File:        fortran_builder.py
# Author:      Matthias Kost
# Contact:     matthias.kost@uni-ulm.de
# Generated:   01/04/2025
# Last Update: 31/03/2026, 18:02
# Version:     0.1.204
#
#################################################end#of#autoheader#do#not#modify


"""

from __future__ import annotations

__doc__ = """
Fortran90 backend generation and f2py-oriented build support.

The Fortran backend lowers symbolic Phoenix routines into module-based Fortran
source, preserving builder-driven instruction lowering while adapting argument
status, array indexing, and routine signatures to Fortran conventions. The
module also provides makefile targets for native shared-library builds and for
``f2py`` Python-extension builds used by the Fortran wrapper path.
"""

import os
import shlex
import sys
import importlib.util
from pathlib import Path

from ...backend_config import Configuration
from .fortran_atomic import (
    register_fortran_atomic_handlers,
)
from ...builder import Builder

from ...computeresource import ComputeResource

from ...codecontainer import (
    CodeLine,
    CommentLine,
    RoutineContainer,
    MultiFrameExpandContainer,
    RoutineCallContainer,
    AccumulateStatementLine,
    HookContainer,
    ImportContainer,
    ImportSectionContainer,
    IntCombineExpandContainer,
)

from ...libroutinevar import (
    LibRoutineBufferVariable,
    LibRoutineVariable,
    LibRoutineInputVariable,
    LibRoutineOutputVariable,
    LibRoutineInOutVariable,
    LibRoutineLocalVariable,
    LibRoutineConstant,
    Numeric,
)


# from ...libroutine import LibRoutine
from ...library import Library, LibRoutine
from ...makefile import MFTObject, MFTSharedLibrary, MFTSpecial

from ...instruction import (
    AffineOperationInstruction,
    BiLinearOperationInstruction,
)

from ....toolbox.logger import GLOBAL_LOGGER

from ....aux import configured_zero_tol, multiline_iterable

_GENERAL_CONFIG = Configuration.general()
ZERO_TOL = configured_zero_tol()
GLOBAL_LOGGER.set_loglevel(
    _GENERAL_CONFIG.get_nested("logging", "level", default="DEBUG")
)
GLOBAL_LOGGER.add_note(
    """
    This is the first version of the FORTRAN builder.
    The supported data is compatible to numpy. At this point I can
    start to design how call patterns are implemented and how they
    come from the signature of the ADAAs.
    Also a basic compilation call is required, let's see how that's
    gonna play out.
    """
)

GLOBAL_LOGGER.log_to_stdout(
    _GENERAL_CONFIG.get_nested("logging", "stdout", default=False)
)


class FortranMFTObject(MFTObject):
    """Fortran object-file target with a Fortran compiler blueprint."""

    def __init__(
        self,
        name,
        *,
        source,
        dependencies=None,
        compiler=None,
        flags=None,
        silent=None,
        configuration=None,
    ):
        super().__init__(
            name,
            source=source,
            dependencies=dependencies,
            silent=silent,
        )
        self._configuration = (
            Configuration.for_backend("fortran")
            if configuration is None
            else configuration.clone()
        )
        if compiler is None:
            compiler = self._configuration.get_nested(
                "executables", "compiler", default="gfortran"
            )
        self._compiler = compiler
        self._flags = [
            *self._configuration.get_nested("flags", "object", default=[]),
            *(flags or []),
            *self._configuration.get_nested(
                "flags", "extra_object", default=[]
            ),
        ]

    def generate(self, *flags):
        summary = self.get_dependency_summary()
        direct_dependencies = list(self.dependencies)
        if not direct_dependencies:
            raise ValueError(
                f"{type(self).__name__} expects one direct source dependency."
            )
        source_files = list(
            direct_dependencies[0].get_compile_input_contributions()
        )
        if len(source_files) != 1:
            raise ValueError(
                f"{type(self).__name__} expects exactly one compile input."
            )
        cmd_flags = [
            *self._flags,
            *flags,
            *summary["compile_flags"],
            self._join_flags(
                self._configuration.get_nested(
                    "prefixes", "include", default="-I"
                ),
                summary["include_dirs"],
            ),
        ]
        cmd_flags = " ".join(flag for flag in cmd_flags if flag)
        yield (
            f"{self._compiler} -c {source_files[0]} -o {self.target_name()}"
            + (f" {cmd_flags}" if cmd_flags else "")
        )

    def get_include_dir_contributions(self):
        objdir = Path(self.target_name()).parent
        if str(objdir) not in ("", "."):
            yield str(objdir)


class FortranMFTSharedLibrary(MFTSharedLibrary):
    """Fortran shared-library target with a Fortran linker blueprint."""

    def __init__(
        self,
        name,
        dependencies=None,
        *,
        linker=None,
        flags=None,
        silent=None,
        configuration=None,
    ):
        super().__init__(name, dependencies=dependencies, silent=silent)
        self._configuration = (
            Configuration.for_backend("fortran")
            if configuration is None
            else configuration.clone()
        )
        if linker is None:
            linker = self._configuration.get_nested(
                "executables", "linker", default="gfortran"
            )
        self._linker = linker
        self._flags = [
            *self._configuration.get_nested("flags", "shared", default=[]),
            *(flags or []),
            *self._configuration.get_nested(
                "flags", "extra_shared", default=[]
            ),
        ]

    def generate(self, *flags):
        summary = self.get_dependency_summary()
        link_inputs = " ".join(summary["link_inputs"])
        cmd_flags = [
            *self._flags,
            *flags,
            *summary["link_flags"],
            self._join_flags(
                self._configuration.get_nested(
                    "prefixes", "library", default="-L"
                ),
                summary["library_dirs"],
            ),
        ]
        cmd_flags = " ".join(flag for flag in cmd_flags if flag)
        yield (
            f"{self._linker} -o {self.target_name()} {link_inputs}"
            + (f" {cmd_flags}" if cmd_flags else "")
        )


class FortranMFTPythonModule(MFTSpecial):
    """`f2py`-based Python extension target for generated Fortran code."""

    def __init__(
        self,
        name,
        *,
        source,
        module_name,
        output_dir,
        dependencies=None,
        f2py_command=None,
        python_command=None,
        silent=None,
        configuration=None,
    ):
        dependencies = [source, *(dependencies or [])]
        super().__init__(name, dependencies=dependencies, silent=silent)
        self._module_name = module_name
        self._output_dir = output_dir
        self._configuration = (
            Configuration.for_backend("fortran")
            if configuration is None
            else configuration.clone()
        )
        self._f2py_command = f2py_command or self._default_f2py_command()
        self._python_command = python_command or self._configuration.get_nested(
            "executables", "python", default="python3"
        )

    def _default_f2py_command(self):
        configured = os.environ.get(
            "F2PYEXEC"
        ) or self._configuration.get_nested("executables", "f2py", default=None)
        if configured:
            return shlex.quote(configured)
        executable_path = Path(sys.executable).resolve()
        for candidate_name in ("f2py", "f2py3"):
            candidate = executable_path.with_name(candidate_name)
            if candidate.exists():
                return shlex.quote(str(candidate))
        return f"{shlex.quote(sys.executable)} -m {shlex.quote('numpy.f2py')}"

    def generate(self, *flags):
        summary = self.get_dependency_summary()
        direct_dependencies = list(self.dependencies)
        if not direct_dependencies:
            raise ValueError(
                f"{type(self).__name__} expects one direct source dependency."
            )
        source_files = list(
            direct_dependencies[0].get_compile_input_contributions()
        )
        if len(source_files) != 1:
            raise ValueError(
                f"{type(self).__name__} expects exactly one compile input."
            )
        source_name = Path(source_files[0]).name
        compile_flags = [
            *self._configuration.get_nested(
                "flags", "f2py_compile", default=[]
            ),
            *summary["compile_flags"],
            *self._configuration.get_nested(
                "flags", "extra_f2py_compile", default=[]
            ),
            *flags,
        ]
        link_flags = [*summary["link_flags"]]
        include_flags = self._join_flags("-I", summary["include_dirs"])
        library_flags = self._join_flags("-L", summary["library_dirs"])
        link_inputs = " ".join(summary["link_inputs"])
        env_parts = []
        if compile_flags:
            flags_string = " ".join(flag for flag in compile_flags if flag)
            if flags_string:
                env_parts.append(f'FFLAGS="{flags_string} $${{FFLAGS}}"')
                env_parts.append(f'FCFLAGS="{flags_string} $${{FCFLAGS}}"')
        ld_parts = [
            " ".join(flag for flag in link_flags if flag),
            library_flags,
            link_inputs,
        ]
        ldflags_string = " ".join(part for part in ld_parts if part)
        if ldflags_string:
            env_parts.append(f'LDFLAGS="{ldflags_string} $${{LDFLAGS}}"')
        quoted_output_dir = shlex.quote(str(Path(self._output_dir).resolve()))
        module_name = shlex.quote(self._module_name)
        command = [
            f"cd {quoted_output_dir} &&",
            *env_parts,
            self._f2py_command,
            "-c",
            shlex.quote(source_name),
            "-m",
            module_name,
        ]
        if include_flags:
            command.append(include_flags)
        yield " ".join(command)
        yield (
            f"{self._python_command} -c "
            f'"from pathlib import Path; Path({self.target_name()!r}).touch()"'
        )


class FortranNumeric(Numeric):
    """F90 version of a numeric"""


class FortranLibRoutineVariable(LibRoutineVariable):
    """LibRoutineVariable F90 Base class"""

    def get_zero_value(self):
        if self.dtype == "f64":
            return "0.0d0"
        if self.dtype == "f32":
            return "0.0"
        if self.dtype == "i64":
            return "0_8"
        if self.dtype == "i32":
            return "0"
        return "0"

    def get_definition_lines(self) -> str:
        """create the line that defines the variable"""
        dimension_str = ""
        if not self.is_scalar:
            dimension_str = f", dimension({self._size})"
        yield f"{self.lookup_dtype(self._dtype)}{dimension_str} :: {self._name}"

    def lookup_dtype(self, dtype):
        match dtype:
            case "f64":
                return "double precision"
            case "f32":
                return "real"
            case "i64":
                return "integer(8)"
            case "i32":
                return "integer"
        raise ValueError(f"Unknown dtype: {dtype}")

    def at(self, *offsets, **kwargs):
        """Fortran variables start at 1, not 0"""
        return super().at(1, *offsets, **kwargs)

    def expr_at(self, offset_string):
        return f"{self.name}({offset_string})"

    def generate_tozero_lines(self):
        zero_value = self.get_zero_value()
        if self.is_scalar:
            yield f"{self.expr()} = {zero_value}"
            return
        yield f"{self.name}(:) = {zero_value}"


class FortranLocalVariable(FortranLibRoutineVariable, LibRoutineLocalVariable):
    """Local variable, not initialized with intent parameter"""

    def get_definition_lines(self) -> str:
        """create the line that defines the variable"""
        dimension_str = ""
        if not self.is_scalar:
            dimension_str = f", dimension({self._size})"
        yield f"{self.lookup_dtype(self._dtype)}{dimension_str} :: {self._name}"


class FortranDummyVariable(FortranLibRoutineVariable):
    """Dummy variable, used as argument place holder in routines"""

    _intent = None

    def get_definition_lines(self) -> str:
        """create the line that defines the variable"""
        dimension_str = ""
        intent = self.lookup_intent(type(self)._intent)
        intent_str = f", intent({intent})"
        if not self.is_scalar:
            dimension_str = f", dimension({self._size})"
        yield f"{self.lookup_dtype(self._dtype)}{intent_str}{dimension_str} :: {self._name}"

    def lookup_intent(self, intent):
        """lookup the INTENT keyword in definitions"""
        assert intent is not None
        if intent == "RO":
            return "IN"
        if intent == "WO":
            return "OUT"
        if intent == "RW":
            return "INOUT"
        raise ValueError(f"Unknown intent: {intent}")


class FortranInputVariable(FortranDummyVariable, LibRoutineInputVariable):
    """FortranInputVariable, has intent(IN)"""

    _intent = "RO"


class FortranOutputVariable(FortranDummyVariable, LibRoutineOutputVariable):
    """FortranOutputVariable, has intent(OUT)"""

    _intent = "WO"


class FortranInOutVariable(FortranDummyVariable, LibRoutineInOutVariable):
    """FortranInOutVariable, has intent(INOUT)"""

    _intent = "RW"


class FortranBufferVariable(FortranInOutVariable, LibRoutineBufferVariable):
    """Fortran buffer variable with intent(INOUT)."""


class FortranConstant(FortranLibRoutineVariable, LibRoutineConstant):
    """
    Constant is initialized with the parameter keyword in Fortran and its value is set
    upon initialisation
    """

    def get_definition_lines(self) -> str:
        """create the line that defines the variable"""
        # dimension_str = ""
        # if not self.is_scalar:
        #     dimension_str = f", dimension({self._size})"
        if self.is_scalar:
            yield f"{self.lookup_dtype(self._dtype)}, parameter :: {self._name} = {self.value}"
            return
        codeline = f"{self.lookup_dtype(self._dtype)}, parameter :: {self._name}({self.size}) = "
        prefix = "(/"
        suffix = "/)"
        conv = float
        if self.dtype[0] == "i":
            conv = int
        for thisline in multiline_iterable(
            [conv(value) for value in self.values],
            separator=", ",
            max_line_length=100,
            indent="",
            extra_indent="  ",
            linebreak=" &",
            prefix=codeline + prefix,
            suffix=suffix,
            prefix_suffix_lines=False,
        ):
            yield thisline


###############################################################################
#
# .oPYo.                   o            o
# 8    8                   8
# 8       .oPYo.  odYo.   o8P  .oPYo.  o8  odYo.  .oPYo.  oPYo.  .oPYo.
# 8       8    8  8' `8    8   .oooo8   8  8' `8  8oooo8  8  `'  Yb..
# 8    8  8    8  8   8    8   8    8   8  8   8  8.      8        'Yb.
# `YooP'  `YooP'  8   8    8   `YooP8   8  8   8  `Yooo'  8      `YooP'
# :.....: :.....: ..::.. ::..: :.....: :.. ..::.. :.....: ..:::: :.....:
# ::::::: ::::::: :::::: ::::: ::::::: ::: :::::: ::::::: :::::: :::::::
# ::::::: ::::::: :::::: ::::: ::::::: ::: :::::: ::::::: :::::: :::::::
###############################################################################


class FortranRoutineCallContainer(RoutineCallContainer):
    """F90 version of a RoutineCallContainer"""

    def get_call_string(self):
        """generate the call string"""
        return f"call {self.get_call_name()}({', '.join(self.get_args_list())})"


class FortranCommentLine(CommentLine):
    """F90 version of CommentLine. Sets comment symbol to !"""

    COMMENT_PREFIX = "! "


class FortranMultiFrameExpandContainer(MultiFrameExpandContainer):
    """F90 version of MultiFrameExpandContainer. In this case, this is a DO-loop."""

    INDENT_BODY = True
    DEFAULT_LOCAL_VARIABLE_CLASS = FortranLocalVariable

    def generate_head_containers(self):
        if self._multiframe_variable is not None:
            yield from self.codelines_from_text(
                f"DO {self._multiframe_variable.expr()} = {self._min_value}, {self._max_value - 1}"
            )

    def generate_foot_containers(self):
        if self._multiframe_variable is not None:
            yield from self.codelines_from_text(
                f"END DO  ! {self._multiframe_variable.expr()}={self._min_value}...{self._max_value - 1}"
            )


class FortranIntCombineExpandContainer(IntCombineExpandContainer):
    """Recombine split integer loop indices for Fortran code emission."""

    INDENT_BODY = True
    DEFAULT_LOCAL_VARIABLE_CLASS = FortranLocalVariable

    def generate_head_containers(self, **_):
        # yield from self.codelines_from_text(
        #     f"! combine {self._variable.local}, {self._first.local} {self._second.local} {self._offset}"
        # )
        yield from self.codelines_from_text(
            f"{self._multiframe_variable.local} = {self._second.local} * {self._first.max_value} + {self._first.local}"
            + (
                f" + {self._multiframe_variable.min_value}"
                if self._multiframe_variable.min_value
                else ""
            )
        )
        yield from self.codelines_from_text(
            f"IF ({self._multiframe_variable.local} .LT. {self._multiframe_variable.max_value}) THEN"
        )

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text("END IF")


class FortranRoutineContainer(RoutineContainer):
    """F90 version of a RoutineContainer"""

    INDENT_BODY = True
    INPUT_VARIABLE_CLASS = FortranInputVariable

    def generate_head_containers(self, **_):
        call_args = (var.as_argument() for var in self.get_argument_variables())
        yield FortranCommentLine(f"Subroutine: {self.name}", context=self.context)
        yield from self.codelines_from_text(
            f"SUBROUTINE {self.name}({', '.join(call_args)})"
        )

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text(f"END SUBROUTINE {self.name}")


class FortranAccumulateStatementLine(AccumulateStatementLine):
    """Implement, how accumulate works in FORTRAN"""

    UPDATE_BLUEPRINT = "{target} = {target} + {expression}"


class FortranAffineContainer(FortranAccumulateStatementLine):
    """Affine update operation y += a * x + b"""

    INDENT_BODY = False
    # BLUEPRINTS = {
    #     "ip": "{y_expression} = {y_expression} + {a_value} * {x_expression} + {b_value}",
    #     "av": "{y_expression} = {a_value} * {x_expression} + {b_value}",
    # }
    EXPRESSION_BLUEPRINT = "{a_value} * {x_expression} + {b_value}"

    # def _mode_select(self, **params):

    def __init__(self, y, a, x, b, *, context, **params):
        super().__init__(
            target=y,
            value_dict={
                "target": y,
                "x_expression": x,
                "a_value": a,
                "b_value": b,
            },
            context=context,
            **params,
        )
        self.requires(y)
        self.requires(x)
        self.requires(a)
        self.requires(b)


class FortranBilinearContainer(FortranAccumulateStatementLine):
    """Bilinear update operation z += a * x * y"""

    INDENT_BODY = False
    # BLUEPRINTS = {
    #     "ip": "{y_expression} = {y_expression} + {a_value} * {u_expression} * {v_expression}",
    #     "av": "{y_expression} = {a_value} * {u_expression} * {v_expression}",
    # }
    EXPRESSION_BLUEPRINT = "{a_value} * {u_expression} * {v_expression}"

    # def _mode_select(self, **params):

    def __init__(self, y, a, u, v, *, context, **params):
        super().__init__(
            target=y,
            value_dict={
                "target": y,
                "u_expression": u,
                "v_expression": v,
                "a_value": a,
            },
            context=context,
            **params,
        )

        self.requires(y)
        self.requires(u)
        self.requires(v)
        self.requires(a)


class FortranImportContainer(ImportContainer):
    """F90 version for imports"""

    INDENT_BODY = False

    def construct_code_lines(self, **_):
        """create the codelines required for the import"""
        yield f"use {self.library.libname}"


class FortranImportSectionContainer(ImportSectionContainer):
    """Fortran import section using ``use`` plus bare routine names."""

    def compose_call_name(self, importable, library):
        del library
        return importable.imported.name


###############################################################################
#
#  .oPYo.           o  8       8
#  8   `8              8       8
# o8YooP'  o    o  o8  8  .oPYo8  .oPYo.  oPYo.
#  8   `b  8    8   8  8  8    8  8oooo8  8  `'
#  8    8  8    8   8  8  8    8  8.      8
#  8oooP'  `YooP'   8  8  `YooP'  `Yooo'  8
# :......: :.....: :.. .. :.....: :.....: ..::::
# :::::::: ::::::: ::: :: ::::::: ::::::: ::::::
# :::::::: ::::::: ::: :: ::::::: ::::::: ::::::
###############################################################################


class FortranBuilder(Builder, identifier="FORTRAN"):
    """F90 Builder"""

    def create_libroutine_variable(
        self,
        *,
        name,
        dtype,
        status,
        size,
        assignment=None,
        namespace=None,
        **kwargs,
    ):
        if status & LibRoutineVariable.STATUS_BUFFER:
            return FortranBufferVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )

        status = status & 3
        if status == LibRoutineVariable.STATUS_OUTPUT:
            status |= LibRoutineVariable.STATUS_INOUT
        if status == LibRoutineVariable.STATUS_INPUT:
            return FortranInputVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        if status == LibRoutineVariable.STATUS_INOUT:
            return FortranInOutVariable(
                name=name,
                dtype=dtype,
                size=size,
                assignment=assignment,
                namespace=namespace,
                **kwargs,
            )
        return super().create_libroutine_variable(
            name=name,
            dtype=dtype,
            status=status,
            size=size,
            namespace=namespace,
            **kwargs,
        )

    def as_numeric(self, variable):
        """make a variable of a compatible numeric type"""
        return FortranNumeric(variable)

    def lookup_status(self, status):
        """map out status to inout"""
        if status.upper().strip() == "OUT":
            status = "INOUT"
        return super().lookup_status(status)

    def handle_environment_instruction(self, instruction, context, buildargs):
        yield from super().handle_environment_instruction(
            instruction, context, buildargs
        )

    def check_relevance(self, *variables, hook=None):
        """check the relevance of variable combination. Require if positive"""
        remember = []
        for var in variables:
            if var is None:
                return False
            if isinstance(var, LibRoutineVariable):
                remember.append(var)
                continue
            if abs(var) < ZERO_TOL:
                return False
        if hook is not None:
            for var in remember:
                hook.requires(var)
        return True

    def handle_affine_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        alpha = instruction_dict.get("alpha")
        beta = instruction_dict.get("beta")

        # otgt = list(tgt0.offsets)
        # osrc = list(src0.offsets)
        # yield FortranCommentLine(f"tgt0={tgt0.name} @ {otgt}", context=context)
        # yield FortranCommentLine(f"src0={src0.name} @ {osrc}", context=context)
        # yield FortranCommentLine(f"alpha = {alpha}", context=context)
        # yield FortranCommentLine(f"beta  = {beta}", context=context)

        x_var_real = context.namespace.find_assignment(
            type(src0), "real", exception_not_existing=False
        )
        x_var_imag = context.namespace.find_assignment(
            type(src0), "imag", exception_not_existing=False
        )
        y_var_real = context.namespace.find_assignment(
            type(tgt0), "real", exception_not_existing=False
        )
        y_var_imag = context.namespace.find_assignment(
            type(tgt0), "imag", exception_not_existing=False
        )

        x_var_offs = src0.offsets
        y_var_offs = tgt0.offsets
        a_real = self.wrap_lrv(alpha.real)
        a_imag = self.wrap_lrv(alpha.imag)
        b_real = self.wrap_lrv(beta.real)
        b_imag = self.wrap_lrv(beta.imag)

        combinations = [
            (y_var_real, a_real, x_var_real, b_real, 1),
            (y_var_real, a_imag, x_var_imag, b_real, -1),
            (y_var_imag, a_real, x_var_imag, b_imag, 1),
            (y_var_imag, a_imag, x_var_real, b_imag, 1),
        ]
        hook = HookContainer(context=context)
        first_real = True
        first_imag = True
        for y_var, a_val, x_var, b_val, sign in combinations:
            if y_var is y_var_real and not first_real:
                b_val = self.wrap_lrv(0.0)
            if y_var is y_var_imag and not first_imag:
                b_val = self.wrap_lrv(0.0)
            ret = self.check_relevance(y_var, a_val, x_var, b_val, hook=hook)
            if ret:
                yield FortranAffineContainer(
                    y_var.at(*y_var_offs),
                    a_val * sign,
                    x_var.at(*x_var_offs),
                    b_val,
                    context=context,
                )
                if y_var is y_var_real:
                    first_real = False
                else:
                    first_imag = False

        yield CodeLine("", context=context)

    def handle_bilinear_instruction(self, instruction, context, buildargs):
        instruction_dict = instruction.apply_environment(
            context.environment
        ).contribute_to_dict()

        tgt0 = instruction_dict.get("tgt0")
        src0 = instruction_dict.get("src0")
        src1 = instruction_dict.get("src1")
        alpha = instruction_dict.get("alpha")

        u_var_real = context.namespace.find_assignment(
            type(src0), "real", exception_not_existing=False
        )
        u_var_imag = context.namespace.find_assignment(
            type(src0), "imag", exception_not_existing=False
        )
        v_var_real = context.namespace.find_assignment(
            type(src1), "real", exception_not_existing=False
        )
        v_var_imag = context.namespace.find_assignment(
            type(src1), "imag", exception_not_existing=False
        )
        y_var_real = context.namespace.find_assignment(
            type(tgt0), "real", exception_not_existing=False
        )
        y_var_imag = context.namespace.find_assignment(
            type(tgt0), "imag", exception_not_existing=False
        )

        u_var_offs = src0.offsets
        v_var_offs = src1.offsets
        y_var_offs = tgt0.offsets
        a_real = self.wrap_lrv(alpha.real)
        a_imag = self.wrap_lrv(alpha.imag)

        include_all = False

        hook = HookContainer(context=context)

        ret = self.check_relevance(
            y_var_real, a_real, u_var_real, v_var_real, hook=hook
        )

        if ret or include_all:
            yield FortranBilinearContainer(
                y_var_real.at(*y_var_offs),
                a_real,
                u_var_real.at(*u_var_offs),
                v_var_real.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_real, a_real, u_var_imag, v_var_imag, hook=hook
        )
        if ret or include_all:
            yield FortranBilinearContainer(
                y_var_real.at(*y_var_offs),
                -a_real,
                u_var_imag.at(*u_var_offs),
                v_var_imag.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_real, a_imag, u_var_imag, v_var_real, hook=hook
        )
        if ret or include_all:
            yield FortranBilinearContainer(
                y_var_real.at(*y_var_offs),
                -a_imag,
                u_var_imag.at(*u_var_offs),
                v_var_real.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_real, a_imag, u_var_real, v_var_imag, hook=hook
        )
        if ret or include_all:
            yield FortranBilinearContainer(
                y_var_real.at(*y_var_offs),
                -a_imag,
                u_var_real.at(*u_var_offs),
                v_var_imag.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_imag, a_real, u_var_imag, v_var_real, hook=hook
        )
        if ret or include_all:
            yield FortranBilinearContainer(
                y_var_imag.at(*y_var_offs),
                a_real,
                u_var_imag.at(*u_var_offs),
                v_var_real.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_imag, a_real, u_var_real, v_var_imag, hook=hook
        )
        if ret or include_all:
            yield FortranBilinearContainer(
                y_var_imag.at(*y_var_offs),
                a_real,
                u_var_real.at(*u_var_offs),
                v_var_imag.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_imag, a_imag, u_var_real, v_var_real, hook=hook
        )
        if ret or include_all:
            yield FortranBilinearContainer(
                y_var_imag.at(*y_var_offs),
                a_imag,
                u_var_real.at(*u_var_offs),
                v_var_real.at(*v_var_offs),
                context=context,
            )

        ret = self.check_relevance(
            y_var_imag, a_imag, u_var_imag, v_var_imag, hook=hook
        )
        if ret or include_all:
            yield FortranBilinearContainer(
                y_var_imag.at(*y_var_offs),
                -a_imag,
                u_var_imag.at(*u_var_offs),
                v_var_imag.at(*v_var_offs),
                context=context,
            )
        yield CodeLine("", context=context)

    def create_external_array(
        self,
        *args,
        context,
        **kwargs,
    ):
        return Builder.create_external_array(
            self,
            *args,
            context=context,
            local_class=FortranLocalVariable,
            constant_class=FortranConstant,
        )


# set handlers for instruction classes
FortranBuilder.set_instruction_class_handler(
    AffineOperationInstruction, FortranBuilder.handle_affine_instruction
)
FortranBuilder.set_instruction_class_handler(
    BiLinearOperationInstruction, FortranBuilder.handle_bilinear_instruction
)

FortranRoutineContainer.set_comment_class(None)

FortranBuilder.set_comment_class(FortranCommentLine)
FortranBuilder.set_routinecall_class(FortranRoutineCallContainer)
register_fortran_atomic_handlers(FortranBuilder)


###############################################################################
#
#  .oPYo.
#  8   `8
# o8YooP'  .oPYo.  .oPYo.  .oPYo.  o    o  oPYo.  .oPYo.  .oPYo.
#  8   `b  8oooo8  Yb..    8    8  8    8  8  `'  8    '  8oooo8
#  8    8  8.        'Yb.  8    8  8    8  8      8    .  8.
#  8    8  `Yooo'  `YooP'  `YooP'  `YooP'  8      `YooP'  `Yooo'
# :..:::.. :.....: :.....: :.....: :.....: ..:::: :.....: :.....:
# :::::::: ::::::: ::::::: ::::::: ::::::: :::::: ::::::: :::::::
# :::::::: ::::::: ::::::: ::::::: ::::::: :::::: ::::::: :::::::
###############################################################################


class FortranComputeResource(ComputeResource):
    """A compute resource to manage parallel resources and thread-safety features"""

    DEFAULT_LOCAL_VARIABLE_CLASS = FortranLocalVariable

    def create_mfe_container(
        self, *, context, local_variable_capture, loop_capture=None
    ) -> None | MultiFrameExpandContainer:
        return FortranMultiFrameExpandContainer(
            context=context,
            local_variable_capture=local_variable_capture,
        )

    def create_combine_container(
        self, first, second, *, context, local_variable_capture
    ) -> None | MultiFrameExpandContainer:
        return FortranIntCombineExpandContainer(
            first,
            second,
            context=context,
            local_variable_capture=local_variable_capture,
        )


###############################################################################
#
# o       o  8
# 8          8
# 8      o8  8oPYo.  oPYo.  .oPYo.  oPYo.  o    o
# 8       8  8    8  8  `'  .oooo8  8  `'  8    8
# 8       8  8    8  8      8    8  8      8    8
# 8oooo   8  `YooP'  8      `YooP8  8      `YooP8
# ...... :.. :.....: ..:::: :.....: ..:::: :....8
# :::::: ::: ::::::: :::::: ::::::: :::::: ::ooP'.
# :::::: ::: ::::::: :::::: ::::::: :::::: ::...::
###############################################################################


class FortranLibRoutine(LibRoutine):
    """F90 Version of a LibRoutine, for consinstency"""


class FortranLibrary(Library):
    """F90 Version of a Library"""

    BACKEND_IDENTIFIER = "fortran"
    FILEENDING = "f90"
    INDENTSTR = "  "
    LIBROUTINE_CLASS = FortranLibRoutine
    IMPORTLINE_CLASS = FortranImportContainer
    IMPORTSECTION_CLASS = FortranImportSectionContainer
    DEFAULT_BUILDER = FortranBuilder
    DEFAULT_CONTAINER_CLASS = FortranRoutineContainer

    def __init__(
        self,
        *args,
        resource=None,
        configuration=None,
        general_configuration=None,
        **kwargs,
    ):
        if resource is None:
            resource = FortranComputeResource("FortranResource")
        super().__init__(
            *args,
            resource=resource,
            configuration=configuration,
            general_configuration=general_configuration,
            **kwargs,
        )

    @property
    def objectname(self):
        """Return the default object-file name for this library."""
        return self._get_objectname()

    def _get_objectname(self):
        return f"{self.libname}.o"

    @property
    def sharedlibname(self):
        """Return the default shared-library name for this library."""
        return self._get_sharedlibname()

    def _get_sharedlibname(self):
        return f"lib{self.libname}.so"

    @property
    def modulename(self):
        """Return the Python extension module name for this library."""
        return self._get_modulename()

    def _get_modulename(self):
        return self.libname

    @property
    def modulestampname(self):
        """Return the stamp file used to mark a completed ``f2py`` build."""
        return self._get_modulestampname()

    def _get_modulestampname(self):
        return f"{self.modulename}.f2py.stamp"

    def locate_python_module(self):
        """Return the compiled ``f2py`` extension path if it exists."""
        basepath = Path(self.basepath)
        for pattern in (
            f"{self.modulename}*.so",
            f"{self.modulename}*.pyd",
            f"{self.modulename}*.dll",
        ):
            matches = sorted(basepath.glob(pattern))
            if matches:
                return str(matches[0])
        return None

    def import_python_module(self):
        """Import and return the compiled ``f2py`` extension module."""
        module_path = self.locate_python_module()
        if module_path is None:
            raise ImportError(
                f"no compiled f2py module was found in {Path(self.basepath).resolve()}"
            )
        resolved_module_path = Path(module_path).resolve()
        spec = importlib.util.spec_from_file_location(
            self.modulename,
            resolved_module_path,
        )
        if spec is None or spec.loader is None:
            raise ImportError(
                f"cannot create import spec for {resolved_module_path}"
            )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    def generate_head_containers(self, **_):
        """make the enclosings for this container"""
        yield from self.codelines_from_text(f"MODULE {self.libname}")

    def generate_foot_containers(self, **_):
        yield from self.codelines_from_text(f"END MODULE {self.libname}")

    def generate_prmb_containers(self, **_):
        yield from self.codelines_from_text("! IMPORTS")
        yield self.import_capture
        yield from self.codelines_from_text("")
        yield from self.codelines_from_text("IMPLICIT NONE")
        yield from self.codelines_from_text("")
        yield from self.codelines_from_text("! CONSTANTS")
        yield self.definition_capture
        yield from self.codelines_from_text("")
        yield from self.codelines_from_text("CONTAINS")
        yield from self.codelines_from_text("")
        yield from self.codelines_from_text("! ROUTINES")
        yield from self.codelines_from_text("")

    def generate_clsg_containers(self, **_):
        return
        yield

    def get_to_zero_support_routine(self, dtype):
        """Return the external helper routine used to reset one buffer."""
        routine_name = f"phoenix_to_zero_{dtype}"
        existing = self[routine_name]
        if existing is not None:
            return existing
        zero_value = FortranLocalVariable(name="tmp", dtype=dtype, no_entry=True).get_zero_value()
        dtype_name = FortranLocalVariable(name="tmp", dtype=dtype, no_entry=True).lookup_dtype(dtype)
        code = [
            f"SUBROUTINE {routine_name}(buffer, size)",
            f"  {dtype_name}, intent(INOUT), dimension(size) :: buffer",
            "  integer, intent(IN) :: size",
            f"  buffer(:) = {zero_value}",
            f"END SUBROUTINE {routine_name}",
        ]
        return self._register_manual_routine(
            routine_name,
            code=code,
            arguments=[
                {
                    "name": "buffer",
                    "dtype": dtype,
                    "size": 1,
                    "status": "INOUT",
                    "assignment": ("buffer", "data"),
                },
                {
                    "name": "size",
                    "dtype": "i32",
                    "status": "IN",
                },
            ],
        )

    def get_object_target(self):
        """Create the makefile object target for the Fortran source."""
        dependencies = [*self.get_makefile_compile_dependency_targets()]
        return FortranMFTObject(
            self.relative_to_basepath(self.objectname),
            source=self.get_codefile_target(),
            dependencies=dependencies,
            configuration=self.backend_configuration,
        )

    def get_makefile_compile_dependency_targets(self):
        """Yield compile-time Fortran dependencies with module-producing objects."""
        for dependency in self.get_dependencies(recursive=False):
            target = dependency.get_object_target()
            if target is None:
                target = dependency.get_header_target()
            if target is None:
                target = dependency.get_codefile_target()
            if target is not None:
                yield target

    def get_library_target(self):
        """Create the makefile shared-library target for the Fortran source."""
        dependencies = [
            self.get_object_target(),
            *self.get_makefile_dependency_targets(),
        ]
        return FortranMFTSharedLibrary(
            self.relative_to_basepath(self.sharedlibname),
            dependencies=dependencies,
            configuration=self.backend_configuration,
        )

    def get_python_module_target(self):
        """Create the makefile target that builds the ``f2py`` module."""
        dependencies = [*self.get_makefile_compile_dependency_targets()]
        return FortranMFTPythonModule(
            self.relative_to_basepath(self.modulestampname),
            source=self.get_codefile_target(),
            module_name=self.modulename,
            output_dir=self.basepath,
            dependencies=dependencies,
            configuration=self.backend_configuration,
        )

    def get_makefile_targets(self):
        """Yield the source, object, shared-library, and Python-module targets."""
        yield self.get_codefile_target()
        yield self.get_object_target()
        yield self.get_library_target()
        yield self.get_python_module_target()

    def get_execution_target(self):
        """Build the Python extension by default for direct Python usage."""
        if getattr(self, "_is_auxiliary_library", False):
            return self.get_library_target()
        return self.get_python_module_target()

    def get_compilation_output_files(self):
        """Yield all files required for a complete compiled Fortran build."""
        yield self.modulestampname
        module_path = self.locate_python_module()
        if module_path is not None:
            yield module_path
